Repository mozilla/pdf.js, pull requests merged in 2018-10, with the labels that each got.

#9982 Use the Font Loading API in `MOZCENTRAL` builds, and `GENERIC` builds for Firefox version 63 and above (issue 9945, bug 1088663)
  src/core/fonts.js
  src/display/font_loader.js
  src/shared/compatibility.js
Labels: 1-core

#10123 Attempt to simplify the `PDFFindBar` and `PDFSidebar` constructors
  web/app.js
  web/pdf_find_bar.js
  web/pdf_outline_viewer.js
  web/pdf_sidebar.js
Labels: 1-viewer

#10126 [Regression] Restore the ability to start searching before a document has loaded, and ignore searches for previously opened documents (PR 10099 follow-up)
  web/pdf_find_controller.js
Labels: 1-viewer

#10128 Make `PDFFindController` less confusing to use, by allowing searching to start when `setDocument` is called
  examples/components/simpleviewer.js
  examples/components/singlepageviewer.js
  test/unit/pdf_find_controller_spec.js
  web/app.js
  web/base_viewer.js
  web/pdf_find_controller.js
Labels: 1-viewer

#10117 Add support of Ink annotation
  src/core/annotation.js
  src/display/annotation_layer.js
  test/pdfs/.gitignore
  test/pdfs/annotation-caret-ink.pdf
  test/test_manifest.json
  test/unit/annotation_spec.js
  web/annotation_layer_builder.css
Labels: 4-annotations

#10138 Ensure that `Toolbar.setPageScale` always sets the `pageScaleValue` property to a valid value
  web/toolbar.js
Labels: 1-viewer

#10139 Ensure that the `PDFDocumentLoadingTask` is rejected when "setting up fake worker" failed (issue 10135)
  src/display/api.js
  web/app.js
Labels: 1-core

#10133 Set returnValues.suggestedLength to Content-Length if integer
  src/display/network_utils.js
  test/unit/network_utils_spec.js
Labels: 1-core

#10140 Combine the `pdfjsFilePath` and fallback `workerSrc` handling in `src/display/api.js`
  src/display/api.js
Labels: 1-core

#10143 Ensure that `getMainThreadWorkerMessageHandler` won't accidentally break `getDocument` (PR 10139 follow-up)
  src/display/api.js
Labels: 1-core

#10150 Add missing `pagesCount` getter to `IPDFLinkService` and `SimpleLinkService`
  web/interfaces.js
  web/pdf_link_service.js
Labels: 1-viewer

#10152 Add support for `classList.toggle` with the, optional, "force" parameter
  src/shared/compatibility.js
  web/base_viewer.js
  web/pdf_find_bar.js
  web/secondary_toolbar.js
  web/toolbar.js
Labels: 1-viewer

#10155 Add Build Status Button
  README.md
Labels: 1-other

#10166 Bump version numbers for stable and beta releases
  pdfjs.config
Labels: 1-other

#10167 Export `CMapCompressionType` and `PermissionFlag` on the `pdfjsLib` object (issue 10148, PR 10033 follow-up)
  src/pdf.js
Labels: 1-other

#10168 Convert `PDFDataRangeTransport` to an ES6 class
  src/display/api.js
  web/firefoxcom.js
Labels: 1-core

#10179 Change splice to pop in annotation tests
  test/unit/annotation_spec.js
Labels: 1-test

#10187 Bump versions in `pdfjs.config`
  pdfjs.config
Labels: 1-other

#10188 Hide the beta version button on the website if there is only a stable version
  docs/contents/getting_started/index.md
  gulpfile.js
Labels: 1-other

#10162 Normalize BBox of form XObjects in SVG back-end
  src/core/evaluator.js
  src/display/canvas.js
  src/display/svg.js
Labels: 1-core, 4-svg

#10185 Reduce the number of redundant text normalization operations in `PDFFindController`
  web/pdf_find_controller.js
Labels: 1-viewer

#10182 Small clean-up of the search related methods in `TextLayerBuilder`
  web/pdf_find_controller.js
  web/text_layer_builder.js
Labels: 1-viewer

#10184 Ensure that matches are not scrolled into after the findbar has been closed (PR 10100 follow-up)
  web/pdf_find_controller.js
Labels: 1-viewer

#10196 [Regression] Ensure that "Highlight All" is propagated to all pages for 'findagain' events where the findbar was previously closed (PR 10100 follow-up)
  web/pdf_find_controller.js
Labels: 1-viewer

#10190 Add a helper method for `_getVisiblePages`, in `BaseViewer`, for the case where only a single page is displayed in the viewer
  web/base_viewer.js
  web/pdf_single_page_viewer.js
  web/pdf_viewer.js
Labels: 1-viewer

#10201 Reduce the number of redundant `updatetextlayermatches` events dispatched when calculating matches in `PDFFindController`
  web/pdf_find_controller.js
Labels: 1-viewer

#10203 Change `canvasInRendering` to a `WeakSet` instead of a `WeakMap`
  src/display/api.js
  src/shared/compatibility.js
Labels: 1-core
