Repository mozilla/pdf.js, pull requests merged in 2018-11, with the labels that each got.

#10202 Attempt to clean-up/restore pending rendering operations on `RenderTask.cancel` (issue 10200)
  src/display/api.js
Labels: 1-core

#10217 For repeated 'findagain' operations, attempt to reset the search position if the user has e.g. scrolled in the document (issue 4141)
  web/base_viewer.js
  web/interfaces.js
  web/pdf_find_controller.js
  web/pdf_link_service.js
Labels: 1-viewer

#10219 Convert `src/core/ps_parser.js` to use ES6 classes
  src/core/ps_parser.js
Labels: 1-core

#10228 Don't detect nw.js as node.js
  src/shared/is_node.js
Labels: 1-core

#10233 [api-minor] Convert `PDFObjects`, in `src/display/api.js`, to an ES6 class
  src/display/annotation_layer.js
  src/display/api.js
  src/display/canvas.js
Labels: 1-core

#10238 Move the `interface` definitions out of `src/core/worker.js` and into their own file
  src/core/worker.js
  src/interfaces.js
  web/interfaces.js
Labels: 1-core

#10245 Update `BaseViewer.scrollPageIntoView` to always validate the `pageNumber` parameter
  web/base_viewer.js
Labels: 1-viewer

#10223 When the search query changes, regardless of the search command, always re-calculate matches (bug 1030622)
  web/pdf_find_controller.js
Labels: 1-viewer

#10220 Only scroll search results into view as a result of an actual find operation, and not when the user scrolls/zooms/rotates the document (bug 1237076, issue 6746)
  web/pdf_find_controller.js
  web/text_layer_builder.js
Labels: 1-viewer

#10231 Stop scrolling the document when "Highlight All" is toggled in the findbar (issue 5561)
  web/pdf_find_controller.js
Labels: 1-viewer

#10244 Fix webpack example
  examples/webpack/package.json
Labels: 1-other

#10255 Avoid unnecessary `PDFFindController.scrollMatchIntoView` calls in `TextLayerBuilder._renderMatches` when `highlightAll` is set (PR 10201 follow-up)
  web/text_layer_builder.js
Labels: 1-viewer

#10264 Update translations and packages
  l10n/bn-IN/viewer.properties
  l10n/fa/viewer.properties
  l10n/ff/viewer.properties
  l10n/gd/viewer.properties
  l10n/hr/viewer.properties
  l10n/hu/viewer.properties
  l10n/my/viewer.properties
  l10n/pa-IN/viewer.properties
  l10n/pt-BR/viewer.properties
  package-lock.json
  package.json
  test/font/jasmine-boot.js
  test/unit/jasmine-boot.js
Labels: 1-other

#10197 use <span> instead of <div> in textLayer
  src/display/text_layer.js
  test/text_layer_test.css
  web/text_layer_builder.css
  web/viewer.css
Labels: 4-text-selection

#10246 Convert the remaining code in `src/display/api.js` to use ES6 classes
  examples/acroforms/acroforms.js
  examples/components/pageviewer.js
  examples/components/simpleviewer.js
  examples/components/singlepageviewer.js
  examples/learning/helloworld.html
  examples/learning/helloworld64.html
  examples/learning/prevnext.html
  examples/node/getinfo.js
  examples/node/pdf2png/pdf2png.js
  examples/node/pdf2svg.js
  examples/svgviewer/viewer.js
  examples/text-only/pdf2svg.js
  src/display/api.js
  src/display/canvas.js
  test/driver.js
  test/unit/api_spec.js
  test/unit/custom_spec.js
Labels: 1-core

#10274 Fallback to an exhaustive search, in corrupt PDF files, for NameTrees/NumberTrees that are not correctly ordered (issue 10272)
  src/core/obj.js
Labels: 1-core

#10294 Add ESLint plugin import to be warned against invalid paths
  .eslintrc
  package-lock.json
  package.json
  test/.eslintrc
  web/.eslintrc
Labels: 1-other

#10292 Replace uglify-es with Terser
  gulpfile.js
  package-lock.json
  package.json
Labels: 1-other

#10293 Upgrade to Babel 7
  gulpfile.js
  package-lock.json
  package.json
Labels: 1-other

#10275 Fix `NameOrNumberTree.get` to actually perform a binary search to find the requested key
  src/core/obj.js
Labels: 1-core

#10299 Update packages and translations
  l10n/bn-BD/viewer.properties
  l10n/gl/viewer.properties
  l10n/it/viewer.properties
  l10n/tl/viewer.properties
  package-lock.json
  package.json
Labels: 1-other

#10300 Include forgotten changes after Wintersmith update
  docs/templates/layout.jade
  package-lock.json
  package.json
Labels: 1-other

#10318 In `GENERIC` builds, dispatch a "webviewerloaded" event (from the `webViewerLoad` function) before initializing the viewer
  web/app.js
  web/app_options.js
  web/viewer.js
Labels: 1-viewer
