Repository mozilla/pdf.js, pull requests merged in 2018-12, with the labels that each got.

#10322 Remove unuseful variable
  examples/node/getinfo.js
Labels: 1-other

#10323 Test the code as-is, in Node.js/Travis, rather than its Babel translated version
  gulpfile.js
  package.json
Labels: 1-other

#10330 Handle line width of zero in SVG
  src/display/svg.js
Labels: 4-svg

#10304 Add protection against directory traversal attacks
  test/webserver.js
Labels: 1-other

#10295 Update eslint-plugin-mozilla to ^1.0.1
  package-lock.json
  package.json
Labels: 1-other

#10337 Turn on ESLint in examples
  .eslintignore
  examples/.eslintrc
  examples/acroforms/acroforms.js
  examples/browserify/gulpfile.js
  examples/browserify/main.js
  examples/components/simpleviewer.js
  examples/image_decoders/jpeg_viewer.js
  examples/mobile-viewer/viewer.js
  examples/node/.eslintrc
  examples/node/domstubs.js
  examples/node/getinfo.js
  examples/node/pdf2png/pdf2png.js
  examples/node/pdf2svg.js
  examples/svgviewer/viewer.js
  examples/text-only/pdf2svg.js
  examples/webpack/.eslintrc
  examples/webpack/main.js
  examples/webpack/webpack.config.js
Labels: 1-other

#10351 Attempt to ignore mouse wheel zooming during tab switches (bug 1503412)
  web/app.js
Labels: 1-viewer

#10350 Ignore the `fieldValue` for Signature annotations, since they're currently unsupported (issue 10374)
  src/core/annotation.js
Labels: 4-annotations

#10354 Disable source-map generation when running tests
  gulpfile.js
Labels: 1-test

#10356 Use high DPI icons on semi-high DPI screens.
  web/viewer.css
Labels: 1-viewer

#10358 Add keyboard shortcut to toggle sidebar (F4, same as Adobe Reader).
  web/app.js
Labels: 1-viewer

#10266 Upgrade to Gulp 4
  .travis.yml
  examples/browserify/gulpfile.js
  gulpfile.js
  package-lock.json
  package.json
Labels: 1-other

#10363 Fix small visual quirk in thumbnail viewer
  web/viewer.css
Labels: 1-viewer

#10375 Update translations and packages
  l10n/ast/viewer.properties
  l10n/bn-BD/viewer.properties
  l10n/bn-IN/viewer.properties
  l10n/ca/viewer.properties
  l10n/crh/viewer.properties
  l10n/de/viewer.properties
  l10n/gu-IN/viewer.properties
  l10n/ia/viewer.properties
  l10n/ja/viewer.properties
  l10n/ka/viewer.properties
  l10n/pl/viewer.properties
  l10n/ro/viewer.properties
  l10n/te/viewer.properties
  l10n/tl/viewer.properties
  l10n/vi/viewer.properties
  package-lock.json
  package.json
Labels: 1-other

#10334 [api-minor] Add support for OpenAction destinations (issue 10332)
  extensions/chromium/preferences_schema.json
  src/core/obj.js
  src/core/worker.js
  src/display/api.js
  test/unit/api_spec.js
  web/app.js
  web/app_options.js
  web/default_preferences.json
  web/interfaces.js
  web/pdf_history.js
Labels: 1-core

#10378 Update remaining examples, and docs, to utilize current API functionality (issue 10377)
  docs/contents/examples/index.md
  examples/learning/helloworld.html
  examples/learning/helloworld64.html
  examples/learning/prevnext.html
Labels: 1-other

#10392 Check that the first page can be successfully loaded, to try and ascertain the validity of the XRef table (issue 7496, issue 10326)
  src/core/document.js
  src/core/obj.js
  src/core/worker.js
  src/shared/util.js
  test/pdfs/issue10326.pdf.link
  test/pdfs/issue7496.pdf.link
  test/test_manifest.json
Labels: 1-core

#10394 Optimize the `Ref` class in `src/core/primitives.js`
  src/core/primitives.js
Labels: 1-core, 2-performance

#10396 Optimizations to avoid intermediate string creation
  src/display/canvas.js
  src/display/text_layer.js
Labels: 1-core, 2-performance

#10397 Ensure that `AnnotationBorderStyle.setWidth` is able to handle the input being a `Name`, to correctly deal with corrupt PDF documents (issue 10385)
  src/core/annotation.js
  test/unit/annotation_spec.js
Labels: 4-annotations
