Repository mozilla/pdf.js, pull requests merged in 2018-03, with the labels that each got.

#9494 Windows drive letter
  src/display/node_stream.js
Labels: 1-core

#9520 Attempt to fix the `Array.prototype.includes` and `String.prototype.includes` polyfills (issue 9514, 9516)
  src/shared/compatibility.js
Labels: 1-other, 3-regression

#9493 [api-major] Move the remaining options from, and completely remove, the global `PDFJS` object
  examples/acroforms/acroforms.js
  examples/browserify/main.js
  examples/components/pageviewer.js
  examples/components/simpleviewer.js
  examples/components/singlepageviewer.js
  examples/learning/helloworld.html
  examples/learning/helloworld64.html
  examples/learning/prevnext.html
  examples/mobile-viewer/viewer.js
  examples/svgviewer/viewer.js
  examples/text-only/pdf2svg.js
  gulpfile.js
  src/core/worker.js
  src/display/api.js
  src/display/api_compatibility.js
  src/display/dom_utils.js
  src/display/font_loader.js
  src/display/global.js
  src/display/text_layer.js
  src/doc_helper.js
  src/pdf.js
  src/shared/compatibility.js
  test/driver.js
  test/unit/api_spec.js
  test/unit/cmap_spec.js
  test/unit/test_utils.js
  web/app.js
  web/app_options.js
  web/base_viewer.js
  web/chromecom.js
  web/download_manager.js
  web/firefoxcom.js
  web/genericcom.js
  web/pdf_attachment_viewer.js
  web/pdf_outline_viewer.js
  web/pdf_print_service.js
  web/pdf_viewer.component.js
  web/ui_utils.js
  web/viewer.js
Labels: 1-core, 1-other, 1-test, 1-viewer

#9508 Add paper size to document information/properties
  l10n/en-US/viewer.properties
  src/display/api.js
  web/pdf_document_properties.js
  web/viewer.html
  web/viewer.js
Labels: 1-viewer

#9509 Implement a single `getInheritableProperty` utility function
  src/core/annotation.js
  src/core/document.js
  src/shared/util.js
  test/unit/util_spec.js
Labels: 1-core

#9542 [CRX] Fix error that broke the Chrome extension
  web/chromecom.js
Labels: 1-viewer, 3-regression, 4-chrome-specific

#9541 [CRX] Disable fetch in Chrome 60-
  src/pdf.js
Labels: 1-core, 3-regression, 4-chrome-specific

#9549 Attempt to handle corrupt PDF documents that inline Page dictionaries in a Kids array (issue 9540)
  src/core/obj.js
  test/pdfs/issue9540.pdf.link
  test/test_manifest.json
  web/pdf_link_service.js
Labels: 1-core

#9574 Update translations
  external/importL10n/locales.js
  l10n/lij/viewer.properties
  l10n/mn/chrome.properties
  l10n/ro/viewer.properties
  l10n/rw/chrome.properties
  l10n/sq/viewer.properties
  l10n/ta-LK/chrome.properties
  l10n/th/viewer.properties
  l10n/tn/chrome.properties
Labels: 1-other

#9577 [api-minor] Fix various issues related to pageSize, and display the size for the active page in the document properties dialog
  l10n/en-US/viewer.properties
  l10n/sv-SE/viewer.properties
  src/display/api.js
  test/unit/api_spec.js
  web/app.js
  web/pdf_document_properties.js
Labels: 1-core, 1-viewer

#9571 [Firefox addon] Refactor bundling of the `default_preferences.json` file
  extensions/firefox/content/PdfJs.jsm
  extensions/firefox/content/PdfJsDefaultPreferences.jsm
  extensions/firefox/content/PdfjsChromeUtils.jsm
  gulpfile.js
Labels: 1-addon

#9587 Move the `cursorToolOnLoad` preference handling into `AppOptions` (PR 9493 follow-up)
  web/app.js
  web/app_options.js
  web/pdf_cursor_tools.js
  web/ui_utils.js
Labels: 1-viewer

#9565 Rename the globals to shorter names.
  examples/acroforms/acroforms.js
  examples/browserify/worker.js
  examples/components/pageviewer.js
  examples/components/simpleviewer.js
  examples/components/singlepageviewer.js
  examples/learning/helloworld.html
  examples/learning/helloworld64.html
  examples/learning/prevnext.html
  examples/mobile-viewer/viewer.js
  examples/text-only/pdf2svg.js
  gulpfile.js
  src/display/api.js
  src/pdf.worker.entry.js
  test/driver.js
Labels: 1-other

#9584 Update examples/ documentation for 2.0
  docs/contents/examples/index.md
Labels: 1-other

#9573 New XML parser
  src/display/dom_utils.js
  src/display/metadata.js
  src/display/xml_parser.js
Labels: 1-core

#9594 Add stricter validation in `Catalog.readPageLabels`
  src/core/obj.js
Labels: 1-core

#9576 Update packages
  gulpfile.js
  package.json
  test/font/jasmine-boot.js
  test/unit/api_spec.js
  test/unit/evaluator_spec.js
  test/unit/jasmine-boot.js
Labels: 1-other

#9586 Ensure that `PDFPageProxy.pageSizeInches` handles non-default /Rotate entries correctly
  src/display/api.js
  test/unit/api_spec.js
  test/unit/ui_utils_spec.js
  web/pdf_document_properties.js
  web/ui_utils.js
Labels: 1-core, 1-viewer

#9593 Improve the pageSize entry in the document properties dialog, by also displaying page names and orientation
  l10n/en-US/viewer.properties
  l10n/sv-SE/viewer.properties
  test/unit/ui_utils_spec.js
  web/base_viewer.js
  web/firefoxcom.js
  web/genericl10n.js
  web/interfaces.js
  web/pdf_document_properties.js
  web/ui_utils.js
  web/viewer.html
  web/viewer.js
Labels: 1-viewer

#9611 Clean-up `getMainThreadWorkerMessageHandler` for non-PRODUCTION mode
  src/display/api.js
  web/app.js
Labels: 1-core, 1-viewer
