Repository mozilla/pdf.js, pull requests merged in 2019-10, with the labels that each got.

#11187 Convert the various image decoder `...Error`s to classes extending `BaseException` (PR 11185 follow-up)
  src/core/jbig2.js
  src/core/jpg.js
  src/core/jpx.js
Labels: 1-core

#11202 Bump versions in `pdfjs.config`
  pdfjs.config
Labels: 1-other

#11198 [PDFSidebarResizer] Add a couple of (small) readability improvements in the code
  web/pdf_sidebar_resizer.js
  web/ui_utils.js
Labels: 1-viewer

#11212 [MessageHandler] Some additional (small) clean-up of the code
  src/shared/message_handler.js
Labels: 1-core

#11186 Improve the heuristics, in `PartialEvaluator._buildSimpleFontToUnicode`, for glyphNames of the Cdd{d}/cdd{d} format (issue 9655)
  src/core/evaluator.js
  test/pdfs/.gitignore
  test/pdfs/issue9655_reduced.pdf
  test/test_manifest.json
Labels: 4-text-selection

#11209 Use square brackets for optional properties in the JSDoc comments of `src/display/api.js`
  src/display/api.js
Labels: 1-other

#11222 Remove locales which are unmaintained and/or not shipping in Nightly (PR 11213 follow-up)
  l10n/ak/chrome.properties
  l10n/ak/viewer.properties
  l10n/bn-BD/chrome.properties
  l10n/bn-BD/metadata.inc
  l10n/bn-BD/viewer.properties
  l10n/bn-IN/chrome.properties
  l10n/bn-IN/viewer.properties
  l10n/csb/chrome.properties
  l10n/csb/viewer.properties
  l10n/hto/viewer.properties
  l10n/kok/chrome.properties
  l10n/kok/viewer.properties
  l10n/ks/chrome.properties
  l10n/ks/viewer.properties
  l10n/ku/chrome.properties
  l10n/ku/viewer.properties
  l10n/lg/chrome.properties
  l10n/lg/viewer.properties
  l10n/meh/viewer.properties
  l10n/mn/viewer.properties
  l10n/nso/chrome.properties
  l10n/nso/viewer.properties
  l10n/rw/viewer.properties
  l10n/sah/chrome.properties
  l10n/sah/viewer.properties
  l10n/sat/chrome.properties
  l10n/sat/viewer.properties
  l10n/sw/chrome.properties
  l10n/sw/viewer.properties
  l10n/ta-LK/viewer.properties
  l10n/tn/viewer.properties
  l10n/tsz/chrome.properties
  l10n/tsz/viewer.properties
  l10n/zam/viewer.properties
  l10n/zu/chrome.properties
  l10n/zu/viewer.properties
Labels: 1-other

#11219 [api-minor] Replace all `deprecated` calls with throwing of actual `Error`s
  src/display/api.js
Labels: 1-core

#11218 Attempt to fallback to a default font, for non-available ones, in `PartialEvaluator.loadFont`
  src/core/evaluator.js
Labels: 4-font-conversion

#11220 Added create react app example with typescript and basic usage
  examples/create-react-app/.env
  examples/create-react-app/.gitignore
  examples/create-react-app/README.md
  examples/create-react-app/package.json
  examples/create-react-app/public/favicon.ico
  examples/create-react-app/public/helloworld.pdf
  examples/create-react-app/public/index.html
  examples/create-react-app/public/manifest.json
  examples/create-react-app/public/robots.txt
  examples/create-react-app/src/app.tsx
  examples/create-react-app/src/index.css
  examples/create-react-app/src/index.tsx
  examples/create-react-app/src/pdf.tsx
  examples/create-react-app/src/react-app-env.d.ts
  examples/create-react-app/tsconfig.json
Labels: 1-other

#11228 Enable the ESLint rule `accessor-pairs` for Classes
  .eslintrc
Labels: 1-other

#11232 Cache processed 'ExtGState's in `PartialEvaluator.hasBlendModes` to avoid unnecessary parsing/lookups
  src/core/evaluator.js
Labels: 1-core, 2-performance

#11234 Convert a number of reference tests, for documents with corrupt XRef tables, from `load` to `eq`
  test/pdfs/.gitignore
  test/pdfs/issue5909.pdf
  test/pdfs/issue5909_original.pdf.link
  test/test_manifest.json
Labels: 1-test

#11237 Update `src/shared/compatibility.js` to only run with `SKIP_BABEL = false` set
  src/shared/compatibility.js
Labels: 1-core

#11235 Improve the JSDoc comments
  extensions/chromium/extension-router.js
  extensions/chromium/pdfHandler-vcros.js
  extensions/chromium/pdfHandler.js
  gulpfile.js
  src/core/annotation.js
  src/core/ccitt.js
  src/core/colorspace.js
  src/core/core_utils.js
  src/core/evaluator.js
  src/core/fonts.js
  src/core/image.js
  src/core/obj.js
  src/core/operator_list.js
  src/display/annotation_layer.js
  src/display/api.js
  src/display/content_disposition.js
  src/display/display_utils.js
  src/display/text_layer.js
  src/interfaces.js
  src/shared/message_handler.js
  src/shared/util.js
  web/annotation_layer_builder.js
  web/app.js
  web/base_viewer.js
  web/chromecom.js
  web/firefoxcom.js
  web/grab_to_pan.js
  web/interfaces.js
  web/overlay_manager.js
  web/pdf_cursor_tools.js
  web/pdf_find_controller.js
  web/pdf_history.js
  web/pdf_link_service.js
  web/pdf_page_view.js
  web/pdf_presentation_mode.js
  web/pdf_sidebar.js
  web/pdf_sidebar_resizer.js
  web/pdf_thumbnail_view.js
  web/preferences.js
  web/secondary_toolbar.js
  web/text_layer_builder.js
  web/ui_utils.js
Labels: 1-other

#11246 Tweak the `isIOS` check, in `web/viewer_compatibility`, to attempt to support newer Safari versions (issue 11245)
  web/viewer_compatibility.js
Labels: 1-viewer, 4-os-ios

#11247 Change variable assignment
  src/core/fonts.js
Labels: 1-core

#11253 Avoid handling keyboard shortcuts for `contentEditable` DOM elements (issue 7156)
  web/app.js
Labels: 1-viewer

#11250 Silence the Autoprefixer message being printed with all build logs
  gulpfile.js
Labels: 1-other

#11257 Remove/update `skipPages` annotations from `test/test_manifest.json`
  test/test_manifest.json
Labels: 1-test

#11231 Allow over-writing entries, in `XRef.indexObjects`, only when the generation number matches (issues 11230, 11139, 9552, 9129, 7303)
  src/core/obj.js
  test/pdfs/issue11139.pdf.link
  test/pdfs/issue11230.pdf.link
  test/pdfs/issue7303.pdf.link
  test/pdfs/issue9129.pdf.link
  test/pdfs/issue9552.pdf.link
  test/test_manifest.json
Labels: 4-corrupted-pdf

#11260 Update npm packages
  package-lock.json
  package.json
Labels: 1-other

#11243 Add a fallback for non-embedded *composite* Verdana fonts (issue 11242)
  src/core/fonts.js
  test/pdfs/.gitignore
  test/pdfs/issue11242_reduced.pdf
  test/test_manifest.json
Labels: 4-font-conversion

#11261 Re-factor sending of various Exceptions from the worker to the API
  src/core/worker.js
  src/display/api.js
Labels: 1-core

#11262 Re-add the en-US `chrome.properties` l10n file, to avoid it being removed at mozilla-central (PR 11256 follow-up)
  external/importL10n/locales.js
  gulpfile.js
  l10n/en-US/chrome.properties
Labels: 1-other

#11263 Attempt to reduce resource usage, by not eagerly fetching all pages, for long/large documents
  web/base_viewer.js
Labels: 1-viewer

#11268 refactor: viewer.css refactored, duplications removed
  web/viewer.css
Labels: 1-viewer

#11271 Re-factor `StatTimer` usage, in `src/display/api.js`, and remove `DummyStatTimer`
  src/display/api.js
  src/display/display_utils.js
Labels: 1-core

#11273 [api-minor] Support custom `offsetX`/`offsetY` values in `PDFPageProxy.getViewport` and `PageViewport.clone`
  src/display/api.js
  src/display/display_utils.js
  test/unit/api_spec.js
Labels: 1-core

#11282 Update l10n files
  external/importL10n/locales.js
  l10n/cak/viewer.properties
Labels: 1-other

#11281 Support Blend Modes which are specified in an Array of Names (issue 11279)
  src/core/evaluator.js
  test/pdfs/.gitignore
  test/pdfs/issue11279.pdf
  test/test_manifest.json
Labels: 1-core

#11283 Ensure that `PartialEvaluator.hasBlendModes` handles Blend Modes in Arrays (PR 11281 follow-up)
  src/core/evaluator.js
Labels: 1-core

#11284 Make the `ObjectLoader` use more efficient methods when determining if data needs to be loaded
  src/core/chunked_stream.js
  src/core/obj.js
Labels: 1-core, 2-performance

#11294 Remove some unused `require` statements, used when loading fake workers, in non-`PRODUCTION` mode
  src/display/api.js
  web/app.js
  web/preferences.js
Labels: 1-core, 1-viewer

#11290 [MessageHandler] Re-factor and convert the code to a proper `class`
  .eslintrc
  src/shared/message_handler.js
Labels: 1-core
