Repository mozilla/pdf.js, pull requests merged in 2019-02, with the labels that each got.

#10515 Add a `settled` property, tracking the fulfilled/rejected stated of the Promise, to `createPromiseCapability`
  src/shared/util.js
  test/unit/api_spec.js
  test/unit/util_spec.js
  web/base_viewer.js
Labels: 1-core, 1-viewer

#10517 [api-minor] Remove the `document.currentScript` polyfill
  src/display/api.js
  src/shared/compatibility.js
Labels: 1-core

#10502 Modify a number of the viewer preferences, whose current default value is `0`, such that they behave as expected with the view history
  extensions/chromium/options/migration.js
  extensions/chromium/options/options.html
  extensions/chromium/preferences_schema.json
  web/app.js
  web/app_options.js
  web/base_viewer.js
  web/chromecom.js
  web/default_preferences.json
  web/pdf_sidebar.js
  web/secondary_toolbar.js
  web/ui_utils.js
Labels: 1-viewer

#10525 Convert more code to use `classList.toggle` with the `force` parameter
  web/pdf_outline_viewer.js
  web/pdf_sidebar.js
  web/secondary_toolbar.js
Labels: 1-viewer

#10527 Add a polyfill for `classList.{add, remove}` with more than one parameter
  src/shared/compatibility.js
Labels: 1-viewer

#10532 Bump base version and version prefix in `pdfjs.config`
  pdfjs.config
Labels: 1-other

#10533 Bump the version number in `pdfjs.config`
  pdfjs.config
Labels: 1-other

#10534 Try to hack-around the broken `pdfjs-dist` links, such that they will point to the main library releases (issue 10391)
  gulpfile.js
Labels: 1-other

#10530 Fix copying on supplementary plane characters
  src/core/evaluator.js
  test/pdfs/.gitignore
  test/pdfs/issue10529.pdf
  test/test_manifest.json
Labels: 4-font-conversion

#10545 Undo the `pdfjs.config` version bumps
  pdfjs.config
Labels: 1-other

#10537 Improve unit test coverage
  package-lock.json
  package.json
  test/unit/api_spec.js
  test/unit/custom_spec.js
  test/unit/test_utils.js
  test/unit/util_spec.js
Labels: 1-test

#10540 [Chrome extension] Add missing "type" entry for the `viewOnLoad` preference in the `preferences_schema.json` file (PR 10502 follow-up)
  extensions/chromium/preferences_schema.json
Labels: 1-addon, 4-chrome-specific

#10539 [api-minor] Fallback to the built-in font renderer when font loading fails
  src/core/document.js
  src/core/evaluator.js
  src/core/fonts.js
  src/core/obj.js
  src/core/pdf_manager.js
  src/core/worker.js
  src/display/api.js
  src/display/font_loader.js
  src/shared/compatibility.js
Labels: 4-font-conversion

#10557 Bump versions in `pdfjs.config`
  pdfjs.config
Labels: 1-other

#10556 [api-minor] Expose the existence of a `Collection` dictionary via the `getMetadata` API method (issue 10555)
  src/core/document.js
  test/unit/api_spec.js
Labels: 1-core

#10554 Simplify the `updatetextlayermatches` event handling in `TextLayerBuilder`
  web/pdf_page_view.js
  web/pdf_thumbnail_view.js
  web/text_layer_builder.js
Labels: 1-viewer

#10548 Generate the `default_preferences.json` file from `AppOptions`
  extensions/firefox/content/PdfJsDefaultPreferences.jsm
  gulpfile.js
  web/app.js
  web/app_options.js
  web/default_preferences.json
  web/preferences.js
Labels: 1-other

#10558 Re-factor the `PDFDataRangeTransport` unit-tests and enable them in Node.js/Travis
  test/unit/api_spec.js
  test/unit/test_utils.js
Labels: 1-test

#10560 Update translations and packages
  l10n/hr/viewer.properties
  l10n/is/viewer.properties
  l10n/ko/viewer.properties
  l10n/mr/viewer.properties
  l10n/pt-BR/viewer.properties
  l10n/si/viewer.properties
  l10n/vi/viewer.properties
  package-lock.json
  package.json
Labels: 1-other

#10579 Re-factor the `PDFSidebar` constructor to simplify its call-site (PR 10123 follow-up)
  web/app.js
  web/pdf_sidebar.js
Labels: 1-viewer

#10578 Try to *temporarily* hack around the `__non_webpack_require__` bug, and update Webpack to the latest stable version (issue 10177)
  gulpfile.js
  package-lock.json
  package.json
Labels: 1-other

#10577 Move worker-thread only functions from `src/shared/util.js` and into a new `src/core/core_utils.js` file
  src/core/annotation.js
  src/core/chunked_stream.js
  src/core/cmap.js
  src/core/core_utils.js
  src/core/document.js
  src/core/evaluator.js
  src/core/fonts.js
  src/core/glyphlist.js
  src/core/metrics.js
  src/core/obj.js
  src/core/parser.js
  src/core/pattern.js
  src/core/pdf_manager.js
  src/core/standard_fonts.js
  src/core/unicode.js
  src/core/worker.js
  src/display/annotation_layer.js
  src/display/api.js
  src/display/display_utils.js
  src/display/svg.js
  src/license_header.js
  src/license_header_libre.js
  src/pdf.js
  src/shared/util.js
  test/unit/api_spec.js
  test/unit/clitests.json
  test/unit/cmap_spec.js
  test/unit/core_utils_spec.js
  test/unit/custom_spec.js
  test/unit/display_utils_spec.js
  test/unit/jasmine-boot.js
  test/unit/util_spec.js
Labels: 1-core

#10582 Use `Promise.prototype.finally` in the `PDFRenderingQueue.renderView` method
  web/pdf_rendering_queue.js
Labels: 1-viewer

#10589 Run the `custom_spec` unit-tests in Node.js/Travis (PR 10537 follow-up)
  test/unit/clitests.json
Labels: 1-test

#10585 Load built-in CMap files using the Fetch API when possible
  src/display/display_utils.js
  src/pdf.js
  test/unit/display_utils_spec.js
  test/unit/test_utils.js
Labels: 1-core

#10573 Avoid truncating/breaking some Type3 glyphs in `compileType3Glyph` (bug 1245391, issue 10568)
  src/display/canvas.js
  test/pdfs/.gitignore
  test/pdfs/bug1245391_reduced.pdf
  test/test_manifest.json
Labels: 4-font-conversion

#10599 Update Webpack to the latest stable version (4.29.6)
  gulpfile.js
  package-lock.json
  package.json
Labels: 1-other

#10597 Ensure that the temporary canvas created in `CanvasGraphics.isFontSubpixelAAEnabled` will be cleared
  src/display/canvas.js
Labels: 1-core, 2-performance

#10595 Zero the width/height of the temporary canvas used during `JpegDecode` (issue 10594)
  src/display/api.js
Labels: 1-core, 2-performance
