Repository mozilla/pdf.js, pull requests merged in 2019-07, with the labels that each got.

#10937 Restore the header size limit of 80 KB
  gulpfile.js
Labels: 1-test

#10947 Make the `find` helper function, in `src/core/document.js`, more efficient by using `peekBytes` rather reading the stream one byte at a time
  src/core/document.js
Labels: 1-core

#10949 Delay initialization of searching, in the viewer, until the first page has rendered
  web/base_viewer.js
Labels: 1-viewer

#10960 Bump versions in `pdfjs.config`
  pdfjs.config
Labels: 1-other

#10963 Ensure that `PDFViewerApplication.{zoomIn, zoomOut}` won't run when PesentationMode is active (PR 10652 follow-up)
  web/app.js
Labels: 1-viewer

#10959 Remove the `data-pdfjsprinting` attribute on the `<body>` when destroying `FirefoxPrintService`/`PDFPrintService` instances (issue 10948)
  web/firefox_print_service.js
  web/pdf_print_service.js
Labels: 4-printing

#10962 Prevent "Uncaught promise" messages in the console when cancelling `TextLayer` tasks (PR 10601 follow-up)
  src/display/text_layer.js
Labels: 1-core

#10958 Remove the `intentState.receivingOperatorList` boolean since it's redundant
  src/display/api.js
Labels: 1-core

#10850 Scale stroking line width when using a tiling pattern.
  src/display/canvas.js
  test/pdfs/.gitignore
  test/pdfs/scorecard_reduced.pdf
  test/test_manifest.json
Labels: 4-tiling-type

#10851 Apply bounding box before using shading patterns.
  src/core/pattern.js
  src/display/pattern_helper.js
  test/pdfs/.gitignore
  test/pdfs/issue8092.pdf
  test/test_manifest.json
Labels: 4-shading-pattern

#10950 Fixed testing webserver to handle paths correctly on Windows
  test/webserver.js
Labels: 1-test

#10966 Add timestamp to the page rendered event.
  web/pdf_page_view.js
Labels: 1-viewer

#10968 Remove useless `wrapReason` calls in the `MessageHandler` class
  src/shared/message_handler.js
Labels: 1-core

#10970 Simplify, and inline, the `finalize` function in the `MessageHandler` class
  src/shared/message_handler.js
Labels: 1-core

#10969 Add an API unit-test for the `stopAtErrors` option (PRs 8240 and 8922 follow-up)
  src/display/api.js
  test/unit/api_spec.js
Labels: 1-core, 1-test

#10974 Simplify the `PDFDocument.fingerprint` method slightly
  src/core/chunked_stream.js
  src/core/document.js
  src/core/stream.js
  test/unit/api_spec.js
Labels: 1-core

#10820 Annotations - Added parsing of IRT, RT, State and StateModel
  src/core/annotation.js
  src/shared/util.js
  test/unit/annotation_spec.js
Labels: 4-annotations

#10990 Refactor the `onBeforeDraw`/`onAfterDraw` functionality used in `BaseViewer` and `PDFPageView`
  web/base_viewer.js
  web/pdf_page_view.js
Labels: 1-viewer

#10979 [Firefox] Re-factor the 'zoomreset' message handling in the viewer (PR 10652 follow-up)
  web/app.js
  web/firefoxcom.js
Labels: 1-viewer

#10986 Attempt to significantly reduce the number of `ChunkedStream.{ensureByte, ensureRange}` calls by inlining the `this.progressiveDataLength` checks at the call-sites
  src/core/chunked_stream.js
Labels: 1-core, 2-performance

#10993 Add the `docBaseUrl` API parameter to `AppOptions` in the viewer
  web/app.js
  web/app_options.js
Labels: 1-viewer

#10995 Remove an unnecessary `PDFDocumentProperties.setFileSize` call, relevant for the Firefox built-in viewer, and use the "normal" code-path in `PDFViewerApplication.open` instead
  web/app.js
Labels: 1-viewer

#11001 Inline the `isCmd` check in the `Parser.shift` method
  src/core/parser.js
  test/unit/api_spec.js
Labels: 1-core, 2-performance

#10996 Avoid creating a `PDFFindBar` instance, in the Firefox built-in viewer, when not actually necessary
  web/app.js
Labels: 1-viewer

#11003 Ensure that setting the `zoomDisabledTimeout` isn't skipped, regardless of the supported zoom keys, when handling mouse wheel events (PR 7097 follow-up)
  web/app.js
Labels: 1-viewer

#11012 Reduce the number of function calls in `EvaluatorPreprocessor.read`
  src/core/evaluator.js
Labels: 1-core, 2-performance

#11019 decode filename when match an urlencode filename from contentDispositionFilename
  src/display/network_utils.js
  test/unit/network_utils_spec.js
Labels: 1-core

#11020 Add a work-around, in `glyphlist.js`, for bad PDF generators which use a non-standard `/f_f` string in the `Encoding` dictionary when referring to the ff ligature (issue 11016)
  src/core/glyphlist.js
  test/pdfs/.gitignore
  test/pdfs/issue11016_reduced.pdf
  test/test_manifest.json
Labels: 4-font-conversion
