Repository mozilla/pdf.js, pull requests merged in 2019-12, with the labels that each got.

#11373 Slightly simplify the XRef cache lookup in `XRef.fetch`
  src/core/obj.js
Labels: 1-core, 2-performance

#11374 Set the first `pdfPage` immediately in `{BaseViewer, PDFThumbnailViewer}.setDocument`
  web/base_viewer.js
  web/pdf_thumbnail_viewer.js
Labels: 1-viewer

#11390 Ensure that `PDFDocument.checkFirstPage` waits for cleanup to complete (PR 10392 follow-up)
  src/core/document.js
  src/core/obj.js
Labels: 1-core

#11391 Replace `globalScope` with the standard `globalThis` property instead
  .eslintrc
  src/display/api.js
  src/display/text_layer.js
  src/shared/compatibility.js
  src/shared/global_scope.js
Labels: 1-core

#11387 Handle corrupt ASCII85Decode inline images with truncated EOD markers (issue 11385)
  src/core/parser.js
  test/pdfs/issue11385.pdf.link
  test/test_manifest.json
Labels: 4-image-conversion

#11398 Attempt to improve the `PDFDocument` error message for empty files (issue 5887)
  src/core/document.js
  src/core/obj.js
  test/unit/api_spec.js
Labels: 1-core

#11404 [api-minor] Move the `ReadableStream` polyfill to the global scope
  .eslintrc
  src/display/display_utils.js
  src/pdf.js
  src/shared/compatibility.js
  src/shared/message_handler.js
  src/shared/streams_polyfill.js
  src/shared/util.js
  test/unit/util_spec.js
Labels: 1-core

#11406 Re-factor the `find` helper function, in `src/core/document.js`, to search through the raw bytes rather than a string
  src/core/document.js
Labels: 1-core

#11380 Add a `reset` method to the `PDFHistory` implementation
  examples/mobile-viewer/viewer.js
  web/app.js
  web/interfaces.js
  web/pdf_history.js
Labels: 1-viewer

#11413 Re-factor the `npm test` command, used by Travis, to avoid running the 'default_preferences' tasks concurrently (issue 10732)
  gulpfile.js
  package.json
Labels: 1-test

#11415 Update `npm` packages and l10n files
  l10n/fr/viewer.properties
  l10n/hi-IN/viewer.properties
  l10n/hr/viewer.properties
  l10n/ia/viewer.properties
  l10n/ka/viewer.properties
  l10n/sq/viewer.properties
  l10n/ur/viewer.properties
  package-lock.json
  package.json
Labels: 1-dependencies

#11418 [api-minor] Simplify the *fallback* fake worker loader code in `src/display/api.js`
  examples/browserify/main.js
  examples/webpack/main.js
  gulpfile.js
  package-lock.json
  package.json
  src/display/api.js
  web/app.js
Labels: 1-core

#11422 Use the `strict` mode `assert` in the pdf2png Node.js example (issue 10768)
  examples/node/pdf2png/pdf2png.js
Labels: 1-other

#11425 Use const in viewer_compatibility.js
  web/viewer_compatibility.js
Labels: 1-viewer

#11426 Use const in viewer.js
  web/viewer.js
Labels: 1-viewer

#11427 Use const in view_history.js
  web/view_history.js
Labels: 1-viewer

#11428 Use const in ui_utils.js
  web/ui_utils.js
Labels: 1-viewer

#11429 Use const in toolbar.js
  web/toolbar.js
Labels: 1-viewer

#11436 Update webpack-stream to fix vulnerabiliy reported by npm and dedupe Webpack
  package-lock.json
  package.json
Labels: 1-dependencies

#11440 Tweak the "gets page stats after rendering page, with `pdfBug` set" unit-test to remove an intermittent failure on Travis
  test/unit/api_spec.js
Labels: 1-test

#11437 Extract & use createHeaders helper
  src/display/fetch_stream.js
Labels: 1-core

#11431 Use const in secondary_toolbar.js
  web/secondary_toolbar.js
Labels: 1-viewer

#11430 Use const in text_layer_builder.js
  web/text_layer_builder.js
Labels: 1-viewer

#11433 Use const in pdf_thumbnail_viewer.js
  web/pdf_thumbnail_viewer.js
Labels: 1-viewer

#11432 Use const in perferences.js
  web/preferences.js
Labels: 1-viewer

#11423 Ignore Metadata entries with incorrectly encoded characters, when setting the viewer title (bug 1605526)
  web/app.js
Labels: 1-viewer

#11443 Support OpenAction dictionaries without `Type` entries when parsing `Print` actions (issue 11442)
  src/core/obj.js
Labels: 1-core

#11445 Include a unit test for OpenAction dictionaries without `Type` entries (PR 11443 follow-up)
  test/pdfs/.gitignore
  test/pdfs/issue11442_reduced.pdf
  test/unit/api_spec.js
Labels: 1-test

#11449 Move the regular expression, used with auto printing in the viewer, to `web/ui_utils.js` and also use it in the API unit-tests
  test/unit/api_spec.js
  web/app.js
  web/ui_utils.js
Labels: 1-test, 1-viewer

#11450 Enable the ESLint `prefer-const` rule in the `web/` directory
  web/.eslintrc
  web/annotation_layer_builder.js
  web/app.js
  web/base_viewer.js
  web/chromecom.js
  web/debugger.js
  web/download_manager.js
  web/firefox_print_service.js
  web/firefoxcom.js
  web/genericcom.js
  web/genericl10n.js
  web/password_prompt.js
  web/pdf_attachment_viewer.js
  web/pdf_cursor_tools.js
  web/pdf_document_properties.js
  web/pdf_find_bar.js
  web/pdf_history.js
  web/pdf_link_service.js
  web/pdf_outline_viewer.js
  web/pdf_page_view.js
  web/pdf_presentation_mode.js
  web/pdf_print_service.js
  web/pdf_rendering_queue.js
  web/pdf_sidebar.js
  web/pdf_sidebar_resizer.js
  web/pdf_single_page_viewer.js
  web/pdf_thumbnail_view.js
  web/pdf_thumbnail_viewer.js
  web/preferences.js
  web/secondary_toolbar.js
  web/text_layer_builder.js
  web/toolbar.js
  web/ui_utils.js
  web/view_history.js
  web/viewer.js
  web/viewer_compatibility.js
Labels: 1-viewer

#11454 Move the SegoeUISymbol font to the `getNonStdFontMap` (PR 8698 follow-up)
  src/core/standard_fonts.js
Labels: 4-font-conversion

#11455 Update `npm` packages and l10n files
  l10n/cs/viewer.properties
  l10n/pa-IN/viewer.properties
  l10n/pl/viewer.properties
  l10n/scn/viewer.properties
  package-lock.json
  package.json
Labels: 1-dependencies, 1-other
