Repository mozilla/pdf.js, pull requests merged in 2019-06, with the labels that each got.

#10877 Ignore Annotations with too large border `width`s, to prevent the `annotationLayer` from rendering it over the surrounding document (bug 1552113)
  src/core/annotation.js
  test/pdfs/.gitignore
  test/pdfs/bug1552113.pdf
  test/test_manifest.json
Labels: 4-annotations

#10879 [api-minor] Attempt to reduce memory usage during printing, by always running `cleanup` once rendering has finished
  src/display/api.js
Labels: 4-printing

#10890 Add support for outline items, in the default viewer, which default to collapsed when the outline is built
  src/core/obj.js
  src/display/api.js
  web/pdf_outline_viewer.js
Labels: 1-core, 1-viewer

#10897 Remove a superfluous `linkService.isPageVisible` check from `PDFFindController` (PR 10217 follow-up)
  web/pdf_find_controller.js
Labels: 1-viewer

#10898 Allow experimenting with the `printResolution` AppOption when printing with the built-in Firefox version
  web/firefox_print_service.js
Labels: 1-viewer

#10905 Pin the version of `eslint-plugin-mozilla` to prevent failures on Travis (issue 10901)
  package.json
Labels: 1-test

#10903 Move `PDFWorkerStream` and related code to its own file
  src/core/worker.js
  src/core/worker_stream.js
  src/interfaces.js
Labels: 1-core

#10926 Change the signature of the `Parser` constructor to take a parameter object
  src/core/evaluator.js
  src/core/obj.js
  src/core/parser.js
  test/unit/annotation_spec.js
  test/unit/parser_spec.js
Labels: 1-core

#10925 Enable the `eslint-plugin-no-unsanitized` ESLint plugin to disallow unsafe usage of e.g. `innerHTML`
  .eslintrc
  src/core/operator_list.js
  test/driver.js
Labels: 1-other

#10902 Implement tiling patterns for the SVG back-end
  src/display/svg.js
Labels: 4-svg

#10936 Update translations and packages
  l10n/ar/viewer.properties
  l10n/be/viewer.properties
  l10n/br/viewer.properties
  l10n/de/viewer.properties
  l10n/eo/viewer.properties
  l10n/et/viewer.properties
  l10n/eu/viewer.properties
  l10n/fi/viewer.properties
  l10n/gn/viewer.properties
  l10n/he/viewer.properties
  l10n/hi-IN/viewer.properties
  l10n/hr/viewer.properties
  l10n/id/viewer.properties
  l10n/ja/viewer.properties
  l10n/kab/viewer.properties
  l10n/kk/viewer.properties
  l10n/nb-NO/viewer.properties
  l10n/ro/chrome.properties
  l10n/ro/viewer.properties
  l10n/sl/viewer.properties
  l10n/te/viewer.properties
  l10n/uk/viewer.properties
  package-lock.json
  package.json
Labels: 1-other

#10938 Reduce the number of `isCmd` calls slightly in the `XRef` class
  src/core/obj.js
Labels: 1-core, 2-performance
