Repository mozilla/pdf.js, pull requests merged in 2019-11, with the labels that each got.

#11301 Ensure that the `peekByte` methods, on the various Streams, handles end of data correctly (PR 5286 follow-up)
  src/core/chunked_stream.js
  src/core/stream.js
Labels: 1-core

#11296 Allow skipping of errors when parsing broken/unsupported ColorSpaces (issue 6707, issue 11287)
  src/core/evaluator.js
  test/pdfs/issue11287.pdf.link
  test/test_manifest.json
Labels: 1-core, 4-corrupted-pdf

#11302 Slightly re-factor setting of the link `target` in `addLinkAttributes`
  src/display/display_utils.js
Labels: 1-core

#11304 Re-factor the `ObjectLoader._walk` method to be properly asynchronous
  src/core/obj.js
Labels: 1-core

#11307 Support UTF-16 little-endian strings in the `stringToPDFString` helper function (bug 1593902)
  src/shared/util.js
  test/unit/util_spec.js
Labels: 1-core

#11308 Prevent browser exceptions from incorrectly triggering the `assert` in `PDFPageProxy._abortOperatorList` (PR 11069 follow-up)
  src/display/api.js
Labels: 1-core

#11312 Convert `Catalog.getPageDict` to an `async` method
  src/core/obj.js
Labels: 1-core

#11314 Revert "Convert `Catalog.getPageDict` to an `async` method"
  src/core/obj.js
Labels: 1-core

#11313 Ensure that Popup annotations, where the parent annotation is a polyline, will always be possible to open/close (issue 11122)
  src/display/annotation_layer.js
Labels: 4-annotations

#11305 Fix nodejs core module : ignore url module for web browser
  gulpfile.js
Labels: 1-other

#11315 Include a reduced test case for annotations without a `Border`/`BS` entry (PR 6180 follow-up)
  test/pdfs/.gitignore
  test/pdfs/issue6179_reduced.pdf
  test/test_manifest.json
Labels: 1-test

#11300 Simplifies code contributions by automating the dev setup
  .gitpod.Dockerfile
  .gitpod.yml
  README.md
Labels: 1-other

#11316 Convert `globalScope` and `isNodeJS` to proper modules
  src/core/worker.js
  src/display/api.js
  src/display/api_compatibility.js
  src/display/svg.js
  src/display/text_layer.js
  src/pdf.js
  src/shared/compatibility.js
  src/shared/global_scope.js
  src/shared/is_node.js
  test/unit/api_spec.js
  test/unit/clitests_helper.js
  test/unit/cmap_spec.js
  test/unit/custom_spec.js
  test/unit/display_svg_spec.js
  test/unit/display_utils_spec.js
  test/unit/jasmine-boot.js
  test/unit/node_stream_spec.js
  test/unit/test_utils.js
  test/unit/ui_utils_spec.js
  web/viewer.js
Labels: 1-core

#11318 [PDFHistory] Move the IE11 `pushState`/`replaceState` work-around to `src/shared/compatibility.js` (PR 10461 follow-up)
  src/shared/compatibility.js
  web/pdf_history.js
Labels: 1-viewer

#11317 Update npm packages
  package-lock.json
  package.json
Labels: 1-other

#11334 Use `getBytes`, rather than looping over `getByte`, in `FlateStream.prototype.readBlock`
  src/core/stream.js
Labels: 1-core, 2-performance

#11335 Subtract `stream.start` when getting the `startXRef` property for documents with a Linearization dictionary (issue 11330)
  src/core/document.js
  test/pdfs/issue11330.pdf.link
  test/test_manifest.json
Labels: 1-core

#11346 Ensure that attempting to print with `disableAutoFetch` set will fail gracefully (issue 11339)
  web/base_viewer.js
Labels: 4-printing

#11338 Reduce duplication when registering event listeners for the `Toolbar` buttons, and other small clean-up
  web/secondary_toolbar.js
  web/toolbar.js
Labels: 1-viewer

#11350 Convert `{BaseViewer, PDFThumbnailViewer}._pagesRequests` from an Array to a WeakMap
  web/base_viewer.js
  web/pdf_thumbnail_viewer.js
Labels: 1-viewer

#11353 Remove `document.attachEvent` code from `web/pdf_print_service.js` since it's only necessary for old IE versions
  web/pdf_print_service.js
Labels: 1-viewer

#11325 Added custom file transform function
  gulpfile.js
  package-lock.json
  package.json
Labels: 1-dependencies

#11354 Enable the `getter-return`, `no-dupe-else-if`, and `no-setter-return` ESLint rules
  .eslintrc
  l10n/bn/viewer.properties
  l10n/ia/viewer.properties
  l10n/mr/viewer.properties
  l10n/pt-PT/viewer.properties
  package-lock.json
  package.json
  src/core/cmap.js
  src/display/font_loader.js
  web/interfaces.js
Labels: 1-dependencies, 1-other

#11356 Remove outdated, and misleading, JSDoc comment from the `PDFDocument` class
  src/core/document.js
Labels: 1-other

#11363 Remove the `Number.isInteger` checks from `XRef.fetchUncompressed` (PR 8857 follow-up)
  src/core/obj.js
Labels: 1-core, 2-performance

#11370 Stop caching Streams in `XRef.fetchCompressed`
  src/core/obj.js
Labels: 1-core
