Repository mozilla/pdf.js, pull requests merged in 2019-09, with the labels that each got.

#11110 Remove support for the `scope` parameter in the `MessageHandler.on` method
  src/display/api.js
  src/shared/message_handler.js
Labels: 1-core, 2-performance

#11111 Inline the `resolveCall` helper function at its call-sites in `MessageHandler`
  src/shared/message_handler.js
Labels: 1-core

#11112 Remove the API/Worker version warning message in `TESTING` mode
  src/core/worker.js
  src/display/api.js
Labels: 1-core, 1-test

#11108 Use more ES6 syntax in the annotation code
  src/core/annotation.js
  src/display/annotation_layer.js
Labels: 1-core

#11115 Ensure that `Error`s are handled correctly when using `postMessage` with Streams in `MessageHandler`
  src/shared/message_handler.js
  test/unit/message_handler_spec.js
Labels: 1-core

#11123 [api-minor] Remove the `postMessageTransfers` parameter, and thus the ability to manually disable transferring of data, from the API
  src/core/worker.js
  src/display/api.js
  web/app_options.js
Labels: 1-core, 2-performance

#11118 Transfer, rather than copy, CMap data to the worker-thread
  src/core/evaluator.js
  src/display/api.js
Labels: 1-core, 2-performance

#11127 Update the `eslint-plugin-mozilla` to the latest version (PR 10905 follow-up)
  extensions/firefox/content/PdfJsDefaultPreferences.jsm
  extensions/firefox/tools/l10n.js
  package-lock.json
  package.json
Labels: 1-dependencies

#11129 Prevent "offsetParent is not set -- cannot scroll" errors when the viewer loads in e.g. a hidden <iframe>
  web/app.js
Labels: 1-viewer

#11133 Enable the `no-async-promise-executor` ESLint rule
  .eslintrc
Labels: 1-test

#11130 Don't `enqueue` unused properties when sending 'GetOperatorList' data from the worker-thread (PR 11069 follow-up)
  src/core/operator_list.js
  src/display/api.js
Labels: 1-core

#11138 [CRX] Ignore auto-generated <embed> from Chrome
  extensions/chromium/contentscript.js
Labels: 1-addon, 4-chrome-specific

#11134 Ensure that `addLinkAttributes` is always called with a valid `url` parameter
  src/display/annotation_layer.js
  src/display/display_utils.js
Labels: 1-core

#11142 Stop dispatching a "localized" event from the webL10n library, since it's unused and may clash with the default viewer
  external/webL10n/l10n.js
Labels: 1-other

#11106 Abort, with a small delay, `getOperatorList` on the worker-thread when rendering is cancelled (PR 11069 follow-up)
  src/display/api.js
Labels: 1-core

#11145 Update translations and packages
  l10n/ast/viewer.properties
  l10n/brx/viewer.properties
  l10n/ca/viewer.properties
  l10n/he/viewer.properties
  l10n/it/viewer.properties
  l10n/zh-TW/viewer.properties
  package-lock.json
  package.json
Labels: 1-dependencies, 1-other

#11155 Miscellaneous (small) clean-up of the `MessageHandler` code
  src/shared/message_handler.js
Labels: 1-core

#11159 For Type1 fonts, replace missing font dictionary /Widths entries with ones from the font data (issue 11150)
  src/core/fonts.js
  src/core/type1_parser.js
  test/pdfs/.gitignore
  test/pdfs/issue11150_reduced.pdf
  test/test_manifest.json
  test/unit/type1_parser_spec.js
Labels: 4-corrupted-pdf, 4-font-conversion

#11158 Avoid floating point inaccuracy in gradient color stops
  src/core/pattern.js
  test/pdfs/.gitignore
  test/pdfs/issue7339_reduced.pdf
  test/test_manifest.json
Labels: 2-image-quality, 4-shading-pattern

#11163 Fix the link in the doc website
  docs/contents/getting_started/index.md
Labels: 1-other

#11146 Replace our `URL` polyfill with the one from `core-js`
  .eslintrc
  external/url/url-lib.js
  gulpfile.js
  package-lock.json
  package.json
  src/display/api.js
  src/display/display_utils.js
  src/pdf.js
  src/shared/compatibility.js
  src/shared/url_polyfill.js
  src/shared/util.js
  systemjs.config.js
  test/unit/util_spec.js
  web/app.js
  web/chromecom.js
  web/download_manager.js
  web/firefoxcom.js
  web/pdf_print_service.js
Labels: 1-core, 1-viewer

#11165 Enable a couple of `return` related ESLint rules
  .eslintrc
  web/pdf_print_service.js
Labels: 1-other

#11168 Remove unmaintained localizations and update translations and packages
  external/importL10n/locales.js
  l10n/as/chrome.properties
  l10n/as/viewer.properties
  l10n/crh/chrome.properties
  l10n/crh/viewer.properties
  l10n/en-ZA/chrome.properties
  l10n/en-ZA/viewer.properties
  l10n/mai/chrome.properties
  l10n/mai/viewer.properties
  l10n/ml/chrome.properties
  l10n/ml/viewer.properties
  l10n/or/chrome.properties
  l10n/or/viewer.properties
  l10n/tl/viewer.properties
  package-lock.json
  package.json
Labels: 1-other

#11171 Fix the inconsistent return types for `Dict.{get, getAsync}`
  src/core/primitives.js
  test/unit/primitives_spec.js
Labels: 1-core

#11173 Replace the bundled `ReadableStream` polyfill with the `web-streams-polyfill` npm package (issue 11157)
  .eslintignore
  .eslintrc
  external/streams/LICENSE.md
  external/streams/README.md
  external/streams/streams-lib.js
  gulpfile.js
  package-lock.json
  package.json
  src/shared/streams_polyfill.js
  systemjs.config.js
Labels: 1-core

#11169 Reduce the number of function calls in the `Dict` class
  src/core/primitives.js
Labels: 1-core, 2-performance

#11185 Convert the various `...Exception`s to proper classes, to reduce code duplication
  src/core/core_utils.js
  src/display/display_utils.js
  src/shared/util.js
Labels: 1-core

#11182 Forbid sending of `Dict`s and `Stream`s, with `postMessage`, when workers are disabled
  src/display/api.js
Labels: 1-core
