Repository mozilla/pdf.js, pull requests merged in 2019-04, with the labels that each got.

#10706 Add missing `hasChildNodes` polyfill to `domstubs.js` (PR 10022 follow-up)
  examples/node/domstubs.js
Labels: 1-other

#10675 [Firefox regression] Fix `disableRange=true` bug in `PDFDataTransportStream`
  src/display/api.js
  src/display/transport_stream.js
  test/unit/api_spec.js
  web/firefoxcom.js
Labels: 1-core, 3-regression

#10713 Remove `src/core/annotation.js` from the `gulp jsdoc` build target
  gulpfile.js
  src/display/api.js
Labels: 1-other

#10678 Remove `moz-chunked-arraybuffer` support, and related code, from `src/display/network.js`
  src/display/network.js
Labels: 1-core

#10709 [api-minor] Add basic support for PageLayout in the API and the viewer
  src/core/obj.js
  src/core/worker.js
  src/display/api.js
  test/unit/api_spec.js
  web/app.js
Labels: 1-core, 1-viewer

#10714 [Firefox] Ensure that loading progress is reported, and the loadingBar updated, when `disableRange=true` is set
  src/display/api.js
  src/display/transport_stream.js
  web/firefoxcom.js
Labels: 1-core, 1-viewer

#10674 Convert `src/display/svg.js` to ES6 syntax and implement `setRenderingIntent` and `setFlatness` for the SVG backend
  src/display/canvas.js
  src/display/svg.js
Labels: 4-svg

#10715 Add test for fetch_stream
  test/unit/fetch_stream_spec.js
  test/unit/jasmine-boot.js
Labels: 1-test

#10725 Attempt to clarify the `l10n` section of `CONTRIBUTING.md`
  .github/CONTRIBUTING.md
Labels: 1-other

#10723 Implement caret annotations
  src/core/annotation.js
  src/display/annotation_layer.js
  web/annotation_layer_builder.css
Labels: 4-annotations

#10728 Annotations - _preparePopup method replaced with MarkupAnnotation
  src/core/annotation.js
Labels: 4-annotations

#10696 Update `ChunkedStream.makeSubStream` to actually check if (some) data exists when the `length` parameter is undefined
  src/core/chunked_stream.js
Labels: 1-core

#10694 Avoid dispatching range requests to fetch PDF data that's already loaded with streaming (PR 10675 follow-up)
  src/display/api.js
  src/display/fetch_stream.js
  src/display/node_stream.js
  src/display/transport_stream.js
Labels: 1-core

#10733 Update translations and packages
  l10n/ka/chrome.properties
  l10n/ko/viewer.properties
  l10n/vi/viewer.properties
  package-lock.json
  package.json
Labels: 1-other

#10735 Implement free text annotations
  src/core/annotation.js
  src/display/annotation_layer.js
  test/pdfs/.gitignore
  test/pdfs/annotation-freetext.pdf
  test/test_manifest.json
  web/annotation_layer_builder.css
Labels: 4-annotations

#10742 [Firefox] Avoid displaying the indeterminate loadingBar when `disableStream=true` is set (PR 10714 follow-up)
  src/display/transport_stream.js
Labels: 1-core

#10746 Add links to PDF.js homepage and API reference in README.md
  README.md
Labels: 1-other

#10727 Support (rare) Type3 fonts which contains image resources (issue 10717)
  src/core/evaluator.js
  src/display/api.js
  src/display/canvas.js
  test/pdfs/issue10717.pdf.link
  test/test_manifest.json
Labels: 4-font-conversion

#10754 Add a `getDocId` method to the `idFactory`, in `Page` instances, to avoid passing around `PDFManager` instances unnecessarily (PR 7941 follow-up)
  src/core/annotation.js
  src/core/document.js
  src/core/evaluator.js
  test/unit/annotation_spec.js
  test/unit/document_spec.js
  test/unit/evaluator_spec.js
  test/unit/test_utils.js
Labels: 1-core

#10738 [api-minor] Add support for ViewerPreferences in the API (issue 10736)
  src/core/obj.js
  src/core/worker.js
  src/display/api.js
  test/unit/api_spec.js
Labels: 1-core

#10765 Add `passive: false` to the `wheel` event listener, to work-around broken default behaviour in Chrome 73 and above (issue 10761)
  web/app.js
Labels: 1-viewer
