Repository mozilla/pdf.js, pull requests merged in 2019-08, with the labels that each got.

#11033 Ensure that the loading indicator, in the pageNumber input, is hidden when the viewer is closed
  web/toolbar.js
Labels: 1-viewer

#11029 [api-minor] Update telemetry to use 'categorical' histograms.
  src/core/parser.js
  src/shared/util.js
  web/app.js
Labels: 1-viewer

#11034 Ensure that `ReadableStream`s are cancelled with actual Errors
  src/core/chunked_stream.js
  src/core/pdf_manager.js
  src/core/worker.js
  src/display/api.js
  test/unit/fetch_stream_spec.js
  test/unit/message_handler_spec.js
  test/unit/network_spec.js
  test/unit/node_stream_spec.js
Labels: 1-core

#11038 [api-minor] Fix completely broken `getStats` method by returning stats in Objects, rather than in Arrays (PR 11029 follow-up)
  src/core/obj.js
  src/display/api.js
  test/unit/api_spec.js
Labels: 1-core

#11013 [api-minor] Implement quadpoints for annotations in the core layer
  src/core/annotation.js
  test/unit/annotation_spec.js
Labels: 1-core, 4-annotations

#11048 Use more compact keys in `PDFLinkService._pagesRefCache`
  web/pdf_link_service.js
Labels: 1-viewer

#11047 Support corrupt PDF files with invalid/non-existent Group /CS entries (issue 11045)
  src/core/evaluator.js
  test/pdfs/.gitignore
  test/pdfs/issue11045.pdf
  test/test_manifest.json
Labels: 1-core

#11051 Actually compare the `cropBox` and `mediaBox` correctly in the `Page.view` getter
  src/core/document.js
Labels: 1-core

#11057 Handle some corrupt/truncated JPEG images that are missing the EOI (End of Image) marker (issue 11052)
  src/core/jpg.js
  test/pdfs/issue11052.pdf.link
  test/test_manifest.json
Labels: 1-core, 4-corrupted-pdf

#11059 Fallback gracefully when encountering corrupt PDF files with empty /MediaBox and /CropBox entries
  src/core/document.js
  src/shared/util.js
  test/pdfs/.gitignore
  test/pdfs/boundingBox_invalid.pdf
  test/test_manifest.json
  test/unit/api_spec.js
Labels: 1-core

#11062 Miscellaneous small clean-up of code in the `web/` folder
  web/app.js
  web/pdf_sidebar.js
Labels: 1-viewer

#11064 Convert the `src/shared/util.js` file to ES6 syntax
  src/core/document.js
  src/shared/util.js
Labels: 1-core

#11070 Inline the `isString` check in the `Parser.getObj` method
  src/core/parser.js
Labels: 1-core, 2-performance

#11073 Move polyfill for codePointAt to String prototype.
  src/shared/compatibility.js
Labels: 1-core

#11076 Replace the `XRef.cache` Array with a Map instead
  src/core/obj.js
Labels: 1-core, 2-performance

#11081 added in information about pdfjs/webpack
  examples/webpack/README.md
Labels: 1-other

#11079 [TextLayer] Only cache the current `textDiv` style when `enhanceTextSelection` is enabled and use template strings in `expandTextDivs``
  src/display/text_layer.js
Labels: 1-core, 2-performance

#11086 [TextLayer] Only cache the `originalTransform` when `enhanceTextSelection` is enabled
  src/display/text_layer.js
Labels: 1-core, 2-performance

#11091 [TextLayer] Only handle positive padding values in `expandTextDivs`
  src/display/text_layer.js
Labels: 1-core, 2-performance

#11090 [TextLayer] Use an Array to build the total `transform`, rather than concatenating Strings, in `expandTextDivs`
  src/display/text_layer.js
Labels: 1-core, 2-performance

#11093 Shorthand afterPrint signature in app.js
  web/app.js
Labels: 1-viewer

#11092 [TextLayer] Use an Array to build the total `padding`, rather than concatenating Strings, in `expandTextDivs`
  src/display/text_layer.js
Labels: 1-core, 2-performance

#11069 Use streams for OperatorList chunking (issue 10023)
  src/core/document.js
  src/core/evaluator.js
  src/core/operator_list.js
  src/core/worker.js
  src/display/api.js
  test/unit/evaluator_spec.js
Labels: 1-core, 2-performance

#11096 Update translations/packages and upgrade to `eslint` version 6
  examples/.eslintrc
  examples/mobile-viewer/viewer.js
  l10n/az/viewer.properties
  l10n/bg/chrome.properties
  l10n/es-MX/viewer.properties
  l10n/hi-IN/viewer.properties
  l10n/ia/viewer.properties
  l10n/ka/viewer.properties
  l10n/meh/viewer.properties
  l10n/pa-IN/viewer.properties
  l10n/pt-PT/viewer.properties
  l10n/rm/viewer.properties
  l10n/tl/viewer.properties
  package-lock.json
  package.json
Labels: 1-dependencies

#11095 Include a reduced, non-linked PDF file for the attachments API unit test
  test/pdfs/.gitignore
  test/pdfs/attachment.pdf
  test/unit/api_spec.js
Labels: 1-test

#11097 [TextLayer] Only measure the width of the text, in `_layoutText`, for multi-char text divs
  src/display/text_layer.js
Labels: 1-core, 2-performance

#11104 [TextLayer] Avoid unnecessary font updates in `_layoutText` and remove `setAttribute` usage in `appendText`
  src/display/text_layer.js
Labels: 4-text-selection

#11107 Various `MessageHandler` improvements when using Streams
  src/display/api.js
  src/shared/message_handler.js
Labels: 1-core, 2-performance
