Repository mozilla/pdf.js, pull requests merged in 2020-11, with the labels that each got.

#12560 Update `npm` packages
  package-lock.json
  package.json
Labels: 1-dependencies

#12561 Fix some static static analyzer warnings (issue 11965)
  src/shared/fonts_utils.js
  web/chromecom.js
  web/debugger.js
  web/firefoxcom.js
  web/genericcom.js
Labels: 1-core, 1-viewer

#12562 Try adding a very basic `lgtm.yml` file, to prevent LGTM complaining about unused variables (issue 11965)
  lgtm.yml
Labels: 1-other

#12555 Replace css color rgb(...) by #...
  src/core/pattern.js
  src/display/annotation_layer.js
  src/display/canvas.js
  src/display/pattern_helper.js
  src/display/svg.js
  src/shared/util.js
Labels: 1-core, 2-performance

#12559 Also update the browser history when the user *manually* change pages using the pageNumber-input (PR 12493 follow-up)
  web/app.js
  web/base_viewer.js
  web/interfaces.js
  web/pdf_history.js
  web/pdf_link_service.js
Labels: 1-viewer

#12505 Split highlight annotation div into multiple divs
  src/core/annotation.js
  src/display/annotation_layer.js
Labels: 4-annotations

#12572 Change the `getVisibleElements` helper function to take a parameter object
  test/unit/ui_utils_spec.js
  web/base_viewer.js
  web/pdf_thumbnail_viewer.js
  web/ui_utils.js
Labels: 1-viewer

#12568 [api-minor] JS -- Add default value in annotation data
  src/core/annotation.js
  test/unit/annotation_spec.js
Labels: 4-annotations

#12583 Add global caching, for /Resources without blend modes, and use it to reduce repeated fetching/parsing in `PartialEvaluator.hasBlendModes`
  src/core/document.js
  src/core/evaluator.js
  src/core/obj.js
  src/core/primitives.js
Labels: 1-core, 2-performance

#12564 Make sure that Popup is rendered next to trigger for textAnnotation
  src/display/annotation_layer.js
  test/pdfs/.gitignore
  test/pdfs/pr12564.pdf
  test/test_manifest.json
Labels: 4-annotations

#12530 JS -- Add 'util' object
  gulpfile.js
  src/scripting_api/util.js
  test/unit/clitests.json
  test/unit/jasmine-boot.js
  test/unit/scripting_spec.js
Labels: 1-core

#12591 Improve the Pattern-detection in `CanvasGraphics.stroke`
  src/display/canvas.js
  src/display/pattern_helper.js
Labels: 1-core

#12594 Enable the ESLint `no-useless-escape` rule (PR 12551 follow-up)
  .eslintrc
  external/builder/builder.js
  gulpfile.js
  src/scripting_api/util.js
  src/shared/util.js
  test/webserver.js
  web/app.js
  web/debugger.js
  web/ui_utils.js
Labels: 1-core

#12595 Convert files in the `src/display/`-folder to use optional chaining where possible
  src/display/api.js
  src/display/canvas.js
  src/display/fetch_stream.js
  src/display/font_loader.js
  src/display/svg.js
  src/display/text_layer.js
  src/display/transport_stream.js
  src/display/webgl.js
Labels: 1-core

#12598 Fail early, in modern `GENERIC` builds, if `globalThis` isn't available (PR 11799 follow-up, issue 12596)
  src/core/worker.js
Labels: 1-core

#12546 [api-minor] JS -- Add listener for sandbox events only if there are some actions
  src/core/document.js
  src/core/worker.js
  src/display/annotation_layer.js
  src/display/api.js
  src/scripting_api/field.js
  test/unit/annotation_spec.js
  test/unit/document_spec.js
  web/annotation_layer_builder.js
  web/app.js
  web/base_viewer.js
  web/interfaces.js
  web/pdf_page_view.js
  web/ui_utils.js
Labels: 1-core

#12582 JS -- Implement doc object
  src/scripting_api/constants.js
  src/scripting_api/doc.js
  src/scripting_api/initialization.js
  src/scripting_api/print_params.js
  web/app.js
Labels: 1-core, 1-viewer

#12585 Fix popup for highlights without popup (follow-up of #12505)
  src/display/annotation_layer.js
  test/pdfs/.gitignore
  test/pdfs/issue12504.pdf
  test/test_manifest.json
Labels: 4-annotations

#12613 Trigger cleanup, once rendering has finished, in `PDFThumbnailView.draw`
  web/base_viewer.js
  web/interfaces.js
  web/pdf_link_service.js
  web/pdf_thumbnail_view.js
Labels: 1-viewer, 2-performance

#12616 Improve the cleanup functionality for thumbnails
  web/pdf_thumbnail_view.js
  web/pdf_thumbnail_viewer.js
Labels: 1-viewer

#12618 Ensure that rendering of thumbnails work correctly on HiDPI displays (issue 9820)
  web/pdf_thumbnail_view.js
Labels: 1-viewer

#12621 Follow-up for #12585: set elements class in render instead of in _createQuadrilaterals
  src/display/annotation_layer.js
Labels: 4-annotations

#12622 Some `hasJSActions`, and general annotation-code, related cleanup in the viewer and API
  .eslintrc
  external/builder/preprocessor2.js
  gulpfile.js
  package.json
  src/display/api.js
  web/annotation_layer_builder.js
  web/base_viewer.js
  web/pdf_page_view.js
Labels: 1-core, 1-viewer

#12569 JS -- Fix events dispatchment and add tests
  src/display/annotation_layer.js
  src/scripting_api/doc.js
  src/scripting_api/event.js
  src/scripting_api/field.js
  src/scripting_api/initialization.js
  test/unit/scripting_spec.js
  web/app.js
Labels: 1-core

#12625 Add a new preference, `viewerCssTheme`, to allow forcing the use of the light/dark viewer CSS themes (issue 12290)
  extensions/chromium/preferences_schema.json
  web/app.js
  web/app_options.js
Labels: 1-viewer

#12630 Reduce, now unnecessary, asynchronicity in the `BasePreferences` constructor
  web/preferences.js
Labels: 1-viewer

#12636 Add an `AppOptions.setAll` method, and use it in `PDFViewerApplication._readPreferences`
  web/app.js
  web/app_options.js
Labels: 1-viewer

#12567 [api-minor] JS -- hidden annotations must be built in case a script show them
  src/core/annotation.js
  src/core/document.js
  src/display/annotation_layer.js
  src/display/annotation_storage.js
  test/pdfs/.gitignore
  test/pdfs/160F-2019.pdf
  test/test_manifest.json
  test/unit/annotation_spec.js
  test/unit/annotation_storage_spec.js
Labels: 4-annotations

#12642 [api-minor] Add "contentLength" to the information returned by the `getMetadata` method
  src/display/api.js
  test/unit/api_spec.js
  web/app.js
  web/pdf_document_properties.js
Labels: 1-core, 1-viewer

#12645 Convert the `PDFDocumentProperties.open` method to be async
  web/pdf_document_properties.js
Labels: 1-viewer

#12647 Update Puppeteer to version 5.5.0
  package-lock.json
  package.json
Labels: 1-dependencies

#12655 Parenthesis in names are not escaped when saving
  src/core/core_utils.js
  test/unit/core_utils_spec.js
Labels: 1-core, 4-annotations, 4-form-acroform

#12662 Check the top-level /Pages dictionary when finding the trailer in `XRef.indexObjects` (issue 12402)
  src/core/obj.js
  test/pdfs/issue12402.pdf.link
  test/test_manifest.json
Labels: 1-core

#12652 Add a README about quickjs-eval.js file (build and license)
  external/quickjs/README.md
Labels: 1-other

#12665 Update packages and translations
  external/builder/builder.js
  gulpfile.js
  l10n/el/viewer.properties
  l10n/eu/viewer.properties
  l10n/oc/viewer.properties
  l10n/pt-BR/viewer.properties
  package-lock.json
  package.json
  src/core/cmap.js
  src/core/worker.js
  src/scripting_api/util.js
  test/unit/evaluator_spec.js
  test/unit/pdf_find_controller_spec.js
Labels: 1-dependencies
