Repository mozilla/pdf.js, pull requests merged in 2020-03, with the labels that each got.

#11556 Fix the vertical writing mode with horizontal scaling. #11555.
  src/display/canvas.js
  test/pdfs/.gitignore
  test/pdfs/issue11555.pdf
  test/test_manifest.json
Labels: 1-core

#11654 Simplify the `BaseFontLoader.isFontLoadingAPISupported` getter
  src/display/font_loader.js
Labels: 1-core

#11631 [api-minor] Deprecate `getGlobalEventBus` and update the "viewer components" examples accordingly
  examples/acroforms/acroforms.js
  examples/components/pageviewer.js
  examples/components/simpleviewer.js
  examples/components/singlepageviewer.js
  examples/mobile-viewer/viewer.js
  examples/svgviewer/viewer.js
  web/app.js
  web/base_viewer.js
  web/interfaces.js
  web/pdf_attachment_viewer.js
  web/pdf_cursor_tools.js
  web/pdf_document_properties.js
  web/pdf_find_bar.js
  web/pdf_find_controller.js
  web/pdf_history.js
  web/pdf_outline_viewer.js
  web/pdf_page_view.js
  web/pdf_sidebar.js
  web/pdf_sidebar_resizer.js
  web/pdf_single_page_viewer.js
  web/pdf_viewer.component.js
  web/secondary_toolbar.js
  web/text_layer_builder.js
  web/toolbar.js
  web/ui_utils.js
  web/viewer.js
Labels: 1-viewer

#11660 Fix Type1 font parsing when .notdef is not at index zero
  src/core/type1_parser.js
  test/pdfs/.gitignore
  test/pdfs/issue11477_reduced.pdf
  test/test_manifest.json
Labels: 4-font-conversion

#11653 Ensure that there's always a setFont (Tf) operator before text rendering operators (issue 11651)
  src/core/evaluator.js
  test/pdfs/.gitignore
  test/pdfs/issue11651.pdf
  test/test_manifest.json
Labels: 4-corrupted-pdf

#11664 Prevent the zoom dropdown icon from being overridden when the element is `:active` (bug 1619595)
  web/viewer.css
Labels: 1-viewer

#11672 Slightly simplify the lookup of data in `Dict.{get, getAsync, has}`
  src/core/evaluator.js
  src/core/primitives.js
  test/unit/primitives_spec.js
Labels: 1-core, 2-performance

#11673 Update the `FontLoader.bind` method to avoid explicitly returning `undefined`
  src/display/font_loader.js
Labels: 1-core

#11667 Add a deprecation warning for the `eventBusDispatchToDOM` option/preference (PR 11631 follow-up)
  web/ui_utils.js
Labels: 1-core

#11523 Add a heuristic, in `src/core/jpg.js`, to handle JPEG images with a wildly incorrect SOF (Start of Frame) `scanLines` parameter (issue 10880)
  src/core/evaluator.js
  src/core/image_utils.js
  src/core/jpeg_stream.js
  src/core/jpg.js
  test/pdfs/issue10880.pdf.link
  test/test_manifest.json
Labels: 4-image-jpeg

#11675 Fix typo in comment
  web/app.js
Labels: 1-viewer

#11676 Slightly improve the `BaseViewer.{firstPagePromise, onePageRendered, pagesPromise}` functionality
  web/app.js
  web/base_viewer.js
Labels: 1-viewer

#11680 Prevent lookup errors in `PartialEvaluator.hasBlendModes` from breaking all parsing/rendering of a page (issue 11678)
  src/core/evaluator.js
  src/core/parser.js
  test/pdfs/issue11678.pdf.link
  test/test_manifest.json
Labels: 4-corrupted-pdf

#11690 Remove transition effects from toolbar buttons/fields
  web/viewer.css
Labels: 1-viewer

#11686 Magnifier positioning in reftest analyzer
  test/resources/reftest-analyzer.html
  test/resources/reftest-analyzer.js
Labels: 1-test

#11692 Move `IsLittleEndianCached`/`IsEvalSupportedCached` to `src/shared/util.js`, and rename the `isSpace` helper function to `isWhiteSpace`
  src/core/core_utils.js
  src/core/document.js
  src/core/fonts.js
  src/core/function.js
  src/core/parser.js
  src/core/ps_parser.js
  src/core/stream.js
  src/core/type1_parser.js
  src/display/canvas.js
  src/display/font_loader.js
  src/shared/util.js
  test/unit/core_utils_spec.js
Labels: 1-core

#11695 Remove variable shadowing from the JavaScript files in the `web/` folder
  web/app.js
  web/debugger.js
  web/pdf_document_properties.js
  web/pdf_find_controller.js
  web/pdf_print_service.js
  web/pdf_sidebar.js
Labels: 1-viewer

#11644 [api-minor] Add more general OpenAction support (PR 10334 follow-up, issue 11642)
  src/core/obj.js
  src/core/worker.js
  src/display/api.js
  test/unit/api_spec.js
  web/app.js
Labels: 1-core

#11553 Fix the horizontal scaling of texts with SVG backend. #10988
  src/display/svg.js
Labels: 4-svg

#11698 Don't accidentally accept invalid glyphNames which *appear* to follow the Cdd{d}/cdd{d} format in `PartialEvaluator._buildSimpleFontToUnicode` (issue 11697)
  src/core/evaluator.js
  test/pdfs/.gitignore
  test/pdfs/issue11697_reduced.pdf
  test/test_manifest.json
Labels: 4-font-conversion

#11700 Ensure that the JavaScript-warning is always displayed, in the viewer, regardless of browser printing support
  web/app.js
Labels: 1-viewer

#11706 Move the `webViewerOpenFile` function, and the "openfile" eventBus listener, since they only matter in GENERIC builds of the default viewer
  web/app.js
Labels: 1-viewer

#11711 Update packages and translations
  l10n/az/viewer.properties
  l10n/ca/viewer.properties
  l10n/ko/viewer.properties
  package-lock.json
  package.json
Labels: 1-other

#11716 [api-minor] Change the pageIndex, on `PDFPageProxy` instances, to a private property
  src/display/api.js
  test/unit/api_spec.js
  web/pdf_page_view.js
Labels: 1-core

#11717 Bump versions in `pdfjs.config` and update the getting started page of the website for the new release
  docs/contents/getting_started/index.md
  pdfjs.config
Labels: 1-other

#11719 Remove the unused `wideChars` property on `Font` instances
  src/core/evaluator.js
  src/core/fonts.js
Labels: 4-font-conversion

#11720 Update the `eslint-plugin-no-unsanitized` package to the latest version
  package-lock.json
  package.json
  src/core/operator_list.js
  test/unit/jasmine-boot.js
Labels: 1-other

#11721 Don't let Travis run `npm update` during setup
  .travis.yml
Labels: 1-test

#11728 Remove unnecessary checks from the `PDFDocumentProperties` constructor
  web/pdf_document_properties.js
Labels: 1-viewer

#11724 Only build the necessary `web/` files during the `gulp default_preferences` task
  gulpfile.js
Labels: 1-other

#11723 Remove variable shadowing from the JavaScript files in the `src/display/` folder
  src/display/api.js
  src/display/canvas.js
  src/display/content_disposition.js
  src/display/node_stream.js
  src/display/pattern_helper.js
  src/display/text_layer.js
Labels: 1-core

#11725 Re-factor `PDFViewerApplication.load` such that `{PDFViewer, PDFThumbnailViewer}.setDocument` happens slightly earlier
  web/app.js
  web/view_history.js
Labels: 1-viewer

#11734 Remove old API methods which were previously converted to throwing (PR 11219 follow-up)
  src/display/api.js
Labels: 1-core

#11736 Add `passive: false` to the `wheel` event listener used in `PDFPresentationMode` (issue 11735, PR 10765 follow-up)
  web/pdf_presentation_mode.js
Labels: 1-viewer

#11742 Remove variable shadowing from the JavaScript files in the `test/unit/` folder
  test/unit/api_spec.js
  test/unit/cff_parser_spec.js
  test/unit/parser_spec.js
Labels: 1-test

#11738 Remove variable shadowing from the JavaScript files in the `src/core/` folder
  src/core/chunked_stream.js
  src/core/document.js
  src/core/evaluator.js
  src/core/font_renderer.js
  src/core/fonts.js
  src/core/function.js
  src/core/jpg.js
  src/core/jpx.js
  src/core/obj.js
  src/core/type1_parser.js
  src/core/worker.js
Labels: 1-core

#11707 Always prefer the PDF.js JPEG decoder for very large images, in order to reduce peak memory usage (issue 11694)
  src/core/jpeg_stream.js
Labels: 2-performance, 4-image-jpeg

#11744 The first glyph in CFF CIDFonts must be named 0 instead of ".notdef"
  src/core/cff_parser.js
  test/pdfs/.gitignore
  test/pdfs/issue11718_reduced.pdf
  test/test_manifest.json
  test/unit/cff_parser_spec.js
Labels: 4-font-conversion

#11646 Ensure that automatic printing still works when the viewer and/or its pages are hidden (bug 1618621, bug 1618955)
  web/base_viewer.js
  web/pdf_single_page_viewer.js
  web/pdf_viewer.js
  web/ui_utils.js
Labels: 1-viewer

#11747 Add `passive: false` when removing wheel listeners
  web/app.js
  web/pdf_presentation_mode.js
Labels: 1-viewer

#11755 Remove the unused `sizes` and `encoding` properties on `Font` instances
  src/core/fonts.js
Labels: 1-core

#11767 Replace the RTL images with CSS transforms of the standard images (issue 11766)
  web/images/findbarButton-next-rtl.png
  web/images/findbarButton-next-rtl@2x.png
  web/images/findbarButton-previous-rtl.png
  web/images/findbarButton-previous-rtl@2x.png
  web/images/toolbarButton-pageDown-rtl.png
  web/images/toolbarButton-pageDown-rtl@2x.png
  web/images/toolbarButton-pageUp-rtl.png
  web/images/toolbarButton-pageUp-rtl@2x.png
  web/images/toolbarButton-secondaryToolbarToggle-rtl.png
  web/images/toolbarButton-secondaryToolbarToggle-rtl@2x.png
  web/images/toolbarButton-sidebarToggle-rtl.png
  web/images/toolbarButton-sidebarToggle-rtl@2x.png
  web/images/toolbarButton-viewOutline-rtl.png
  web/images/toolbarButton-viewOutline-rtl@2x.png
  web/images/treeitem-collapsed-rtl.png
  web/images/treeitem-collapsed-rtl@2x.png
  web/viewer.css
Labels: 1-viewer

#11655 [api-minor] Remove the `getGlobalEventBus` viewer functionality, and the `eventBusDispatchToDOM` option/preference (PR 11631 follow-up)
  extensions/chromium/preferences_schema.json
  test/unit/ui_utils_spec.js
  web/app.js
  web/app_options.js
  web/base_viewer.js
  web/firefoxcom.js
  web/pdf_find_bar.js
  web/pdf_find_controller.js
  web/pdf_history.js
  web/pdf_link_service.js
  web/pdf_page_view.js
  web/text_layer_builder.js
  web/ui_utils.js
Labels: 1-core
