Repository mozilla/pdf.js, pull requests merged in 2020-05, with the labels that each got.

#11864 Remove the `create-react-app` example (issue 11729)
  examples/create-react-app/.env
  examples/create-react-app/.gitignore
  examples/create-react-app/README.md
  examples/create-react-app/package.json
  examples/create-react-app/public/favicon.ico
  examples/create-react-app/public/helloworld.pdf
  examples/create-react-app/public/index.html
  examples/create-react-app/public/manifest.json
  examples/create-react-app/public/robots.txt
  examples/create-react-app/src/app.tsx
  examples/create-react-app/src/index.css
  examples/create-react-app/src/index.tsx
  examples/create-react-app/src/pdf.tsx
  examples/create-react-app/src/react-app-env.d.ts
  examples/create-react-app/tsconfig.json
Labels: 1-other

#11868 Update packages and translations
  l10n/br/viewer.properties
  l10n/hr/viewer.properties
  l10n/hy-AM/viewer.properties
  l10n/meh/viewer.properties
  l10n/ro/viewer.properties
  l10n/ur/viewer.properties
  package-lock.json
  package.json
Labels: 1-other

#11869 Various smaller clean-up in `gulpfile.js`
  gulpfile.js
Labels: 1-other

#11863 Add more categories of unsupported features.
  src/core/evaluator.js
  src/core/worker.js
  src/display/font_loader.js
  src/shared/util.js
Labels: 1-core

#11872 Gracefully handle annotation parsing errors in `Page.getOperatorList` (issue 11871)
  src/core/document.js
  src/core/operator_list.js
  test/pdfs/issue11871.pdf.link
  test/test_manifest.json
Labels: 1-core

#11879 Enable the ESLint `grouped-accessor-pairs` rule
  .eslintrc
  examples/mobile-viewer/viewer.js
  web/app.js
Labels: 1-other, 1-viewer

#11880 Attempt to respect the "zoom" hash parameter, even when the "nameddest" parameter is present (issue 11875)
  web/pdf_history.js
  web/pdf_link_service.js
Labels: 1-viewer

#11889 Handle errors individually for each annotation in the `_parsedAnnotations` getter
  src/core/document.js
Labels: 1-core

#11890 Update ESLint to version 7
  .eslintrc
  package-lock.json
  package.json
Labels: 1-other

#11892 Add a `minified-es5` gulp task (issue 11858)
  gulpfile.js
Labels: 1-other

#11905 Reduce the usage of `require` statements in code-paths not protected by pre-processor and/or run-time checks
  src/core/worker.js
  src/display/api_compatibility.js
  src/shared/compatibility.js
  web/viewer_compatibility.js
Labels: 1-core

#11910 Update packages and translations
  l10n/hye/viewer.properties
  l10n/uk/viewer.properties
  package-lock.json
  package.json
Labels: 1-other

#11911 Remove the SystemJS dependency from the `web/preferences.js` file
  web/preferences.js
Labels: 1-viewer

#11917 [Firefox] Allow PDF attachments to, once again, be opened directly in the browser (bug 1632644)
  web/app.js
  web/pdf_attachment_viewer.js
  web/pdf_document_properties.js
  web/ui_utils.js
Labels: 1-viewer

#11914 Convert the `src/pdf.js` and `src/pdf.worker.js` files to use standard `import`/`export` statements
  src/display/api.js
  src/display/fetch_stream.js
  src/display/node_stream.js
  src/pdf.js
  src/pdf.worker.js
Labels: 1-core

#11919 Reduce usage of SystemJS, in the development viewer, even further
  .eslintrc
  external/builder/preprocessor2.js
  package-lock.json
  package.json
  src/core/.eslintrc
  src/display/api.js
  src/pdf.js
  web/app.js
  web/viewer.html
  web/viewer.js
Labels: 1-core, 1-viewer

#11924 Avoid hanging the worker-thread for CMap data with ridiculously large ranges (issue 11922)
  src/core/cmap.js
  test/pdfs/.gitignore
  test/pdfs/issue11922_reduced.pdf
  test/test_manifest.json
Labels: 1-core, 2-performance

#11926 Allow `GlobalImageCache.clear` to, optionally, only remove the actual data (PR 11912 follow-up)
  src/core/document.js
  src/core/image_utils.js
  src/core/obj.js
  src/core/pdf_manager.js
  src/core/worker.js
Labels: 1-core, 2-performance

#11601 [api-minor] Decode all JPEG images with the built-in PDF.js decoder in `src/core/jpg.js`
  examples/node/pdf2svg.js
  gulpfile.js
  src/core/evaluator.js
  src/core/image.js
  src/core/image_utils.js
  src/core/jpeg_stream.js
  src/core/worker.js
  src/display/api.js
  src/display/api_compatibility.js
  src/display/canvas.js
  src/display/display_utils.js
  src/display/svg.js
  src/pdf.js
  src/shared/util.js
  test/driver.js
  test/test_manifest.json
  test/unit/display_svg_spec.js
  web/app.js
  web/app_options.js
  web/download_manager.js
  web/pdf_attachment_viewer.js
  web/pdf_print_service.js
  web/viewer_compatibility.js
Labels: 1-core

#11927 Implement fill opacity for shading patterns in the SVG back-end
  src/display/svg.js
Labels: 4-svg

#11939 Update Acorn to version 7
  package-lock.json
  package.json
Labels: 1-dependencies

#11940 Add comments to the `export` list in the `src/pdf.js` file (PR 11914 follow-up)
  src/pdf.js
Labels: 1-core

#11930 Improve the *local* image caching in `PartialEvaluator.getOperatorList`
  src/core/evaluator.js
  src/core/image_utils.js
Labels: 1-core, 2-performance

#11943 Remove unused code from the `external/builder/builder.js` file
  external/builder/builder.js
Labels: 1-other

#11945 Update packages and translations
  l10n/oc/viewer.properties
  l10n/uk/viewer.properties
  l10n/zh-TW/viewer.properties
  package-lock.json
  package.json
Labels: 1-other
