Repository mozilla/pdf.js, pull requests merged in 2021-03, with the labels that each got.

#13039 Change the background to ensure that the sidebar is visible/readable when the viewer is narrow (issue 13036)
  web/viewer.css
Labels: 1-ux, 1-viewer

#13050 Collect all l10n fallback strings, used in the viewer, in one helper function (PR 12981 follow-up)
  web/annotation_layer_builder.js
  web/app.js
  web/base_viewer.js
  web/firefoxcom.js
  web/genericl10n.js
  web/l10n_utils.js
  web/password_prompt.js
  web/pdf_document_properties.js
  web/pdf_find_bar.js
  web/pdf_layer_viewer.js
  web/pdf_page_view.js
  web/pdf_print_service.js
  web/pdf_sidebar.js
  web/pdf_thumbnail_view.js
  web/pdf_viewer.component.js
  web/toolbar.js
  web/ui_utils.js
Labels: 1-viewer

#13053 Enable scripting by default in the development viewer; remove the standalone `acroforms` example
  examples/acroforms/README.md
  examples/acroforms/acroforms.html
  examples/acroforms/acroforms.js
  web/app_options.js
Labels: 1-other, 1-viewer

#13042 [api-minor] Move the viewer scripting initialization/handling into a new `PDFScriptingManager` class
  examples/components/simpleviewer.js
  examples/components/singlepageviewer.js
  web/app.js
  web/base_viewer.js
  web/generic_scripting.js
  web/pdf_page_view.js
  web/pdf_scripting_manager.js
  web/pdf_viewer.component.js
  web/ui_utils.js
Labels: 1-viewer

#13054 Move handling of the PageOpen/PageClose events into the `PDFScriptingManager` (PR 13042 follow-up)
  web/base_viewer.js
  web/pdf_scripting_manager.js
Labels: 1-viewer

#13060 Update packages and translations
  l10n/ast/viewer.properties
  l10n/hye/viewer.properties
  l10n/kk/viewer.properties
  package-lock.json
  package.json
Labels: 1-dependencies, 1-other

#13055 JS - reset correctly radio buttons
  src/display/annotation_layer.js
  src/scripting_api/field.js
  test/integration/scripting_spec.js
Labels: 1-core

#13062 Remove the `test/features` folder, since it's very out of date (issue 11954)
  gulpfile.js
  test/features/index.html
  test/features/tests.js
  test/features/worker-stub.js
Labels: 1-other

#13063 Use more optional chaining in the web/-folder (PR 12961 follow-up)
  web/pdf_document_properties.js
  web/pdf_find_controller.js
  web/pdf_sidebar_resizer.js
Labels: 1-viewer

#13015 JS - Avoid a popup to ask for updating Acrobat.
  src/scripting_api/initialization.js
Labels: 1-core

#13074 Re-factor the `PDFScriptingManager._destroyScripting` method (PR 13042 follow-up)
  web/base_viewer.js
  web/pdf_scripting_manager.js
Labels: 1-viewer

#13081 Replace the `objectFromEntries` helper function with an `objectFromMap` one instead, and simplify the data lookup in the AnnotationStorage.getValue method
  src/display/annotation_storage.js
  src/display/metadata.js
  src/display/optional_content_config.js
  src/shared/util.js
Labels: 1-core

#13085 Ensure that *all* errors are handled in `rasterizeTextLayer`/`rasterizeAnnotationLayer`
  test/driver.js
Labels: 1-test

#13090 Enable the ESLint `no-var` rule in `gulpfile.js`
  gulpfile.js
  test/unit/display_utils_spec.js
  test/unit/fetch_stream_spec.js
  test/unit/parser_spec.js
Labels: 1-other

#13079 Ensure that `getDocument` handles Node.js `Buffer`s more gracefully (issue 13075)
  src/display/api.js
Labels: 1-core, 4-node-specific

#13087 Enable the ESLint `no-var` rule in the `examples/` folder
  examples/.eslintrc
  examples/browserify/gulpfile.js
  examples/browserify/main.js
  examples/components/pageviewer.js
  examples/components/simpleviewer.js
  examples/components/singlepageviewer.js
  examples/image_decoders/jpeg_viewer.js
  examples/mobile-viewer/viewer.js
  examples/node/domstubs.js
  examples/node/getinfo.js
  examples/node/pdf2png/pdf2png.js
  examples/node/pdf2svg.js
  examples/svgviewer/viewer.js
  examples/text-only/pdf2svg.js
  examples/webpack/main.js
  examples/webpack/webpack.config.js
Labels: 1-other

#13084 Enable the ESLint `no-var` rule in a few font-parsing files, and convert `src/core/type1_parser.js` to use "standard" classes
  src/core/cff_parser.js
  src/core/font_renderer.js
  src/core/type1_parser.js
Labels: 1-core

#13092 Enable the ESLint `no-var` rule in the `importL10n/` folder
  external/importL10n/.eslintrc
  external/importL10n/locales.js
Labels: 1-other

#13091 Enable the ESLint `no-var` rule globally
  .eslintignore
  .eslintrc
  examples/.eslintrc
  extensions/chromium/.eslintrc
  extensions/firefox/.eslintrc
  external/.eslintrc
  gulpfile.js
  src/.eslintrc
  src/core/.eslintrc
  src/shared/.eslintrc
  systemjs.config.js
  test/add_test.js
  test/chromium/test-telemetry.js
  test/downloadutils.js
  test/driver.js
  test/font/.eslintrc
  test/stats/statcmp.js
  test/test.js
  test/testutils.js
  test/unit/.eslintrc
  test/webserver.js
  web/.eslintrc
Labels: 1-other

#13093 Enable the ESLint `no-var` rule in the `external/builder/` folder
  external/builder/.eslintrc
  external/builder/builder.js
  external/builder/preprocessor2.js
  external/builder/test-fixtures.js
  external/builder/test-fixtures_esprima.js
Labels: 1-other

#13097 Enable the ESLint `no-var` rule in `test/add_test.js`
  test/add_test.js
Labels: 1-test

#13096 Enable the ESLint `no-var` rule in the `test/stats/` folder
  test/stats/statcmp.js
Labels: 1-test

#13095 Enable linting of the `external/cmapscompress/` folder
  .eslintignore
  external/cmapscompress/.eslintrc
  external/cmapscompress/compress.js
  external/cmapscompress/optimize.js
  external/cmapscompress/parse.js
Labels: 1-other

#13098 Enable the ESLint `no-var` rule in the `external/` folder
  .eslintignore
  external/.eslintrc
  external/builder/.eslintrc
  external/cmapscompress/.eslintrc
  external/dist/webpack.js
  external/importL10n/.eslintrc
  external/systemjs/plugin-babel-cached.js
  external/webpack/pdfjsdev-loader.js
Labels: 1-other

#13094 Enable the `no-var` linting rule for `src/core/{operator_list, pattern}.js`
  src/core/operator_list.js
  src/core/pattern.js
Labels: 1-core

#13101 print: Remove invalid @supports condition.
  web/pdf_print_service.js
Labels: 4-printing

#13100 print: Ensure print containers have the right size and don't create overflow.
  web/firefox_print_service.js
  web/pdf_print_service.js
  web/viewer.css
Labels: 4-printing

#13102 print: RFC: Center when printing a PDF with smaller size than the output page.
  web/viewer.css
Labels: 4-printing

#13106 Support `LineAnnotation`s with empty /Rect-entries (issue 6564)
  src/core/annotation.js
  test/pdfs/.gitignore
  test/pdfs/annotation-line-without-appearance-empty-Rect.pdf
  test/test_manifest.json
Labels: 4-annotations

#13069 [api-minor]XFA - Add a layer to display XFA forms
  src/core/document.js
  src/core/pdf_manager.js
  src/core/worker.js
  src/core/xfa/factory.js
  src/core/xfa/html_utils.js
  src/core/xfa/template.js
  src/core/xfa/utils.js
  src/core/xfa/xfa_object.js
  src/display/api.js
  src/display/xfa_layer.js
  src/pdf.js
  test/unit/xfa_parser_spec.js
  web/app.js
  web/app_options.js
  web/base_viewer.js
  web/interfaces.js
  web/pdf_page_view.js
  web/pdf_viewer.css
  web/xfa_layer_builder.css
  web/xfa_layer_builder.js
Labels: 1-core, 1-viewer

#13120 Rotate landscape pages, during printing, by default in the viewer (`enablePrintAutoRotate = true`)
  extensions/chromium/preferences_schema.json
  web/app_options.js
  web/base_viewer.js
Labels: 4-printing

#13116 Enable scripting by default in the viewer (PR 13053 follow-up)
  extensions/chromium/preferences_schema.json
  web/app_options.js
Labels: 1-viewer

#13113 Ignore some *scripting* events which don't make sense in PresentationMode
  web/pdf_scripting_manager.js
Labels: 1-viewer

#13105 Improve memory usage around the `BasePdfManager.docBaseUrl` parameter (PR 7689 follow-up)
  src/core/pdf_manager.js
  src/display/api.js
  src/display/display_utils.js
  src/pdf.js
  test/unit/display_utils_spec.js
  test/unit/ui_utils_spec.js
  web/app.js
  web/generic_scripting.js
  web/pdf_document_properties.js
  web/ui_utils.js
Labels: 1-core

#13118 Add landmark region and aria-label for each page.
  l10n/en-US/viewer.properties
  web/l10n_utils.js
  web/pdf_page_view.js
Labels: 1-viewer

#13124 Tweak the pre-processor condition, for Node.js environments, in the `animationStarted` helper (issue 13057)
  web/ui_utils.js
Labels: 1-viewer

#13117 Re-factor the default preferences generation to support build targets (PR 10548)
  extensions/firefox/content/PdfJsDefaultPreferences.jsm
  gulpfile.js
  web/app_options.js
  web/preferences.js
Labels: 1-other

#13126 Update packages and translations
  l10n/ast/viewer.properties
  l10n/ca/viewer.properties
  l10n/sk/viewer.properties
  l10n/sv-SE/viewer.properties
  l10n/th/viewer.properties
  package-lock.json
  package.json
  test/unit/annotation_spec.js
  test/unit/api_spec.js
Labels: 1-dependencies, 1-other

#13125 Don't provide the `enableXfa` parameter to the `BaseViewer` constructor, and avoid the fallback bar with `enableXfa = true` set (PR 13069 follow-up)
  web/app.js
Labels: 1-viewer

#13135 Fix typo in pdf_history.js
  web/pdf_history.js
Labels: 1-viewer

#13128 Re-factor how the `BasePreferences.prefs`-property is initialized; remove some *indirect* loops
  web/preferences.js
Labels: 1-viewer

#13082 XFA - Convert some template properties into CSS ones
  src/core/xfa/html_utils.js
  src/core/xfa/template.js
  src/core/xfa/utils.js
  src/core/xfa/xfa_object.js
  src/display/xfa_layer.js
  test/unit/jasmine-boot.js
  test/unit/xfa_parser_spec.js
  test/unit/xfa_tohtml_spec.js
  web/xfa_layer_builder.css
  web/xfa_layer_builder.js
Labels: 1-core, 1-viewer

#13140 [GrabToPan] Remove more IE-specific code, and remove *unconditional* browser sniffing
  web/grab_to_pan.js
Labels: 1-viewer

#13145 print: Improve rendering of oversized pages.
  web/firefox_print_service.js
  web/pdf_print_service.js
  web/viewer.css
Labels: 4-printing

#13144 [GrabToPan] Use `Element.matches()` rather than prefixed `...matchesSelector` versions
  web/grab_to_pan.js
Labels: 1-viewer

#13138 [PDFHistory] Correctly simulate an internal destination in the `pushPage`-method (PR 12493 follow-up)
  web/pdf_history.js
Labels: 1-viewer

#13056 Dispatch a "Doc/WillClose" event, when scripting is enabled, when closing the document
  web/pdf_scripting_manager.js
Labels: 1-viewer

#13154 Update quickjs to revision b5e62895c619d4ffc75c9d822c8d85f1ece77e5b
  external/quickjs/quickjs-eval.js
Labels: 1-core

#13155 Move rotation normalization from `PDFViewerApplication` and into `BaseViewer`
  src/display/display_utils.js
  web/app.js
  web/base_viewer.js
Labels: 1-viewer

#13152 Skip extra objects in object stream in using offsets
  src/core/obj.js
  src/core/stream.js
  test/pdfs/issue13130.pdf.link
  test/test_manifest.json
Labels: 1-core

#13133 JS - Handle correctly hierarchy of fields
  src/core/annotation.js
  src/core/core_utils.js
  src/core/document.js
  src/display/annotation_layer.js
  src/scripting_api/common.js
  src/scripting_api/event.js
  src/scripting_api/field.js
  src/scripting_api/initialization.js
  src/scripting_api/util.js
  test/integration/scripting_spec.js
  test/pdfs/issue13132.pdf.link
  test/test_manifest.json
  web/pdf_scripting_manager.js
Labels: 1-core

#13158 Remove the `URL` polyfill
  src/shared/compatibility.js
Labels: 1-core

#13166 [api-minor] Support proper `URL`-objects, in addition to URL-strings, in `getDocument`
  src/display/api.js
  test/unit/api_spec.js
Labels: 1-core

#13165 [api-minor] Stop exposing the *raw* `defaultAppearance`-string on Annotation-instances
  src/core/annotation.js
Labels: 1-core, 4-annotations

#13168 Use post table when Encoding has only Differences
  src/core/fonts.js
  test/pdfs/.gitignore
  test/pdfs/issue13107_reduced.pdf
  test/test_manifest.json
Labels: 4-font-conversion

#12908 Slightly rescale lineWidth to workaround chrome rendering issue
  src/display/canvas.js
Labels: 1-core, 4-chrome-specific
