Repository mozilla/pdf.js, pull requests merged in 2021-01, with the labels that each got.

#12801 Modernize the `FirefoxCom.request` method
  web/firefoxcom.js
Labels: 1-viewer

#12802 Add a new `FirefoxCom.requestAsync` method, to simplify the code in `web/firefoxcom.js`
  web/firefoxcom.js
Labels: 1-viewer

#12805 Remove unnecessary toolbarButton icon-flipping in RTL mode (PR 11077 follow-up)
  web/viewer.css
Labels: 1-viewer

#12804 Remove the `DownloadManager.onerror` functionality, since its only usage is unlikely to be helpful
  web/app.js
  web/download_manager.js
  web/firefoxcom.js
Labels: 1-viewer

#12807 Remove unnecessary `dir`-dependent CSS rules, and add a missing CSS variable (PR 11077 follow-up)
  web/viewer.css
Labels: 1-viewer

#12774 JS -- Add tests for print/save actions
  src/core/document.js
  test/integration/scripting_spec.js
  test/pdfs/.gitignore
  test/pdfs/doc_actions.pdf
  test/pdfs/docactions.pdf
  test/test.js
  test/test_manifest.json
  test/unit/api_spec.js
Labels: 1-core, 1-test

#12808 Disable a test using pending function
  test/integration/scripting_spec.js
Labels: 1-test

#12825 An option is missing for last versions of worker-loader to use pdf.js with webpack
  examples/webpack/README.md
  external/dist/webpack.js
Labels: 1-other

#12815 Update webpack example
  examples/webpack/package.json
  gulpfile.js
Labels: 1-other

#12816 JS -- Plug PageOpen and PageClose actions
  src/display/api.js
  src/scripting_api/doc.js
  src/scripting_api/event.js
  test/integration/scripting_spec.js
  web/app.js
Labels: 1-core, 1-viewer

#12292 Fix encoding issues when printing/saving a form with non-ascii characters
  src/core/annotation.js
  src/core/cmap.js
  src/core/fonts.js
  src/shared/util.js
  test/unit/annotation_spec.js
  test/unit/util_spec.js
Labels: 4-annotations, 4-form-acroform, 4-printing

#12822 Improve the `PDFViewerApplication._contentLength` handling in the viewer, related mostly to scripting
  web/app.js
Labels: 1-viewer

#12824 Improve the handling of errors, in `PartialEvaluator.loadFont`, occuring in `PartialEvaluator.preEvaluateFont` (issue 12823)
  src/core/evaluator.js
  test/pdfs/.gitignore
  test/pdfs/issue12823.pdf
  test/test_manifest.json
Labels: 1-core

#12820 Don't dispatch "pageclose" events if a "pageopen" wasn't dispatched for the page (PR 12747 follow-up)
  web/base_viewer.js
Labels: 1-viewer

#12834 Try to fix TypeScript definitions for the es5-build in pdfjs-dist (issue 12872)
  external/dist/es5/build/pdf.d.ts
Labels: 1-other

#12837 Remove unncessary `CanvasFactory`/`CMapReaderFactory`/`FileReaderFactory` duplication in unit-tests
  src/display/api.js
  test/unit/annotation_spec.js
  test/unit/api_spec.js
  test/unit/cmap_spec.js
  test/unit/custom_spec.js
  test/unit/test_utils.js
Labels: 1-test

#12394 In a text widget, Font resources can be in the appearance
  src/core/annotation.js
  test/test_manifest.json
Labels: 4-annotations, 4-form-acroform

#12777 Add support for finding/highlighting the outlineItem, corresponding to the currently visible page, in the sidebar (issue 7557, bug 1253820, bug 1499050)
  l10n/en-US/viewer.properties
  l10n/nl/viewer.properties
  l10n/sv-SE/viewer.properties
  web/app.js
  web/base_tree_viewer.js
  web/images/toolbarButton-currentOutlineItem.svg
  web/pdf_layer_viewer.js
  web/pdf_outline_viewer.js
  web/pdf_sidebar.js
  web/ui_utils.js
  web/viewer.css
  web/viewer.html
  web/viewer.js
Labels: 1-viewer

#12840 Use ESLint to ensure that `export`s are sorted alphabetically
  .eslintrc
  package-lock.json
  package.json
  src/core/annotation.js
  src/core/cff_parser.js
  src/core/charsets.js
  src/core/cmap.js
  src/core/core_utils.js
  src/core/crypto.js
  src/core/encodings.js
  src/core/fonts.js
  src/core/function.js
  src/core/glyphlist.js
  src/core/image_utils.js
  src/core/obj.js
  src/core/pattern.js
  src/core/primitives.js
  src/core/standard_fonts.js
  src/core/stream.js
  src/core/unicode.js
  src/core/worker.js
  src/core/writer.js
  src/display/api.js
  src/display/display_utils.js
  src/interfaces.js
  src/pdf.image_decoders.js
  src/pdf.js
  src/shared/util.js
  test/unit/test_utils.js
  web/app.js
  web/interfaces.js
  web/pdf_history.js
  web/pdf_rendering_queue.js
  web/pdf_sidebar.js
  web/pdf_viewer.component.js
  web/text_layer_builder.js
  web/ui_utils.js
Labels: 1-other

#12844 Update packages and translations
  .eslintrc
  l10n/ka/viewer.properties
  l10n/ru/viewer.properties
  package-lock.json
  package.json
Labels: 1-dependencies

#12845 Remove unnecessary `dir`-dependent CSS rules, and simplify som findbar-button rules (PR 11077 follow-up)
  web/viewer.css
Labels: 1-viewer

#12846 Enable the Stylelint `length-zero-no-unit` rule
  .stylelintrc
  test/annotation_layer_builder_overrides.css
  web/annotation_layer_builder.css
  web/pdf_viewer.css
  web/text_layer_builder.css
  web/viewer.css
Labels: 1-viewer

#12848 Correctly align annotation content in horizontal/spead scrolling modes
  web/annotation_layer_builder.css
Labels: 1-viewer, 4-annotations

#12838 [api-minor] Change the "dc:creator" Metadata field to an Array
  src/core/writer.js
  src/display/metadata.js
  src/scripting_api/doc.js
  src/shared/xml_parser.js
  test/integration/scripting_spec.js
  test/pdfs/.gitignore
  test/pdfs/js-authors.pdf
  test/unit/metadata_spec.js
  test/unit/xml_spec.js
  web/app.js
Labels: 1-core

#12853 Fix the initialization/resetting of scripting-related events in the `BaseViewer`
  src/display/api.js
  web/app.js
  web/base_viewer.js
Labels: 1-viewer

#12855 [api-minor] Highlight search results correctly for normalized text (PR 9448)
  test/pdfs/.gitignore
  test/pdfs/fraction-highlight.pdf
  test/unit/clitests_helper.js
  test/unit/pdf_find_controller_spec.js
  web/pdf_find_controller.js
  web/text_layer_builder.js
Labels: 1-viewer

#12861 Always re-measure non-embedded ArialNarrow fonts (bug 1671312, PR 12725 follow-up)
  src/core/fonts.js
  test/pdfs/.gitignore
  test/pdfs/bug1671312_ArialNarrow.pdf
  test/test_manifest.json
Labels: 4-font-conversion

#12812 Enforce line width to be at least 1px after applied transform
  src/display/canvas.js
  test/pdfs/.gitignore
  test/pdfs/issue12295.pdf
  test/pdfs/issue12810.pdf
  test/test_manifest.json
Labels: 1-core

#12864 Enforce linewidth to 1px when at least one of scale factor is lower than 1
  src/display/canvas.js
  test/pdfs/.gitignore
  test/pdfs/issue6127.pdf
  test/test_manifest.json
Labels: 1-core

#12874 Put less emphasis on "ES5"/"ES6" in the README and other documentation
  README.md
  docs/contents/getting_started/index.md
  external/dist/README.md
Labels: 1-other

#12875 Replace some ternary operators with optional chaining, and nullish coalescing, in the `src/display/`-folder
  src/display/api.js
  src/display/canvas.js
  src/display/fetch_stream.js
  src/display/metadata.js
  src/display/node_stream.js
  src/display/svg.js
  src/display/transport_stream.js
Labels: 1-core

#12871 Only display a notification on the `sidebarToggle`-button, and not the individual view-buttons (PR 7959 follow-up)
  web/pdf_sidebar.js
Labels: 1-viewer

#12850 JS -- Add few missing constants in global scope
  src/scripting_api/aform.js
  src/scripting_api/constants.js
  src/scripting_api/initialization.js
  test/unit/scripting_spec.js
Labels: 1-core

#12878 Remove redundant compatibility checks, for modern `generic` builds, in `src/core/worker.js`
  src/core/worker.js
Labels: 1-core

#12869 Fix zoom issue with too thin lines
  src/display/canvas.js
Labels: 1-core

#12831 Add a parser to get font data from the default appearance
  src/core/annotation.js
  src/core/default_appearance.js
  src/core/evaluator.js
  test/unit/annotation_spec.js
  test/unit/clitests.json
  test/unit/default_appearance_spec.js
  test/unit/jasmine-boot.js
Labels: 1-core

#12836 JS -- update radio/checkbox values even if there are no actions
  src/core/annotation.js
  src/display/annotation_layer.js
  test/integration/scripting_spec.js
  test/pdfs/js-buttons.pdf
  test/test_manifest.json
Labels: 1-core

#12888 Enable the Stylelint `shorthand-property-no-redundant-values` rule
  .stylelintrc
  web/pdf_viewer.css
  web/viewer.css
Labels: 1-viewer

#12890 Enable ESLint rules that no longer need to be disabled on a directory/file-basis
  examples/.eslintrc
  examples/acroforms/acroforms.js
  examples/browserify/main.js
  examples/components/pageviewer.js
  examples/components/simpleviewer.js
  examples/components/singlepageviewer.js
  examples/image_decoders/jpeg_viewer.js
  examples/mobile-viewer/viewer.js
  examples/node/domstubs.js
  examples/node/pdf2png/pdf2png.js
  examples/node/pdf2svg.js
  examples/svgviewer/viewer.js
  examples/text-only/pdf2svg.js
  examples/webpack/main.js
  extensions/.eslintrc
  external/.eslintrc
  external/builder/preprocessor2.js
  external/builder/test-fixtures_esprima.js
  external/systemjs/plugin-babel-cached.js
  gulpfile.js
  test/.eslintrc
  test/chromium/test-telemetry.js
  test/downloadutils.js
  test/test.js
  test/webserver.js
Labels: 1-other

#12886 Use `_defaultAppearanceData` directly in `WidgetAnnotation._getSaveFieldResources` (PR 12831 follow-up)
  src/core/annotation.js
Labels: 1-core

#12887 Keep logical assignment operators in `MOZCENTRAL`/`TESTING`-builds
  gulpfile.js
Labels: 1-other

#12885 Simplify the `PDFFunctionFactory._localFunctionCache` initialization (PR 12034 follow-up); Fix the `gStateObj` lookup in `TranslatedFont._removeType3ColorOperators` (PR 12718 follow-up)
  src/core/evaluator.js
  src/core/function.js
Labels: 1-core

#12891 Ensure that `parseDefaultAppearance` won't attempt to access a not yet defined variable (PR 12831 follow-up)
  src/core/default_appearance.js
  test/unit/default_appearance_spec.js
Labels: 1-core

#12828 [api-minor] Set font size and color for text widget annotations
  src/core/annotation.js
  src/display/annotation_layer.js
  test/pdfs/.gitignore
  test/pdfs/pr12828.pdf
  test/test_manifest.json
Labels: 4-annotations

#12893 Enable, a basic version of, the ESLint `no-use-before-define` rule
  .eslintrc
Labels: 1-other

#12870 Add previous/next-page functionality that takes scroll/spread-modes into account (issue 11946)
  test/unit/ui_utils_spec.js
  web/app.js
  web/base_viewer.js
  web/pdf_link_service.js
  web/pdf_presentation_mode.js
  web/pdf_single_page_viewer.js
  web/pdf_viewer.js
  web/ui_utils.js
Labels: 1-viewer

#12899 Update the ESLint `env` to use "es2021"
  .eslintrc
  src/scripting_api/app.js
Labels: 1-other

#12898 Update packages and translations
  l10n/cy/viewer.properties
  l10n/de/viewer.properties
  l10n/dsb/viewer.properties
  l10n/el/viewer.properties
  l10n/en-GB/viewer.properties
  l10n/es-AR/viewer.properties
  l10n/gl/viewer.properties
  l10n/he/viewer.properties
  l10n/hsb/viewer.properties
  l10n/hu/viewer.properties
  l10n/hye/viewer.properties
  l10n/ia/viewer.properties
  l10n/it/viewer.properties
  l10n/ko/viewer.properties
  l10n/nb-NO/viewer.properties
  l10n/pt-BR/viewer.properties
  l10n/sv-SE/viewer.properties
  l10n/uk/viewer.properties
  l10n/zh-CN/viewer.properties
  l10n/zh-TW/viewer.properties
  package-lock.json
  package.json
Labels: 1-dependencies

#12897 JS - Fix mouse event names
  src/display/annotation_layer.js
  src/scripting_api/event.js
  src/shared/util.js
  test/unit/annotation_spec.js
Labels: 1-core

#12901 Bump versions in `pdfjs.config`
  pdfjs.config
Labels: 1-other

#12826 JS -- add support for choice widget
  src/core/annotation.js
  src/display/annotation_layer.js
  src/scripting_api/field.js
  test/integration/scripting_spec.js
  test/pdfs/.gitignore
  test/pdfs/listbox_actions.pdf
Labels: 1-core

#12916 Include `pdf.sandbox.js` when building the pdfjs-dist files
  gulpfile.js
Labels: 1-other

#12911 Fix text layer regression tests in using the correct line-height property
  test/text_layer_test.css
Labels: 1-test

#12910 Add back dir property in spans in text layer
  src/display/text_layer.js
  test/pdfs/issue12909.pdf.link
  test/test_manifest.json
Labels: 4-text-selection

#12903 Improve global image caching for small images (PR 11912 follow-up, issue 12098)
  src/core/evaluator.js
  src/core/image_utils.js
Labels: 1-core, 2-performance

#12924 Fix font data clone error when pdfBug is enabled.
  src/core/evaluator.js
Labels: 4-font-conversion

#12922 Ignore globally cached images in `PartialEvaluator.getTextContent` (PR 11930 follow-up)
  src/core/evaluator.js
  src/core/image_utils.js
Labels: 1-core

#12920 fix(acroforms): pdf path in acroforms example
  examples/acroforms/acroforms.js
Labels: 1-other

#12931 Stop showing the fallback bar for "errorFontLoadNative" errors (PR 10539 follow-up)
  src/display/font_loader.js
  web/app.js
Labels: 1-core, 1-viewer

#12932 Stop including `-ms` prefixed CSS rules in GENERIC builds
  gulpfile.js
Labels: 1-other

#12933 Stop polyfilling CSS variables in GENERIC builds
  gulpfile.js
  package-lock.json
  package.json
Labels: 1-other

#12935 Remove prefixed fullscreen properties/methods from the MOZCENTRAL builds
  web/app.js
  web/pdf_presentation_mode.js
Labels: 1-viewer
