Repository mozilla/pdf.js, pull requests merged in 2022-06, with the labels that each got.

#14980 Handle CSS-comments better in the preprocess-function (PR 14963 follow-up)
  external/builder/builder.js
  external/builder/fixtures/css-comment-expected.css
  external/builder/fixtures/css-comment.css
Labels: other

#14976 [editor] Add a FreeText editor (#14970)
  extensions/chromium/preferences_schema.json
  l10n/en-US/viewer.properties
  src/display/annotation_storage.js
  src/display/editor/annotation_editor_layer.js
  src/display/editor/editor.js
  src/display/editor/freetext.js
  src/display/editor/tools.js
  src/pdf.js
  src/shared/util.js
  test/integration-boot.js
  test/integration/freetext_editor_spec.js
  test/test.js
  web/annotation_editor_layer_builder.css
  web/annotation_editor_layer_builder.js
  web/app.js
  web/app_options.js
  web/base_viewer.js
  web/default_factory.js
  web/images/toolbarButton-editorFreeText.svg
  web/images/toolbarButton-editorNone.svg
  web/interfaces.js
  web/l10n_utils.js
  web/pdf_page_view.js
  web/pdf_viewer.css
  web/toolbar.js
  web/viewer.css
  web/viewer.html
  web/viewer.js
Labels: editor

#14988 Remove mention of `gulp singlefile`-command from `examples/node/getinfo.js`
  examples/node/getinfo.js
Labels: other

#14985 [editor] A couple of small FreeText-related fixes (PR 14976 follow-up)
  l10n/en-US/viewer.properties
  src/display/annotation_storage.js
  src/shared/util.js
  web/base_viewer.js
  web/l10n_utils.js
  web/toolbar.js
  web/viewer.html
  web/viewer.js
Labels: editor

#14984 Bundle the `<dialog>` polyfill-CSS in the GENERIC `legacy/`-viewer (PR 14710 follow-up)
  gulpfile.js
  web/overlay_manager.js
Labels: viewer

#14991 [editor] Disable the editor-buttons in XFA documents
  web/app.js
  web/app_options.js
  web/base_viewer.js
  web/toolbar.js
  web/viewer.css
  web/viewer.js
Labels: editor

#14992 Lookup image-data correctly in `paintImageMaskXObjectGroup` (issue 14990)
  src/display/canvas.js
  test/pdfs/issue14990.pdf.link
  test/test_manifest.json
Labels: image-conversion

#14993 [editor] Update the `AnnotationStorage.hash`-getter to support editing
  src/display/annotation_storage.js
  src/display/editor/freetext.js
Labels: editor

#14994 Conditionally bundle `gulp image_decoders`-specific code in `src/core/jbig2.js` (PR 9729 follow-up)
  src/core/jbig2.js
Labels: image-jbig2

#15000 Outline fields which are required (bug 1724918)
  src/core/annotation.js
  src/core/xfa/template.js
  src/display/annotation_layer.js
  test/pdfs/.gitignore
  test/pdfs/bug1724918.pdf
  test/test_manifest.json
  web/annotation_layer_builder.css
  web/xfa_layer_builder.css
Labels: annotations

#15001 Set "presentation" role for page canvases (issue 14437)
  web/pdf_page_view.js
Labels: accessibility

#15003 Change the name of the generated pdf.sandbox.external for mozilla-central
  gulpfile.js
Labels: other, firefox-specific

#14978 [editor] Add support for saving a newly added FreeText
  src/core/annotation.js
  src/core/document.js
  src/core/worker.js
  src/core/writer.js
  src/core/xref.js
  src/display/editor/annotation_editor_layer.js
  src/display/editor/editor.js
  src/display/editor/freetext.js
  src/shared/util.js
  test/unit/annotation_spec.js
  test/unit/test_utils.js
  web/annotation_editor_layer_builder.css
Labels: editor

#15008 Polyfill `Array.prototype.at` with core-js (PR 14976 follow-up)
  src/shared/compatibility.js
Labels: core

#15011 Fix a couple of old review comments
  src/core/annotation.js
  src/shared/scripting_utils.js
  web/debugger.js
Labels: core, viewer

#15013 Render PopupAnnotations even if they have missing or empty /Rect-entries (issue 15012, PR 14439 follow-up)
  .github/workflows/ci.yml
  src/display/annotation_layer.js
  test/pdfs/.gitignore
  test/pdfs/issue15012.pdf
  test/test_manifest.json
Labels: annotations

#14989 [editor] Add an Ink editor
  l10n/en-US/viewer.properties
  src/display/editor/annotation_editor_layer.js
  src/display/editor/fit_curve/fit_curve.js
  src/display/editor/freetext.js
  src/display/editor/ink.js
  src/shared/util.js
  web/annotation_editor_layer_builder.css
  web/app.js
  web/app_options.js
  web/images/toolbarButton-editorInk.svg
  web/toolbar.js
  web/viewer.css
  web/viewer.html
  web/viewer.js
Labels: editor

#15006 [editor] Add support for saving newly added Ink
  src/core/annotation.js
  src/core/default_appearance.js
  test/unit/annotation_spec.js
Labels: editor

#15015 Extend TextLayerRenderParameters.container type to include HTMLElement.
  src/display/text_layer.js
Labels: other

#15020 Add an empty entry in combo list when nothing is selected (bug 1773680)
  src/display/annotation_layer.js
Labels: form-acroform

#15014 Enable the `unicorn/prefer-at` ESLint plugin rule (PR 15008 follow-up)
  .eslintrc
  external/.eslintrc
  src/core/catalog.js
  src/core/crypto.js
  src/core/document.js
  src/core/evaluator.js
  src/core/font_renderer.js
  src/core/fonts.js
  src/core/function.js
  src/core/operator_list.js
  src/core/pattern.js
  src/core/type1_parser.js
  src/core/writer.js
  src/core/xfa/builder.js
  src/core/xfa/data.js
  src/core/xfa/formcalc_parser.js
  src/core/xfa/html_utils.js
  src/core/xfa/som.js
  src/core/xfa/template.js
  src/core/xfa/text.js
  src/core/xfa/xhtml.js
  src/core/xfa_fonts.js
  src/core/xml_parser.js
  src/display/editor/fit_curve/fit_curve.js
  src/display/svg.js
  src/display/text_layer.js
  src/display/xfa_layer.js
  src/shared/compatibility.js
  test/resources/reftest-analyzer.js
  test/test.js
  test/unit/ui_utils_spec.js
  web/ui_utils.js
Labels: other

#15018 Expose `TextLayerRenderTask` in the TypeScript definitions (issue 15016, PR 14013 follow-up)
  src/display/text_layer.js
  src/pdf.js
  test/unit/clitests.json
  test/unit/jasmine-boot.js
  test/unit/text_layer_spec.js
Labels: core

#15022 Tweak the `editorNone` icon to circumvent the "duplicated files"-check
  web/images/toolbarButton-editorNone.svg
Labels: editor

#15026 [api-minor] Stop using the `beginAnnotations`/`endAnnotations` operators (PR 14998 follow-up)
  src/core/document.js
  src/display/canvas.js
  src/shared/util.js
  test/unit/api_spec.js
Labels: core

#15027 Remove superfluous trailing arguments from `parseFloat`-calls (PR 14978 follow-up)
  src/display/editor/freetext.js
Labels: core

#15029 Enable the `unicorn/prefer-dom-node-append` ESLint plugin rule
  .eslintrc
  examples/node/domstubs.js
  examples/text-only/pdf2svg.js
  extensions/chromium/contentscript.js
  extensions/chromium/options/options.js
  src/display/annotation_layer.js
  src/display/display_utils.js
  src/display/editor/annotation_editor_layer.js
  src/display/editor/freetext.js
  src/display/editor/ink.js
  src/display/font_loader.js
  src/display/svg.js
  src/display/text_layer.js
  src/display/xfa_layer.js
  test/driver.js
  test/resources/reftest-analyzer.js
  test/unit/custom_spec.js
  test/unit/display_svg_spec.js
  web/annotation_editor_layer_builder.js
  web/annotation_layer_builder.js
  web/base_tree_viewer.js
  web/base_viewer.js
  web/debugger.js
  web/download_manager.js
  web/firefox_print_service.js
  web/firefoxcom.js
  web/grab_to_pan.js
  web/pdf_attachment_viewer.js
  web/pdf_layer_viewer.js
  web/pdf_outline_viewer.js
  web/pdf_page_view.js
  web/pdf_print_service.js
  web/pdf_thumbnail_view.js
  web/print_utils.js
  web/struct_tree_layer_builder.js
  web/text_highlighter.js
  web/text_layer_builder.js
  web/viewer.js
  web/xfa_layer_builder.js
Labels: other

#15023 Enable the `unicorn/prefer-array-flat` and `unicorn/prefer-array-flat-map` ESLint plugin rules
  .eslintrc
  src/core/xfa/som.js
Labels: other

#15028 [api-minor] Update the minimum supported browsers/environments
  gulpfile.js
  src/shared/compatibility.js
Labels: other

#15030 Update packages and translations
  l10n/ia/viewer.properties
  l10n/pt-BR/viewer.properties
  l10n/szl/viewer.properties
  l10n/tg/viewer.properties
  package-lock.json
  package.json
Labels: dependencies

#15031 Enable the `unicorn/prefer-modern-dom-apis` ESLint plugin rule
  .eslintrc
  extensions/chromium/contentscript.js
  src/display/annotation_layer.js
  web/pdf_page_view.js
Labels: other

#15046 Add basic support for non-embedded ArialUnicodeMS fonts (issue 15044)
  src/core/standard_fonts.js
  test/pdfs/issue15044.pdf.link
  test/test_manifest.json
Labels: font-conversion

#15050 [Editor] - Add the ability to directly draw after selecting ink tool
  src/display/editor/annotation_editor_layer.js
  src/display/editor/editor.js
  src/display/editor/freetext.js
  src/display/editor/ink.js
  src/display/editor/tools.js
  web/annotation_editor_layer_builder.css
Labels: editor

#15054 [JS] Hide field borders and buttons (#15053)
  src/display/annotation_layer.js
  test/integration/scripting_spec.js
  test/pdfs/.gitignore
  test/pdfs/issue15053.pdf
Labels: form-js

#15035 Use modern DOM methods a bit more (PR 15031 follow-up)
  external/webL10n/l10n.js
  src/display/annotation_layer.js
  web/base_tree_viewer.js
  web/overlay_manager.js
  web/text_highlighter.js
Labels: other

#15048 Only define the `renderer`-option in the GENERIC viewer
  web/app.js
  web/app_options.js
  web/pdf_page_view.js
Labels: viewer

#15052 Simplify setting the `defaultUrl`-option in the CHROME viewer (PR 12470 follow-up)
  web/app_options.js
  web/viewer.js
Labels: viewer

#15057 Replace element `id`s with custom attributes for Widget-annotations (issue 15056)
  src/display/annotation_layer.js
  test/integration/annotation_spec.js
  test/integration/scripting_spec.js
  test/integration/test_utils.js
  web/pdf_scripting_manager.js
Labels: form-js

#15036 [api-minor] Get rid of CSS transform on each annotation in the annotation layer
  src/core/annotation.js
  src/core/xfa/template.js
  src/core/xfa/xhtml.js
  src/display/annotation_layer.js
  src/display/base_factory.js
  src/display/canvas.js
  src/display/editor/annotation_editor_layer.js
  src/display/editor/freetext.js
  test/annotation_layer_builder_overrides.css
  test/driver.js
  test/integration/freetext_editor_spec.js
  web/annotation_editor_layer_builder.css
  web/annotation_layer_builder.css
  web/annotation_layer_builder.js
  web/base_viewer.js
  web/pdf_page_view.js
  web/pdf_viewer.css
Labels: form-acroform

#15058 [api-minor] Remove the "baseviewerinit" event since it's unused (PR 14324 follow-up)
  web/base_viewer.js
Labels: viewer

#15059 Reduce unnecessary usage of `Array.prototype.concat()`
  external/builder/preprocessor2.js
  src/core/cff_parser.js
  src/core/jbig2.js
  src/display/text_layer.js
Labels: core

#15065 Popup trigger area must filled its parent (fix #15063)
  src/display/annotation_layer.js
  web/annotation_layer_builder.css
Labels: annotations

#15064 Avoid having overflowing sections (#15036 follow-up)
  src/display/annotation_layer.js
  web/annotation_layer_builder.css
Labels: viewer, regression, annotations

#15062 Simplify the `newRefs` computation in the "SaveDocument"-handler in the worker-thread
  src/core/document.js
  src/core/worker.js
Labels: core

#15071 Add an outline around popup trigger areas in ref-tests
  test/annotation_layer_builder_overrides.css
Labels: test

#15074 Only activate ink editor if none is selected
  src/display/editor/annotation_editor_layer.js
  src/display/editor/tools.js
Labels: editor

#15069 Ensure that the annotationLayer has the correct dimensions (PR 15036 follow-up)
  src/display/annotation_layer.js
Labels: annotations

#15047 [Editor] Add support for printing newly added Ink annotations
  src/core/annotation.js
  src/core/core_utils.js
  src/core/document.js
  src/core/worker.js
  test/test_manifest.json
  test/unit/annotation_spec.js
Labels: editor

#15089 Correctly order added annotations when saving or printing
  src/core/annotation.js
  src/core/document.js
  test/test_manifest.json
Labels: editor

#15043 [api-minor] Introduce a `PrintAnnotationStorage` with *frozen* serializable data
  src/display/annotation_storage.js
  src/display/api.js
  test/unit/api_spec.js
  web/app.js
  web/firefox_print_service.js
  web/pdf_print_service.js
Labels: core, viewer

#15093 [JS] Update siblings when a field is updated after a calculation (#15092)
  src/scripting_api/doc.js
  src/scripting_api/event.js
  test/integration/scripting_spec.js
  test/pdfs/.gitignore
  test/pdfs/issue15092.pdf
Labels: form-js

#15095 Add (basic) support for Optional Content in Annotations
  src/core/annotation.js
  test/test_manifest.json
Labels: annotations

#15101 Use the *built* `components/pdf_viewer.css` file in the reference tests
  test/driver.js
Labels: test

#15099 Remove element `id`s from the layersView in the sidebar
  web/pdf_layer_viewer.js
  web/viewer.css
Labels: viewer

#15100 chore: Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: other

#15103 chore: Set permissions for GitHub actions
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
Labels: other

#15088 Support rotating editor layer
  src/core/annotation.js
  src/display/annotation_layer.js
  src/display/editor/annotation_editor_layer.js
  src/display/editor/editor.js
  src/display/editor/freetext.js
  src/display/editor/ink.js
  test/integration/scripting_spec.js
  test/test_manifest.json
  test/unit/annotation_spec.js
  web/annotation_editor_layer_builder.css
  web/annotation_editor_layer_builder.js
  web/annotation_layer_builder.css
  web/pdf_viewer.css
Labels: editor

#15104 Update translations and dependencies to the most recent versions
  l10n/be/viewer.properties
  l10n/bn/viewer.properties
  l10n/cy/viewer.properties
  l10n/dsb/viewer.properties
  l10n/el/viewer.properties
  l10n/en-GB/viewer.properties
  l10n/es-AR/viewer.properties
  l10n/es-CL/viewer.properties
  l10n/es-MX/viewer.properties
  l10n/et/viewer.properties
  l10n/fr/viewer.properties
  l10n/gn/viewer.properties
  l10n/he/viewer.properties
  l10n/hsb/viewer.properties
  l10n/hu/viewer.properties
  l10n/ia/viewer.properties
  l10n/id/viewer.properties
  l10n/is/viewer.properties
  l10n/it/viewer.properties
  l10n/ka/viewer.properties
  l10n/ko/viewer.properties
  l10n/nl/viewer.properties
  l10n/nn-NO/viewer.properties
  l10n/oc/viewer.properties
  l10n/pt-BR/viewer.properties
  l10n/pt-PT/viewer.properties
  l10n/rm/viewer.properties
  l10n/ru/viewer.properties
  l10n/sv-SE/viewer.properties
  l10n/tg/viewer.properties
  l10n/tr/viewer.properties
  l10n/uk/viewer.properties
  l10n/vi/viewer.properties
  l10n/zh-CN/viewer.properties
  l10n/zh-TW/viewer.properties
  package-lock.json
  package.json
Labels: other, dependencies

#15105 Always flush the current item with MarkedContent stuff when getting text (#15094)
  src/core/evaluator.js
  test/unit/api_spec.js
Labels: text-selection

#15039 [editor] Add some UI elements in order to set font size & color, and ink thickness & color
  l10n/en-US/viewer.properties
  src/core/annotation.js
  src/display/canvas.js
  src/display/display_utils.js
  src/display/editor/annotation_editor_layer.js
  src/display/editor/editor.js
  src/display/editor/freetext.js
  src/display/editor/ink.js
  src/display/editor/tools.js
  src/pdf.js
  src/shared/util.js
  test/integration/freetext_editor_spec.js
  test/unit/annotation_spec.js
  web/annotation_editor_params.js
  web/app.js
  web/base_viewer.js
  web/toolbar.js
  web/viewer.css
  web/viewer.html
  web/viewer.js
Labels: editor

#15113 [editor] Introduce a proper `annotationEditorMode` option/preference (PR 15075 follow-up)
  extensions/chromium/preferences_schema.json
  l10n/en-US/viewer.properties
  src/shared/util.js
  web/app.js
  web/app_options.js
  web/base_viewer.js
  web/l10n_utils.js
  web/viewer.html
Labels: viewer, editor

#15116 Fix the `annotationEditorMode`-compatibility for older browsers (PR 15113 follow-up)
  web/app_options.js
  web/base_viewer.js
Labels: viewer

#15117 [Editor] Set the freetext editor dimensions when the changing the font size
  src/display/editor/freetext.js
Labels: editor

#15115 [Editor] Handle correctly colors when saving a document in HCM
  src/display/display_utils.js
  src/display/editor/editor.js
  src/display/editor/freetext.js
  src/display/editor/ink.js
  src/display/editor/tools.js
  web/annotation_editor_layer_builder.css
Labels: editor
