Repository mozilla/pdf.js, pull requests merged in 2022-05, with the labels that each got.

#14860 Update dependencies and translations
  gulpfile.js
  l10n/pa-IN/viewer.properties
  l10n/sc/viewer.properties
  l10n/tg/viewer.properties
  package-lock.json
  package.json
Labels: other, dependencies

#14858 Use `Path2D`, if available, when rendering Type3-fonts (bug 810214)
  src/display/canvas.js
  src/display/pattern_helper.js
  src/shared/is_node.js
Labels: performance, font-type3

#14861 Pin the `es-module-shims` dependency to version 1.4.7
  package-lock.json
  package.json
Labels: dependencies

#14863 Update quickjs to revision 2788d71e823b522b178db3b3660ce93689534e6d
  external/quickjs/quickjs-eval.js
Labels: form-js

#14865 Support encoded dest-strings in /GoTo destination dictionaries (issue 14864)
  src/core/catalog.js
  test/pdfs/issue14864.pdf.link
  test/test_manifest.json
  test/unit/api_spec.js
Labels: core

#14866 Immediately release the temporary `Uint8Array`s used during Type3-compilation
  src/display/canvas.js
Labels: font-type3

#14869 [JS] Fix few bugs present in the pdf for issue #14862
  src/core/annotation.js
  src/display/annotation_layer.js
  src/display/annotation_storage.js
  src/scripting_api/app.js
  src/scripting_api/doc.js
  src/scripting_api/event.js
  src/scripting_api/field.js
  src/scripting_api/initialization.js
  test/integration/scripting_spec.js
  test/pdfs/.gitignore
  test/pdfs/issue14705.pdf
  test/pdfs/issue14862.pdf
  test/unit/api_spec.js
  test/unit/scripting_spec.js
Labels: form-js

#14873 Replace the `AnnotationStorage.lastModified`-getter with a proper hash-method
  src/core/evaluator.js
  src/display/annotation_storage.js
  src/display/api.js
  src/shared/murmurhash3.js
  test/unit/murmurhash3_spec.js
Labels: core, printing

#14870 Only bundle the `src/display/node_utils.js` file in GENERIC-builds
  src/display/api.js
  src/display/node_utils.js
Labels: core

#14871 Re-factor the PresentationMode handling in `BaseViewer.#ensurePageViewVisible`
  web/base_viewer.js
Labels: viewer

#14874 [api-minor] Improve pdf reading in high contrast mode
  extensions/chromium/preferences_schema.json
  src/display/api.js
  src/display/canvas.js
  test/driver.js
  test/test_manifest.json
  web/app.js
  web/app_options.js
  web/base_viewer.js
  web/pdf_page_view.js
Labels: core, viewer, accessibility

#14877 Add (basic) support for Spread modes in PresentationMode (issue 14749)
  web/base_viewer.js
  web/pdf_presentation_mode.js
Labels: viewer

#14880 Introduce a `--viewer-container-height` CSS variable to simplify the code
  web/app.js
  web/base_viewer.js
  web/pdf_viewer.css
  web/secondary_toolbar.js
  web/viewer.css
  web/viewer.js
Labels: viewer

#14884 Simplify the "fileattachmentannotation"-event handling a little bit
  src/display/annotation_layer.js
  web/pdf_attachment_viewer.js
Labels: viewer, annotations

#14882 Add support for TrueType format 12 `cmap`s (issue 14881)
  src/core/fonts.js
  test/pdfs/.gitignore
  test/pdfs/issue14881.pdf
  test/test_manifest.json
Labels: font-conversion, font-truetype

#14887 Ignore `pageColors` when the background/foreground is identical (PR 14874 follow-up)
  extensions/chromium/preferences_schema.json
  src/display/canvas.js
  web/app.js
  web/app_options.js
Labels: core, viewer

#14885 Stop bundling `PDFViewerApplication.{unbindEvents, unbindWindowEvents}` in MOZCENTRAL builds
  web/app.js
Labels: viewer, firefox-specific

#14888 Try to fix dispatching of "attachmentsloaded"-events, when the document contains no "regular" attachments (PR 8788, 12163 follow-up)
  web/pdf_attachment_viewer.js
Labels: viewer

#14886 Use the regular `preprocess`-function for the CSS files as well
  external/builder/builder.js
  external/builder/fixtures/if-nested-expected.css
  external/builder/fixtures/if-nested.css
  gulpfile.js
  web/app.js
  web/secondary_toolbar.js
  web/toolbar.js
  web/viewer.css
  web/viewer.html
  web/viewer.js
Labels: viewer, other, chrome-specific

#14890 [JS] Formatted value has to be a string when neither null nor undefined
  src/core/annotation.js
  src/scripting_api/event.js
Labels: form-js

#14904 Avoid the `preprocess`-function adding consecutive blank lines
  external/builder/builder.js
Labels: other

#14899 [api-minor] Include line endings in Line/Polyline Annotation-data (issue 14896)
  src/core/annotation.js
  test/unit/annotation_spec.js
Labels: annotations

#14894 Try to remove the `mozOpaque` canvas-property (PR 6551 follow-up)
  src/display/text_layer.js
  test/driver.js
  web/pdf_page_view.js
  web/pdf_thumbnail_view.js
  web/toolbar.js
Labels: core, viewer, test

#14911 Use `TypedArray.prototype.fill()` a bit more in the code-base
  src/core/jbig2.js
Labels: image-jbig2

#14910 Ensure that setting the width of the zoom dropdown works correctly (PR 14028 follow-up)
  web/toolbar.js
Labels: viewer

#14918 [api-minor] Modernize and simplify the `ProgressBar` class
  examples/mobile-viewer/viewer.css
  examples/mobile-viewer/viewer.js
  web/ui_utils.js
  web/viewer.css
Labels: viewer

#14919 Bump versions in `pdfjs.config`
  pdfjs.config
Labels: other

#14920 Update packages and translations
  .eslintrc
  gulpfile.js
  l10n/fi/viewer.properties
  l10n/sc/viewer.properties
  package-lock.json
  package.json
Labels: dependencies

#14921 Adjust the heuristics for handling of incomplete path operators (issue 14917)
  src/core/evaluator.js
  test/pdfs/issue14917.pdf.link
  test/test_manifest.json
Labels: core

#14898 [api-minor] Use a CSS transform to update the progress bar instead of changing the width (bug 1768481)
  examples/mobile-viewer/viewer.css
  web/viewer.css
Labels: viewer

#14945 Allow to have float numbers when getting image information in reftest-analyzer
  test/resources/reftest-analyzer.js
Labels: test

#14929 Display background when printing or saving a text widget (issue #14928)
  src/core/annotation.js
  src/core/core_utils.js
  src/core/default_appearance.js
  src/core/writer.js
  test/pdfs/issue14928.pdf.link
  test/test_manifest.json
  test/unit/annotation_spec.js
  test/unit/default_appearance_spec.js
Labels: form-acroform

#14926 Remove the `sourceEventType` from the viewer (bug 1757771 follow-up)
  web/app.js
  web/download_manager.js
  web/firefoxcom.js
  web/interfaces.js
  web/pdf_scripting_manager.js
Labels: viewer, firefox-specific

#14948 Set 'dropEffect' based on 'effectAllowed' for drag-and-drop in the viewer (issue 14942)
  web/app.js
Labels: viewer

#14950 [JS] Format all the fields if any when the document is open (bug 1766987)
  src/scripting_api/event.js
  test/integration/scripting_spec.js
  test/pdfs/bug1766987.pdf.link
  test/test_manifest.json
Labels: form-js

#14955 Skip bogus `d1` operators in Type3-glyphs (issue 14953)
  src/core/evaluator.js
  src/display/canvas.js
  test/pdfs/.gitignore
  test/pdfs/issue14953.pdf
  test/test_manifest.json
Labels: font-type3

#14957 Introduce a viewer constant for `document.documentElement.style`
  web/base_viewer.js
  web/pdf_page_view.js
  web/pdf_sidebar_resizer.js
  web/toolbar.js
  web/ui_utils.js
Labels: viewer

#14959 Support custom `pageColors` in the thumbnails (PR 14874)
  web/app.js
  web/base_viewer.js
  web/pdf_thumbnail_view.js
  web/pdf_thumbnail_viewer.js
Labels: viewer

#14965 Support Hangul syllables when searching some text (bug 1771477)
  test/pdfs/.gitignore
  test/pdfs/bug1771477.pdf
  test/unit/pdf_find_controller_spec.js
  web/pdf_find_controller.js
Labels: text-selection

#14936 Set the text fields font size based on their height
  src/core/annotation.js
  src/display/annotation_layer.js
  src/shared/util.js
  test/driver.js
  test/pdfs/issue14301.pdf.link
  test/test_manifest.json
  web/annotation_layer_builder.css
Labels: form-acroform

#14966 Use globalThis for webpack's output.globalObject instead of this
  gulpfile.js
Labels: other

#14963 Handle CSS-comments correctly in the `preprocess`-function (PR 14886 follow-up)
  external/builder/builder.js
  external/builder/fixtures/css-comment-expected.css
  external/builder/fixtures/css-comment.css
Labels: other

#14964 Ensure that the `contentDispositionFilename` is always respected, when setting the document title (PR 13014 follow-up)
  web/app.js
  web/pdf_document_properties.js
Labels: viewer

#14962 Improve the `PDFSidebar` implementation
  web/app.js
  web/pdf_sidebar.js
Labels: viewer

#14967 Update packages and translations
  l10n/it/viewer.properties
  l10n/ka/viewer.properties
  package-lock.json
  package.json
Labels: dependencies

#14583 [Annotations] Show buttons even if they've no actions
  src/display/annotation_layer.js
  test/pdfs/bug1737260.pdf.link
  test/test_manifest.json
Labels: annotations

#14968 A small memory-usage improvement for PDF documents opened from TypedArray-data
  src/display/api.js
Labels: core
