Repository mozilla/pdf.js, pull requests merged in 2023-04, with the labels that each got.

#16234 [api-minor] Remove the `disableCombineTextItems` option
  src/core/annotation.js
  src/core/document.js
  src/core/evaluator.js
  src/core/worker.js
  src/display/api.js
  test/unit/api_spec.js
Labels: text-selection

#16238 Update the Node.js compatibility-check in the worker-thread
  src/core/worker.js
  src/shared/compatibility.js
Labels: core

#16232 [Firefox] Stop using a `baseUrl` in the `PDFLinkService` (PR 16153 follow-up)
  web/app.js
  web/pdf_link_service.js
Labels: viewer, firefox-specific

#16159 Write some {Object} in api.js more precise
  src/display/api.js
Labels: other

#16243 Use object-spread when dispatching events in the toolbars
  web/secondary_toolbar.js
  web/toolbar.js
Labels: viewer

#16242 [api-minor] Remove the `canvasFactory` option from `PDFPageProxy.render` (PR 16100 follow-up)
  src/display/api.js
Labels: core

#16244 Bump versions in `pdfjs.config`
  pdfjs.config
Labels: other

#16248 Reduce duplication when dispatching the "switchannotationeditorparams" event
  web/annotation_editor_params.js
Labels: viewer, editor

#16226 [api-minor] Remove SVG-rendering from the viewer (PR 15173 follow-up)
  web/app.js
  web/app_options.js
  web/interfaces.js
  web/pdf_page_view.js
  web/pdf_thumbnail_view.js
  web/pdf_viewer.js
  web/ui_utils.js
Labels: viewer

#16241 [Firefox] Add CSS at-page size when printing from FirefoxPrintService (bug 1820651)
  web/firefox_print_service.js
  web/pdf_print_service.js
  web/pdf_viewer.js
Labels: viewer, printing

#16256 Tweak the `--scale-factor` CSS-variable warning threshold (issue 16254)
  src/display/text_layer.js
Labels: text-selection

#16260 [GeckoView] Add a basic toolbar with a download button for GV (bug 1823164)
  gulpfile.js
  web/app.js
  web/toolbar-geckoview.js
  web/viewer-geckoview.css
  web/viewer-geckoview.html
  web/viewer-geckoview.js
Labels: viewer, firefox-specific

#16261 Tweak the `loadingBar` CSS to better support RTL locales
  web/viewer.css
Labels: viewer

#16262 Tweak the `pageNumber` CSS to better support RTL locales
  web/viewer.css
Labels: viewer

#16246 Force-install when using `gulp dist-install` (issue 15435)
  gulpfile.js
Labels: other

#16249 [api-minor] Update the minimum supported Google Chrome version
  gulpfile.js
Labels: other

#16265 [Firefox] Use `float: inline-start/inline-end` directly in MOZCENTRAL builds (PR 15968 follow-up)
  .stylelintrc
  gulpfile.js
  web/viewer.css
Labels: viewer, firefox-specific

#16225 Thin whitespaces must have their own span
  src/core/evaluator.js
  test/pdfs/.gitignore
  test/pdfs/issue16224.pdf
  test/test_manifest.json
Labels: text-selection

#16268 Attempt to also cache images at the "page"-level (issue 16263)
  src/core/evaluator.js
  src/core/image_utils.js
  test/pdfs/.gitignore
  test/pdfs/issue16263.pdf
  test/test_manifest.json
Labels: core, performance

#16275 Fix search of numbers inside fractions
  test/unit/pdf_find_controller_spec.js
  web/pdf_find_controller.js
Labels: text-selection

#16279 Skip transfers, in `LoopbackPort.postMessage`, for PDF.js `legacy`-builds (issue 16255)
  src/display/api.js
Labels: core, node-specific

#16284 [GeckoView] Show the download button by default and add a pref to disable it (bug 1827963)
  web/app.js
  web/app_options.js
  web/toolbar-geckoview.js
  web/viewer-geckoview.css
Labels: viewer, firefox-specific

#16292 Avoid when it's possible to use Array.concat when compiling a CFF font
  src/core/cff_parser.js
Labels: performance, font-conversion

#16291 Limit the `Path2D`-checks in the worker-thread to Node.js (PR 16238 follow-up, issue 16289)
  src/core/worker.js
Labels: core, regression

#16294 Remove `CFFCompiler.compileGlobalSubrIndex`, and simplify `CFFCompiler.compileTypedArray`
  src/core/cff_parser.js
Labels: font-conversion

#16281 Reduce some duplication when toggling buttons in the viewer toolbars
  web/pdf_sidebar.js
  web/secondary_toolbar.js
  web/toolbar.js
  web/ui_utils.js
Labels: viewer

#16288 Slightly modernize print-related code
  web/firefox_print_service.js
  web/pdf_print_service.js
Labels: viewer, printing

#16286 Add the possibility to copy all the pdf text whatever the rendered pages are (bug 1788035)
  test/integration-boot.js
  test/integration/copy_paste_spec.js
  test/integration/test_utils.js
  web/app.js
  web/pdf_viewer.css
  web/pdf_viewer.js
  web/viewer-geckoview.html
  web/viewer-geckoview.js
  web/viewer.html
  web/viewer.js
Labels: text-selection

#16297 Remove null chars, i.e. `\u0000`, when getting all text (PR 16286 follow-up)
  web/pdf_viewer.js
Labels: text-selection

#16298 Create the "hiddenCopyElement" in the `PDFViewer` constructor (PR 16286 follow-up)
  web/app.js
  web/pdf_viewer.js
  web/viewer-geckoview.html
  web/viewer-geckoview.js
  web/viewer.html
  web/viewer.js
Labels: viewer

#16296 Update packages and translations
  gulpfile.js
  l10n/it/viewer.properties
  l10n/ja/viewer.properties
  l10n/ko/viewer.properties
  l10n/zh-CN/viewer.properties
  package-lock.json
  package.json
Labels: dependencies

#16299 Update TypeScript to version `5`
  package-lock.json
  package.json
Labels: dependencies

#16247 [api-minor] Add support, in `PDFFindController`, for mixing phrase/word searches (issue 7442)
  test/unit/pdf_find_controller_spec.js
  web/app.js
  web/firefoxcom.js
  web/pdf_find_bar.js
  web/pdf_find_controller.js
  web/pdf_link_service.js
Labels: viewer, text-selection

#16295 Use CustomEvent when dispatching the "webviewerloaded" event
  web/viewer.js
Labels: viewer

#16301 [Editor] Take into account the initial rotation (issue #16278)
  src/display/editor/editor.js
  test/integration/ink_editor_spec.js
  test/pdfs/.gitignore
  test/pdfs/issue16278.pdf
Labels: editor

#16200 [api-minor] Don't normalize the text used in the text layer.
  src/core/bidi.js
  src/core/document.js
  src/core/evaluator.js
  src/core/fonts.js
  src/core/unicode.js
  src/core/worker.js
  src/display/api.js
  src/pdf.js
  src/shared/util.js
  test/driver.js
  test/integration/copy_paste_spec.js
  test/pdfs/.gitignore
  test/pdfs/copy_paste_ligatures.pdf
  test/unit/api_spec.js
  test/unit/pdf_find_controller_spec.js
  test/unit/unicode_spec.js
  web/pdf_find_controller.js
  web/pdf_find_utils.js
  web/pdf_page_view.js
  web/pdf_viewer.js
  web/text_highlighter.js
  web/text_layer_builder.js
Labels: core, viewer, text-selection

#16308 [GeckoView] Don't change style for the download button when focused/hovered
  web/viewer-geckoview.css
Labels: viewer, firefox-specific

#16311 Compatible with ResizeObserver borderBoxSize in legacy safari
  web/pdf_viewer.js
Labels: viewer

#16320 Disable the "copy all text" feature when `enablePermissions` is set (PR 16286 follow-up)
  web/pdf_viewer.js
Labels: text-selection

#16310 Introduce some `:is` usage in the xfaLayer CSS
  web/xfa_layer_builder.css
Labels: form-xfa

#16313 Introduce some `:is` usage in the textLayer CSS
  test/text_layer_test.css
  web/text_layer_builder.css
Labels: text-selection

#16314 Introduce some `:is` usage in the PDFViewer CSS
  web/pdf_viewer.css
Labels: viewer

#16315 Introduce some `:is` usage in the annotationLayer CSS
  test/annotation_layer_builder_overrides.css
  web/annotation_layer_builder.css
Labels: annotations

#16323 Introduce some `:is` usage in the viewer CSS
  web/viewer-geckoview.css
  web/viewer.css
Labels: viewer

#16327 Update `eslint-plugin-mozilla` to avoid having to force-install packages (issue 15429)
  gulpfile.js
  package-lock.json
  package.json
Labels: dependencies

#16305 Remove the `PRODUCTION` build-target
  gulpfile.js
  src/core/annotation.js
  src/core/chunked_stream.js
  src/core/colorspace.js
  src/core/core_utils.js
  src/core/document.js
  src/core/evaluator.js
  src/core/fonts.js
  src/core/image.js
  src/core/image_utils.js
  src/core/jpg.js
  src/core/parser.js
  src/core/primitives.js
  src/core/worker.js
  src/core/xref.js
  src/display/annotation_layer.js
  src/display/api.js
  src/display/editor/freetext.js
  src/display/font_loader.js
  src/display/network_utils.js
  src/display/svg.js
  src/pdf.sandbox.js
  src/shared/message_handler.js
  src/shared/util.js
  web/app.js
  web/app_options.js
  web/pdf_page_view.js
  web/pdf_viewer.js
  web/preferences.js
  web/viewer-geckoview.js
  web/viewer.html
Labels: other

#16326 Don't include Chrome-specific CSS rules in MOZCENTRAL builds
  web/text_layer_builder.css
Labels: viewer, firefox-specific

#16331 Remove unnecessary closures in the CMap code
  src/core/binary_cmap.js
  src/core/cmap.js
Labels: core

#16332 Remove the remaining unnecessary closures in the `src/core/primitives.js` file
  src/core/primitives.js
Labels: core

#16334 Remove the `PDF20` closure, in the `src/core/crypto.js` file
  src/core/crypto.js
Labels: core

#16335 Don't force-install packages in the CI job anymore
  .github/workflows/ci.yml
Labels: dependencies

#16338 Update translations and packages
  gulpfile.js
  l10n/lo/viewer.properties
  l10n/nn-NO/viewer.properties
  package-lock.json
  package.json
Labels: dependencies

#16336 Don't use the deprecated `CustomEvent.initCustomEvent` method anymore
  web/event_utils.js
  web/firefoxcom.js
  web/pdf_print_service.js
Labels: viewer

#16333 Allow text-selection, but not copying, when `enablePermissions` is set (PR 16320 follow-up)
  web/pdf_page_view.js
  web/pdf_viewer.css
  web/pdf_viewer.js
  web/text_layer_builder.js
  web/ui_utils.js
Labels: viewer, text-selection

#16347 Prevent incomplete copy-all behaviour while text-extraction is running (PR 16286 follow-up)
  web/pdf_viewer.js
Labels: viewer

#16357 Remove the unused `getXhr`-option in the `NetworkManager` constructor
  src/display/network.js
Labels: core

#16354 Avoid some repeated `stringToBytes`-calls in the `src/core/crypto.js` file
  src/core/crypto.js
Labels: core

#16350 [api-minor] Stop including the "lib"-build in the `pdfjs-dist` repository
  external/dist/lib/README.md
  gulpfile.js
Labels: other

#16361 Declare the `linkService` and `l10n` properties as optional in the `PDFViewerOptions` documentation
  web/pdf_viewer.js
Labels: other

#16344 Fix two intermittents issues in integration tests
  test/integration/scripting_spec.js
Labels: test

#16364 Introduce a GitHub Actions workflow for publishing the website
  .github/workflows/publish_website.yml
  gulpfile.js
Labels: other

#16362 Update type documentations for #16307, #16359
  web/pdf_find_controller.js
  web/pdf_page_view.js
  web/ui_utils.js
Labels: other

#16371 Include the entire `git` history in the work-flows (issue 16366)
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/publish_website.yml
Labels: other

#16370 Limit the `publish_website.yml` work-flow to only the `master` branch (issue 16369)
  .github/workflows/publish_website.yml
Labels: other
