Repository mozilla/pdf.js, pull requests merged in 2023-10, with the labels that each got.

#17052 Use a standard `export` statement in the `web/pdfjs.js` file
  test/unit/pdf_spec.js
  web/pdfjs.js
Labels: viewer

#17053 Add alt-text svg images to the dist (issue #17044)
  gulpfile.mjs
Labels: viewer, editor

#17032 [Editor] Don't show the alt-text button when the alt-text dialog is visible
  src/display/editor/editor.js
  test/integration/stamp_editor_spec.js
  web/alt_text_manager.js
Labels: editor

#17058 [Editor] Use the alt text to descibe the canvas used to display the image
  src/display/editor/editor.js
  src/display/editor/stamp.js
  test/integration/stamp_editor_spec.js
Labels: editor

#17059 Remove timeouts from the copy_paste integration test
  test/integration/copy_paste_spec.js
  test/integration/test_utils.js
Labels: test

#16699 [api-major] Remove the SVG back-end (PR 15173 follow-up)
  examples/node/domstubs.js
  examples/node/pdf2svg.js
  gulpfile.mjs
  src/display/api.js
  src/display/stubs.js
  src/display/svg.js
  src/pdf.js
  test/unit/clitests.json
  test/unit/display_svg_spec.js
  test/unit/jasmine-boot.js
  test/unit/pdf_spec.js
  test/unit/unit_test.html
  tsconfig.json
  web/pdfjs.js
  web/viewer-geckoview.html
  web/viewer.html
Labels: core

#17066 Ensure that readonly TextWidget-annotations are rendered when forms are disabled (issue 17064)
  src/display/annotation_layer.js
  test/pdfs/.gitignore
  test/pdfs/issue17064_readonly.pdf
  test/test_manifest.json
Labels: annotations

#17063 Bump library version to `4.0`
  pdfjs.config
Labels: other

#17060 Add support for "GoToE" actions with destinations (issue 17056)
  src/core/catalog.js
  src/display/annotation_layer.js
  test/pdfs/.gitignore
  test/pdfs/issue17056.pdf
  test/unit/api_spec.js
  web/download_manager.js
  web/firefoxcom.js
Labels: core, viewer

#17062 [Editor] Support resizing editors with the keyboard (bug 1854340)
  l10n/en-US/viewer.properties
  src/display/editor/editor.js
  src/display/editor/tools.js
  test/integration/stamp_editor_spec.js
  web/l10n_utils.js
Labels: editor

#17070 Update the noHTML flag to take into account the hasOwnCanvas one (fixes #17069)
  src/core/annotation.js
  test/pdfs/.gitignore
  test/pdfs/issue17069.pdf
  test/test_manifest.json
Labels: annotations

#17076 Enable some Stylelint color-related rules to slightly reduce file sizes
  .stylelintrc
  examples/mobile-viewer/viewer.css
  test/annotation_layer_builder_overrides.css
  test/text_layer_test.css
  test/xfa_layer_builder_overrides.css
  web/annotation_editor_layer_builder.css
  web/annotation_layer_builder.css
  web/debugger.css
  web/pdf_viewer.css
  web/text_layer_builder.css
  web/viewer-geckoview.css
  web/viewer.css
  web/xfa_layer_builder.css
Labels: viewer, other, test

#16761 [Editor] Add the possibility to create a new editor in using the keyboard (bug 1853424)
  src/display/editor/editor.js
  src/display/editor/tools.js
  test/integration/freetext_editor_spec.js
  web/pdf_viewer.js
  web/toolbar.js
Labels: editor

#17077 Remove unnecessary alpha-value from CSS `rgb` colors
  test/annotation_layer_builder_overrides.css
  test/xfa_layer_builder_overrides.css
  web/annotation_layer_builder.css
  web/debugger.css
  web/pdf_viewer.css
  web/text_layer_builder.css
  web/viewer-geckoview.css
  web/viewer.css
  web/xfa_layer_builder.css
Labels: viewer, test

#17055 [api-major] Output JavaScript modules in the builds (issue 10317)
  external/dist/webpack.js
  gulpfile.mjs
  src/display/api.js
  src/display/display_utils.js
  src/display/node_stream.js
  src/display/node_utils.js
  src/pdf.js
  src/pdf.worker.entry.js
  test/driver.js
  test/test_slave.html
  test/unit/api_spec.js
  test/unit/jasmine-boot.js
  test/unit/pdf_spec.js
  test/unit/scripting_spec.js
  web/app.js
  web/app_options.js
  web/generic_scripting.js
  web/pdfjs.js
  web/viewer-geckoview.html
  web/viewer-snippet-chrome-extension.html
  web/viewer-snippet-firefox-extension.html
  web/viewer-snippet-minified.html
  web/viewer-snippet.html
  web/viewer.html
Labels: core, viewer, other, test

#17080 Output `pdf.scripting.js` as a JavaScript module (PR 17055 follow-up)
  gulpfile.mjs
  src/pdf.scripting.js
Labels: other

#17086 [api-minor] Stop polyfilling `structuredClone` in legacy builds
  gulpfile.mjs
  src/display/annotation_storage.js
  src/display/api.js
Labels: core

#17090 Activate the selector check for the `autoprint` integration test as soon as possible
  test/integration/scripting_spec.js
Labels: test

#17094 Rename `web/debugger.js` since it's actually a JavaScript module (PR 17055 follow-up)
  gulpfile.mjs
  web/debugger.mjs
  web/viewer.js
Labels: viewer

#17095 Fix the protocol timeout configuration for Puppeteer
  test/test.mjs
Labels: test

#17105 Update the "Interactive examples" links (PR 17055 follow-up)
  docs/contents/examples/index.md
Labels: other

#17106 Don't store page-level data, in the API, after cleanup has run (bug 1854145)
  src/display/api.js
Labels: core, performance

#17112 Convert the `integration` test-files to JavaScript modules
  test/integration-boot.mjs
  test/integration/accessibility_spec.mjs
  test/integration/annotation_spec.mjs
  test/integration/copy_paste_spec.mjs
  test/integration/find_spec.mjs
  test/integration/freetext_editor_spec.mjs
  test/integration/ink_editor_spec.mjs
  test/integration/scripting_spec.mjs
  test/integration/stamp_editor_spec.mjs
  test/integration/test_utils.mjs
Labels: test

#17114 Output JavaScript modules for the `LIB` build-target (PR 17055 follow-up)
  extensions/firefox/.eslintrc
  gulpfile.mjs
  package-lock.json
  package.json
  src/display/node_stream.js
  src/display/node_utils.js
  test/stats/statcmp.js
  test/unit/node_stream_spec.js
  test/unit/test_utils.js
Labels: other, test, node-specific

#17098 Tweak `PDFWorkerUtil.createCDNWrapper` to account for JavaScript modules (PR 17055 follow-up)
  src/display/api.js
Labels: core

#14743 Use native `import maps` in development mode
  package-lock.json
  package.json
  test/font/font_test.html
  test/unit/unit_test.html
  web/viewer-geckoview.html
  web/viewer.html
Labels: viewer, test

#17117 Enable the `import/no-commonjs` ESLint plugin rule
  .eslintrc
  examples/node/getinfo.js
  examples/node/pdf2png/pdf2png.js
  examples/webpack/main.js
  examples/webpack/webpack.config.js
  external/dist/webpack.js
  src/pdf.worker.entry.js
  test/chromium/test-telemetry.js
  test/stats/statcmp.js
Labels: other

#17120 Remove obsolete `src/shared/{cffStandardStrings,fonts_utils}.js` files
  gulpfile.mjs
  src/shared/cffStandardStrings.js
  src/shared/fonts_utils.js
Labels: core

#17119 Update translations/dependencies to the most recent versions and fix dependency vulnerabilities
  gulpfile.mjs
  l10n/be/viewer.properties
  l10n/cy/viewer.properties
  l10n/da/viewer.properties
  l10n/de/viewer.properties
  l10n/el/viewer.properties
  l10n/es-ES/viewer.properties
  l10n/fi/viewer.properties
  l10n/fr/viewer.properties
  l10n/fur/viewer.properties
  l10n/fy-NL/viewer.properties
  l10n/gn/viewer.properties
  l10n/it/viewer.properties
  l10n/ja/viewer.properties
  l10n/ka/viewer.properties
  l10n/nl/viewer.properties
  l10n/nn-NO/viewer.properties
  l10n/pa-IN/viewer.properties
  l10n/pt-BR/viewer.properties
  l10n/rm/viewer.properties
  l10n/ru/viewer.properties
  l10n/sk/viewer.properties
  l10n/tg/viewer.properties
  l10n/tr/viewer.properties
  l10n/vi/viewer.properties
  l10n/zh-TW/viewer.properties
  package-lock.json
  package.json
Labels: dependencies

#17122 Remove Escape key press from the `autoprint` integration test, and tweak the protocol timeout configuration for Puppeteer
  test/integration/scripting_spec.mjs
  test/test.mjs
Labels: test

#17123 Update the ESLint `globals` list (PR 17055 follow-up)
  .eslintrc
  src/display/api.js
  src/display/node_stream.js
  src/display/node_utils.js
  src/pdf.worker.entry.js
  test/unit/node_stream_spec.js
  test/unit/test_utils.js
  web/app.js
  web/generic_scripting.js
Labels: other

#17125 Fix intermittent problems on Windows in the XFA search integration test
  test/integration/find_spec.mjs
Labels: test

#17134 Reduce unnecessary type conversion in `writeStream`
  src/core/writer.js
Labels: core

#17131 Re-factor the blob-URL caching in `DownloadManager.openOrDownloadData`
  src/display/annotation_layer.js
  test/unit/api_spec.js
  web/download_manager.js
  web/firefoxcom.js
  web/interfaces.js
  web/pdf_attachment_viewer.js
  web/pdf_outline_viewer.js
Labels: core, viewer

#17138 Use a CSS-only solution to set the `dropdownToolbarButton` width (issue 17137)
  web/l10n_utils.js
  web/toolbar.js
  web/viewer.css
Labels: viewer

#17135 Only bundle `NullL10n` in GENERIC builds (bug 1859818)
  gulpfile.mjs
  test/unit/unit_test.html
  tsconfig.json
  web/annotation_editor_layer_builder.js
  web/annotation_layer_builder.js
  web/pdf_page_view.js
  web/pdf_viewer.js
  web/stubs.js
  web/viewer-geckoview.html
  web/viewer.html
Labels: viewer

#17130 Try to make the `Preferences`/`AppOptions` initialization slightly more efficient
  web/app.js
  web/app_options.js
  web/preferences.js
Labels: viewer

#17133 Use object destructuring, rather than the `merge` helper, in the gulpfile
  external/builder/builder.mjs
  gulpfile.mjs
Labels: other

#17142 [L10n] Don't try to connect the root element when it has already been done
  web/app.js
  web/toolbar.js
Labels: viewer, L10n

#17148 Fix size of maskCanvas to draw image masks correctly
  src/display/canvas.js
  test/pdfs/.gitignore
  test/pdfs/issue17147.pdf
  test/test_manifest.json
Labels: core

#17152 Use a `ResizeObserver` to update the layout of `PDFFindBar`
  web/pdf_find_bar.js
Labels: viewer

#17146 [api-minor] Re-factor `NullL10n` and remove the hard-coded l10n strings (PR 17115 follow-up)
  gulpfile.mjs
  src/display/annotation_layer.js
  src/display/stubs.js
  test/unit/unit_test.html
  tsconfig.json
  web/interfaces.js
  web/l10n_utils.js
  web/pdf_page_view.js
  web/pdf_viewer.js
  web/viewer-geckoview.html
  web/viewer.html
Labels: viewer, L10n

#17151 A couple of `PDFDocumentProperties` tweaks (PR 17115 follow-up)
  web/pdf_document_properties.js
Labels: viewer

#17141 [api-minor] Use "data-l10n-id"/"data-l10n-args", rather than manually updating DOM-elements, to trigger translation (PR 17146 follow-up)
  l10n/en-US/viewer.ftl
  src/display/annotation_layer.js
  test/driver.js
  web/annotation_layer_builder.js
  web/app.js
  web/l10n_utils.js
  web/password_prompt.js
  web/pdf_find_bar.js
  web/pdf_layer_viewer.js
  web/pdf_page_view.js
  web/pdf_print_service.js
  web/pdf_sidebar.js
  web/pdf_thumbnail_view.js
  web/pdf_thumbnail_viewer.js
  web/toolbar-geckoview.js
  web/toolbar.js
  web/viewer.html
Labels: core, viewer, test, release-blocker, L10n

#17156 Update the "aria-label" of the page when a `pageLabel` exists
  web/pdf_page_view.js
Labels: viewer

#17159 [Annotation] Use the field V entry when there is no Parent one for a radio button (bug 1860602)
  src/core/annotation.js
  test/pdfs/bug1860602.pdf.link
  test/test_manifest.json
Labels: form-acroform

#17161 Add a unit-test to ensure that `NullL10n` won't diverge from the `L10n`-class
  test/unit/pdf_viewer.component_spec.js
  web/genericl10n.js
  web/l10n.js
  web/pdf_find_bar.js
Labels: viewer, test, L10n

#17171 Don't take into account the INVISIBLE flag for well-known annotations
  src/core/annotation.js
  test/pdfs/issue17169.pdf.link
  test/test_manifest.json
  test/unit/annotation_spec.js
Labels: annotations

#17173 Fix error that's breaking the `ConstL10n` class (PR 17161 follow-up)
  web/l10n_utils.js
Labels: viewer, regression, release-blocker

#17165 Slightly improve the performance of removeNullCharacters
  web/ui_utils.js
Labels: viewer

#17006 Remove the `enableStampEditor` preference
  extensions/chromium/preferences_schema.json
  web/app.js
  web/app_options.js
  web/viewer.html
Labels: viewer, editor

#17176 Pause translation when appending the outline/attachment/layer trees to the sidebar
  web/app.js
  web/base_tree_viewer.js
  web/interfaces.js
  web/l10n.js
  web/l10n_utils.js
  web/pdf_layer_viewer.js
Labels: viewer, L10n

#17166 Improve performance of optional content parsing
  src/core/catalog.js
Labels: core

#17177 Pause translation when appending the xfaLayer to the page
  web/l10n_utils.js
  web/pdf_page_view.js
  web/xfa_layer_builder.js
Labels: viewer, form-xfa, L10n

#17189 Fix integration tests on Mac
  test/integration/copy_paste_spec.mjs
  test/integration/find_spec.mjs
  test/integration/freetext_editor_spec.mjs
  test/integration/ink_editor_spec.mjs
  test/integration/scripting_spec.mjs
  test/integration/stamp_editor_spec.mjs
  test/integration/test_utils.mjs
Labels: test

#17195 Use CSS nesting in the textLayer
  test/text_layer_test.css
  web/text_layer_builder.css
Labels: viewer, text-selection

#17196 Use CSS nesting in the annotationLayer
  test/annotation_layer_builder_overrides.css
  web/annotation_layer_builder.css
Labels: viewer, annotations

#17185 Fix `WidgetAnnotationElement._getKeyModifier` to account for Linux
  src/display/annotation_layer.js
  src/shared/util.js
Labels: annotations

#17198 Update the GitHub Actions workflow for the Fluent linter
  .github/workflows/fluent_linter.yml
Labels: test

#17081 Update the `examples/`-folder to account for outputting of JavaScript modules (PR 17055 follow-up)
  examples/components/pageviewer.html
  examples/components/pageviewer.mjs
  examples/components/simpleviewer.html
  examples/components/simpleviewer.mjs
  examples/components/singlepageviewer.html
  examples/components/singlepageviewer.mjs
  examples/image_decoders/jpeg_viewer.html
  examples/image_decoders/jpeg_viewer.js
  examples/image_decoders/jpeg_viewer.mjs
  examples/learning/helloworld.html
  examples/learning/helloworld64.html
  examples/learning/prevnext.html
  examples/mobile-viewer/viewer.css
  examples/mobile-viewer/viewer.html
  examples/mobile-viewer/viewer.mjs
  examples/node/getinfo.mjs
  examples/node/pdf2png/pdf2png.mjs
  examples/text-only/index.html
  examples/text-only/pdf2svg.mjs
  examples/webpack/README.md
  examples/webpack/main.js
  examples/webpack/main.mjs
  examples/webpack/package.json
  examples/webpack/webpack.config.js
  gulpfile.mjs
  src/pdf.worker.entry.js
Labels: other, release-blocker

#17184 Handle appending consistently in the xfaLayer regardless of rendering intent (PR 17177 follow-up)
  web/pdf_page_view.js
  web/print_utils.js
  web/xfa_layer_builder.js
Labels: printing, form-xfa

#17192 Pause translation when appending the textLayer and structTreeLayer to the page
  web/pdf_page_view.js
  web/text_layer_builder.js
Labels: viewer, release-blocker, L10n

#17199 Upgrade `setup-node` to version 4 in the GitHub Actions workflows
  .github/workflows/ci.yml
  .github/workflows/publish_website.yml
Labels: test

#17153 Guard `navigator`-object accesses in `src/`-files (issue 15728)
  src/display/font_loader.js
  src/shared/util.js
Labels: core

#17203 Update dependencies and translations to the most recent versions
  gulpfile.mjs
  l10n/cy/viewer.ftl
  l10n/en-GB/viewer.ftl
  l10n/es-CL/viewer.ftl
  l10n/eu/viewer.ftl
  l10n/fur/viewer.ftl
  l10n/gn/viewer.ftl
  l10n/is/viewer.ftl
  l10n/kk/viewer.ftl
  l10n/pt-BR/viewer.ftl
  l10n/sv-SE/viewer.ftl
  l10n/tg/viewer.ftl
  l10n/vi/viewer.ftl
  l10n/zh-CN/viewer.ftl
  package-lock.json
  package.json
Labels: other, dependencies

#17205 Fix the intermittent failures with PageOpen/PageClose test
  test/integration/scripting_spec.mjs
  test/integration/test_utils.mjs
Labels: test

#17204 [Editor] Don't steal the keyboard events when editing mode is enabled
  src/display/editor/tools.js
  test/integration/freetext_editor_spec.mjs
Labels: editor
