Repository mozilla/pdf.js, pull requests merged in 2023-01, with the labels that each got.

#15878 Bump versions in `pdfjs.config`
  pdfjs.config
Labels: other

#15883 Avoid an infinite loop when searching for a single diacritic
  test/unit/pdf_find_controller_spec.js
  web/pdf_find_controller.js
Labels: viewer, text-selection

#15884 Enable the `defaultZoomDelay` option/preference unconditionally, and other (small) improvements
  web/app_options.js
  web/pdf_viewer.js
Labels: viewer

#15880 [api-minor] Remove the `PDFDocumentProxy.stats` getter (PR 15758 follow-up)
  src/core/core_utils.js
  src/core/document.js
  src/core/evaluator.js
  src/core/fonts.js
  src/core/fonts_utils.js
  src/core/parser.js
  src/core/pattern.js
  src/core/xref.js
  src/display/api.js
  src/display/font_loader.js
  src/shared/util.js
  test/unit/api_spec.js
  test/unit/test_utils.js
Labels: core

#15885 Update the `type`/`subtype` at the end of font parsing
  src/core/fonts.js
Labels: font-conversion

#15886 [api-minor] Add the pinch-to-zoom feature (bug 1677933)
  web/app.js
  web/firefoxcom.js
  web/pdf_viewer.js
Labels: viewer

#15891 Reduce duplication in the `accumulateWheelTicks`/`accumulateTouchTicks` methods (PR 15886 follow-up)
  web/app.js
Labels: viewer

#15892 [JS] UserActivation must be enabled before running document actions
  src/scripting_api/event.js
  test/integration/scripting_spec.js
  test/pdfs/.gitignore
  test/pdfs/autoprint.pdf
Labels: regression, form-js

#15896 [GV] Add an option in the find controller to update matches count only when the last page is reached (bug 1803188).
  test/unit/pdf_find_controller_spec.js
  web/app.js
  web/pdf_find_controller.js
Labels: viewer, text-selection

#15857 Delay the loading icon display
  web/pdf_viewer.css
  web/viewer.css
Labels: viewer

#15879 [api-minor] Improve the `useWorkerFetch` default value checks
  src/display/api.js
Labels: core

#15887 Inline the `setPDFNetworkStreamFactory` functionality in `src/display/api.js`
  src/display/api.js
  src/pdf.js
  test/unit/clitests_helper.js
  test/unit/jasmine-boot.js
Labels: core, test

#15850 Remove shadow around each pages (fix issue #15836)
  gulpfile.js
  web/images/shadow.png
  web/pdf_viewer.css
  web/viewer-geckoview.css
  web/viewer.css
Labels: viewer

#15899 Tweak the `--toolbar-border-color` CSS variable (PR 15850 follow-up)
  web/viewer.css
Labels: viewer

#15897 Support parsing encrypted documents in `XRef.indexObjects` (issue 15893)
  src/core/xref.js
  test/pdfs/.gitignore
  test/pdfs/issue15893_reduced.pdf
  test/test_manifest.json
Labels: core, corrupted-pdf

#15904 Remove the `background-color` of the sidebarContent (PR 15850 follow-up)
  web/viewer.css
Labels: viewer

#15906 Upgrade Node.js to version 18 in the CI workflow
  .github/workflows/ci.yml
Labels: test, dependencies

#15909 Add support for smooth pinch-to-zoom on a trackpad (bug 1659492)
  web/app.js
Labels: viewer, ux

#15917 Improve input validation in `PDFDataTransportStream._onReceiveData` (PR 15908 follow-up)
  src/display/api.js
  src/display/transport_stream.js
Labels: core, regression, firefox-specific

#15916 [api-minor] Enabling transferring of data fetched with the `PDFFetchStream` implementation
  src/display/api.js
  src/display/fetch_stream.js
  src/display/network.js
Labels: core

#15905 Improve unit test coverage of `src/core/core_utils.js`
  test/unit/core_utils_spec.js
Labels: core, test

#15924 Update packages and translations
  l10n/be/viewer.properties
  l10n/fur/viewer.properties
  l10n/pt-BR/viewer.properties
  l10n/skr/viewer.properties
  package-lock.json
  package.json
Labels: dependencies

#15923 [Regression] Avoid showing a black canvas during zooming with a `drawingDelay` set (PR 15812 follow-up)
  web/pdf_page_view.js
Labels: viewer, regression, release-blocker

#15925 Update `rimraf` to version 4
  gulpfile.js
  package-lock.json
  package.json
  test/test.js
  test/testutils.js
Labels: dependencies

#15921 Update highlight background when forced colors are active (bug 1759886)
  web/text_layer_builder.css
Labels: viewer, ux

#15920 [api-minor] Enable transferring of TypedArray PDF data by default (PR 15908 follow-up)
  src/display/api.js
  src/display/transport_stream.js
  test/unit/api_spec.js
  web/app_options.js
Labels: core, performance

#15930 Move --scale-factor variable in the viewer container (fix #15929)
  web/pdf_page_view.js
  web/pdf_viewer.css
  web/pdf_viewer.js
Labels: viewer, performance

#15934 Fallback to using the `name` table to infer the encoding for TrueType fonts missing such data (issue 15910)
  src/core/fonts.js
  test/pdfs/.gitignore
  test/pdfs/issue15910.pdf
  test/test_manifest.json
Labels: core, text-selection

#15940 Update the year in the `license_header` files
  src/license_header.js
  src/license_header_libre.js
Labels: other

#15937 Use CSS variables for the textLayer `highlight` colors (PR 15921 follow-up)
  web/annotation_editor_layer_builder.css
  web/annotation_layer_builder.css
  web/text_layer_builder.css
  web/xfa_layer_builder.css
Labels: viewer

#15945 [JBIG2] Ensure that the `decodeInteger` function returns valid integers (issue 15942)
  src/core/jbig2.js
  test/pdfs/issue15942.pdf.link
  test/test_manifest.json
Labels: image-jbig2, image-conversion

#15941 Change 'Current View' to 'Current Page' in the secondary toolbar
  l10n/en-US/viewer.properties
  web/viewer.html
Labels: viewer, ux

#15947 [GV] Avoid to update the finder when the results aren't complete
  test/unit/pdf_find_controller_spec.js
  web/pdf_find_controller.js
Labels: viewer

#15943 [api-minor] Deprecate calling `getDocument` directly with a `PDFDataRangeTransport`-instance
  src/display/api.js
  test/unit/api_spec.js
Labels: core

#15949 Move the `disableAutoFetch` functionality into the `ProgressBar`-class
  web/app.js
  web/ui_utils.js
Labels: viewer

#15948 Tweak `adjustType1ToUnicode` for fonts with a predefined *named* encoding (bug 1811668, PR 14050 follow-up)
  src/core/fonts.js
  test/pdfs/.gitignore
  test/pdfs/bug1811668_reduced.pdf
  test/test_manifest.json
Labels: font-conversion, text-selection

#15957 Try to avoid to interpret wheel events as pinch-to-zoom ones (bug 1810800)
  web/app.js
Labels: viewer, regression

#15959 Tweak the `normalizeWheelEventDelta` helper function
  web/ui_utils.js
Labels: viewer

#15960 Move `ProgressBar`-related CSS variables into the `loadingBar` DOM-element (issue 15958)
  examples/mobile-viewer/viewer.css
  web/ui_utils.js
  web/viewer.css
Labels: viewer

#15965 [JS] Correctly format field with numbers (bug 1811694, bug 1811510)
  src/scripting_api/event.js
  src/scripting_api/field.js
  src/scripting_api/proxy.js
  test/integration/scripting_spec.js
  test/pdfs/.gitignore
  test/pdfs/bug1811510.pdf
  test/pdfs/bug1811694.pdf
  test/unit/scripting_spec.js
Labels: regression, form-js

#15971 Update packages and translations
  gulpfile.js
  l10n/be/viewer.properties
  l10n/cy/viewer.properties
  l10n/de/viewer.properties
  l10n/en-GB/viewer.properties
  l10n/es-AR/viewer.properties
  l10n/es-MX/viewer.properties
  l10n/fy-NL/viewer.properties
  l10n/he/viewer.properties
  l10n/hsb/viewer.properties
  l10n/hu/viewer.properties
  l10n/ia/viewer.properties
  l10n/id/viewer.properties
  l10n/it/viewer.properties
  l10n/kk/viewer.properties
  l10n/ko/viewer.properties
  l10n/nl/viewer.properties
  l10n/oc/viewer.properties
  l10n/pa-IN/viewer.properties
  l10n/pt-BR/viewer.properties
  l10n/skr/viewer.properties
  l10n/sq/viewer.properties
  l10n/sr/viewer.properties
  l10n/sv-SE/viewer.properties
  l10n/tg/viewer.properties
  l10n/uk/viewer.properties
  l10n/vi/viewer.properties
  l10n/zh-CN/viewer.properties
  l10n/zh-TW/viewer.properties
  package-lock.json
  package.json
  test/test.js
  test/testutils.js
Labels: dependencies

#15963 Update various README files to be less specific about the supported JavaScript features
  README.md
  external/dist/README.md
Labels: other

#15966 Simplify setting the `GlobalWorkerOptions` default values (PR 9480 follow-up)
  src/display/worker_options.js
Labels: core

#15954 Tweak the internal handling of the `url`-parameter in `getDocument` (PR 13166 follow-up)
  src/display/api.js
Labels: core

#15964 Only accept non-objects passed to `getDocument` in GENERIC builds
  src/display/api.js
Labels: core

#15972 Change the `PDFViewerApplication.open` method to only accept objects
  web/app.js
Labels: viewer

#15974 Bump versions in `pdfjs.config`
  pdfjs.config
Labels: other

#15973 Remove the transition when displaying the sidebar when the user prefers reduced motion (bug 1813138)
  web/viewer.css
Labels: viewer, accessibility

#15979 Extend `getGlyphMapForStandardFonts` with additional entries (issue 15977)
  src/core/standard_fonts.js
  test/pdfs/.gitignore
  test/pdfs/issue15977_reduced.pdf
  test/test_manifest.json
Labels: font-conversion

#15984 Allow, optionally, using worker-modules during local development
  docs/contents/getting_started/index.md
  src/display/api.js
  src/pdf.worker.js
  web/app.js
Labels: core, viewer
