Repository mozilla/pdf.js, pull requests merged in 2024-07, with the labels that each got.

#18350 Introduce a GitHub Actions workflow for publishing a release and fix `npm publish` warnings about the `package.json` format
  .github/workflows/publish_release.yml
  gulpfile.mjs
Labels: other

#18356 Disable new tab page stuff in Firefox when running tests
  test/test.mjs
Labels: test

#18352 Generate provenance statements on npm publish
  .github/workflows/publish_release.yml
Labels: test

#18358 Fix the repository URL in the `package.json` file for `pdfjs-dist`
  gulpfile.mjs
Labels: other

#18359 Bump the stable version in `pdfjs.config`
  pdfjs.config
Labels: other

#18134 [api-minor][Editor] When switching to editing mode, redraw pages containing editable annotations (bug 1883884)
  src/core/annotation.js
  src/core/document.js
  src/core/worker.js
  src/display/annotation_layer.js
  src/display/annotation_storage.js
  src/display/api.js
  test/integration/annotation_spec.mjs
  test/integration/freetext_editor_spec.mjs
  test/integration/stamp_editor_spec.mjs
  test/integration/test_utils.mjs
  web/annotation_layer_builder.js
  web/pdf_page_view.js
  web/pdf_viewer.js
Labels: editor

#18366 [Editor] Make sure everything is cleaned up when we switch to annotation editor mode
  test/integration/test_utils.mjs
  web/pdf_viewer.js
Labels: viewer, editor

#18349 [api-minor] Remove the deprecated `renderTextLayer` and `updateTextLayer` functions (PR 18104 follow-up)
  src/display/text_layer.js
  src/pdf.js
  test/unit/pdf_spec.js
  web/pdfjs.js
Labels: core

#18369 Use vertical variant of a char when it's in a missing vertical font (bug 1905623)
  src/core/fonts.js
  src/core/fonts_utils.js
  test/pdfs/bug1905623.pdf.link
  test/test_manifest.json
Labels: font-conversion, non-standard-fonts

#15209 [Firefox] Generate a PDF.js default-prefs file that can be used directly in mozilla-central (bug 1905864)
  extensions/firefox/.eslintrc
  extensions/firefox/content/PdfJsDefaultPreferences.sys.mjs
  gulpfile.mjs
  src/license_header.js
  src/license_header_libre.js
Labels: firefox-specific

#18367 Update dependencies and translations to the most recent versions
  gulpfile.mjs
  l10n/zh-TW/viewer.ftl
  package-lock.json
  package.json
Labels: dependencies, l10n

#18374 Make sure the editor is visible before getting its rect
  test/integration/test_utils.mjs
Labels: test

#18389 [Editor] Remove the option enableStamp
  extensions/chromium/preferences_schema.json
  web/app.js
  web/app_options.js
  web/viewer.html
Labels: viewer

#18387 Move the internal API/Worker `isEditing`-state into `RenderingIntentFlag`
  src/core/document.js
  src/core/worker.js
  src/display/api.js
  src/shared/util.js
Labels: core

#18394 Remove the `renderForms` parameter from the Annotation `getOperatorList` methods
  src/core/annotation.js
  src/core/document.js
  test/unit/annotation_spec.js
Labels: annotations

#18393 Check the relevant parameters inside of the `mustBeViewedWhenEditing` method
  src/core/annotation.js
  src/core/document.js
Labels: annotations

#18380 [Editor] Avoid to query ML engine several times for the same image
  src/display/editor/stamp.js
Labels: editor

#18397 Allow to change the toolbar height when changing the pref toolbar.density in Firefox (bug 1171799)
  web/app.js
  web/app_options.js
  web/preferences.js
  web/toolbar.js
Labels: viewer, firefox-specific

#18399 Fix the "must check that charLimit is correctly set" scripting integration test
  test/integration/scripting_spec.mjs
Labels: test

#18398 [Editor] Change the enableML pref for enableAltText (bug 1905923)
  extensions/chromium/preferences_schema.json
  src/display/editor/stamp.js
  src/display/editor/tools.js
  web/app.js
  web/app_options.js
  web/chromecom.js
  web/firefoxcom.js
  web/genericcom.js
Labels: viewer

#18401 Fix orphaned browser processes due to uncaught exceptions in the tests
  test/test.mjs
Labels: test

#18402 Move the "updatedPreference" event listener registration
  web/preferences.js
Labels: viewer, firefox-specific

#18404 Fix the "caches image resources at the document/page level as expected (issue 11878)" unit test
  test/unit/api_spec.js
Labels: test

#18390 Handle toUnicode cMaps that omit leading zeros in hex encoded UTF-16 (issue 18099)
  src/core/evaluator.js
  test/pdfs/.gitignore
  test/pdfs/issue18099_reduced.pdf
  test/unit/api_spec.js
Labels: font-conversion

#18405 Introduce a `waitForScripting` helper function and use it in all scripting integration tests
  test/integration/scripting_spec.mjs
Labels: test

#17962 Use BiDi protocol for Chrome tests
  test/integration/freetext_editor_spec.mjs
  test/test.mjs
Labels: test

#18413 Re-factor `BasePreferences` to essentially be a wrapper around `AppOptions`
  gulpfile.mjs
  web/app.js
  web/app_options.js
  web/preferences.js
Labels: viewer

#18418 [Editor] Wait for 'pagerendered' to switch to editing mode
  web/pdf_viewer.js
Labels: editor

#18416 Fix `ensureMinFontSizeComputed` calculation if `<body>` is a flex container
  src/display/text_layer.js
Labels: text-selection

#18421 Allow e.g. /FitH destinations without additional parameter (bug 1907000)
  src/core/catalog.js
  test/pdfs/.gitignore
  test/pdfs/bug1907000_reduced.pdf
  test/unit/api_spec.js
  web/pdf_link_service.js
Labels: core, viewer, regression

#18412 Also update the width/unicode data when replacing missing glyphs in non-embedded Type1 fonts (issue 18059)
  src/core/fonts.js
  test/pdfs/.gitignore
  test/pdfs/issue18059.pdf
  test/test_manifest.json
Labels: font-conversion, font-type1

#18419 [Editor] Update the freetext annotation dictionary instead of creating a new one when updating an existing freetext
  src/core/annotation.js
  src/core/primitives.js
  test/unit/annotation_spec.js
Labels: annotations, editor

#18417 Create absolute filter-URLs when needed in `DOMFilterFactory` (issue 18406)
  src/display/display_utils.js
  test/pdfs/.gitignore
  test/pdfs/issue16287.pdf
  test/test_manifest.json
Labels: core

#18423 Remove the remaining `zoomDisabledTimeout` usage (issue 17727)
  web/app.js
Labels: viewer

#18425 [Editor] Make editor toolbars usable whatever their z-index (bug 1879104)
  test/integration/highlight_editor_spec.mjs
  test/integration/test_utils.mjs
  web/annotation_editor_layer_builder.css
Labels: editor

#18424 [Editor] Disable existing highlights when drawing a new one (bug 1879035)
  src/display/editor/annotation_editor_layer.js
  src/display/editor/tools.js
  test/integration/highlight_editor_spec.mjs
  web/annotation_editor_layer_builder.css
Labels: editor

#18432 Update dependencies to the most recent versions and update the JS/CSS files for the new Prettier/Stylelint versions
  package-lock.json
  package.json
  src/core/worker.js
  src/display/api.js
  web/app_options.js
  web/l10n.js
  web/text_layer_builder.css
Labels: dependencies

#18433 Disable network connections to Contile for the tests
  test/test.mjs
Labels: test

#18434 Remove obsolete `pdfjs-dist` code from the Gulpfile
  gulpfile.mjs
Labels: other

#18429 [Editor] Add an option to use the new 'add an image' flow (bug 1907207)
  extensions/chromium/preferences_schema.json
  src/display/editor/tools.js
  web/app.js
  web/app_options.js
  web/pdf_viewer.js
Labels: editor

#18430 Fix `DOMFilterFactory.#createUrl` in MOZCENTRAL builds (18417 PR follow-up)
  src/display/display_utils.js
Labels: core, regression, firefox-specific

#18440 [Editor] When in non-editing mode, add a new editor only once the editing mode has switched
  src/display/editor/tools.js
  test/integration/highlight_editor_spec.mjs
  test/pdfs/.gitignore
  test/pdfs/file_pdfjs_test.pdf
  web/pdf_viewer.js
Labels: viewer, editor

#18445 Remove active smask when restoring the initial canvas state
  src/display/canvas.js
  test/pdfs/issue18444.pdf.link
  test/test_manifest.json
Labels: smask

#18449 Add the possibility to change some pdfjs preferences from the viewer (bug 1908483)
  web/firefoxcom.js
  web/preferences.js
Labels: viewer, firefox-specific

#18453 Allow /XYZ destinations without zoom parameter (issue 18408)
  src/core/catalog.js
  test/pdfs/.gitignore
  test/pdfs/issue18408_reduced.pdf
  test/unit/api_spec.js
  web/pdf_link_service.js
Labels: core, viewer, regression

#18448 Include additional data when fetching browser preferences in the PDF Viewer (bug 1908401)
  web/app.js
  web/app_options.js
  web/external_services.js
  web/firefoxcom.js
Labels: viewer, firefox-specific

#18454 [Editor] Allow to change a preference from the editor UI manager
  src/display/editor/tools.js
  web/app.js
Labels: viewer

#18461 Load the image-to-text model when opening the pdf viewer in Firefox (bug 1908938)
  src/display/editor/stamp.js
  src/display/editor/tools.js
  web/app.js
  web/firefoxcom.js
  web/genericcom.js
Labels: firefox-specific, editor

#18464 Reduce a tiny bit of duplication in `PDFViewerApplication.setTitleUsingUrl`
  web/app.js
Labels: viewer

#18463 Re-factor the code to remove all uses of `PDFViewerApplication.downloadComplete`
  web/app.js
  web/ui_utils.js
Labels: viewer

#18450 Add more validation when setting `AppOptions` (PR 18413 follow-up)
  web/app_options.js
Labels: viewer

#18470 Move the `Preferences` initialization as early as possible
  web/app.js
Labels: viewer

#18469 Introduce some `Map`-usage in the AppOptions
  web/app_options.js
Labels: viewer

#18471 Add a pref containing the url for the sumo page about alt text (bug 1909097)
  extensions/chromium/preferences_schema.json
  web/app.js
  web/app_options.js
  web/firefoxcom.js
Labels: viewer, firefox-specific

#18465 Disable system fonts on Android (issue 18210)
  web/app.js
  web/app_options.js
  web/viewer-geckoview.html
  web/viewer-geckoview.js
Labels: viewer, os-android

#18472 Add the possibility to delete a model (bug 1908939)
  web/firefoxcom.js
  web/genericcom.js
Labels: viewer, firefox-specific

#18468 Fallback on DeviceGray when a colorspace cannot be parsed
  src/core/colorspace.js
Labels: core

#18475 Remove the unused `AppOptions.remove` method
  web/app_options.js
Labels: viewer

#18476 Re-factor how the "docBaseUrl" API-option is set in the viewer
  web/app.js
  web/app_options.js
Labels: viewer

#18480 Add better support for AppOptions with multiple types (PR 18465 follow-up)
  web/app_options.js
Labels: viewer

#18484 Add a pref to know if the alt-text must be automatically generated (bug 1909310)
  extensions/chromium/preferences_schema.json
  web/app.js
  web/app_options.js
  web/firefoxcom.js
Labels: firefox-specific, editor

#18483 Remove the `streamqueue` dependency
  gulpfile.mjs
  package-lock.json
  package.json
Labels: dependencies

#18486 Replace the GENERIC-only "locale" with "localeProperties" in AppOptions
  web/app.js
  web/app_options.js
  web/genericcom.js
Labels: viewer

#18493 [Editor] Correctly save a non-ascii alt text
  src/core/annotation.js
  src/core/core_utils.js
  src/core/struct_tree.js
  test/unit/api_spec.js
Labels: annotations, editor

#18495 Consistently dispatch events, if needed, when setting AppOptions
  web/app_options.js
Labels: viewer

#18500 Bump the stable version in `pdfjs.config`
  pdfjs.config
Labels: other

#18502 Shorten the errors mentioning API parameters in `BaseCMapReaderFactory` and `BaseStandardFontDataFactory`
  src/display/base_factory.js
  test/unit/cmap_spec.js
Labels: core

#18501 Initialize all user-options upfront in AppOptions
  web/app_options.js
Labels: viewer

#18481 Disable link annotations during text selection
  test/integration/test_utils.mjs
  test/integration/text_layer_spec.mjs
  web/annotation_layer_builder.css
  web/text_layer_builder.css
  web/text_layer_builder.js
Labels: viewer, text-selection, annotations

#18504 Ignore non-dictionary nodes when parsing StructTree data (issue 18503)
  src/core/struct_tree.js
  test/pdfs/issue18503.pdf.link
  test/test_manifest.json
  test/unit/api_spec.js
Labels: core

#18505 Stop testing in Node.js 21 since it's reached end-of-life
  .github/workflows/ci.yml
Labels: test, node-specific

#18506 Update dependencies to the most recent versions
  package-lock.json
  package.json
  test/test.mjs
Labels: dependencies

#18507 Remove `PDFWorkerUtil` and move its contents into `PDFWorker` instead
  src/display/api.js
  test/unit/api_spec.js
Labels: core

#18509 Remove the `globals` dependency
  package-lock.json
  package.json
Labels: dependencies

#18510 Improve how the findbar's toggle button is referenced in the viewer code
  web/app.js
  web/toolbar.js
  web/viewer.js
Labels: viewer

#18492 [Editor] Implement the new alt text flow (bug 1909604)
  gulpfile.mjs
  l10n/en-US/viewer.ftl
  src/display/editor/alt_text.js
  src/display/editor/editor.js
  src/display/editor/stamp.js
  src/display/editor/tools.js
  web/annotation_editor_layer_builder.css
  web/app.js
  web/app_options.js
  web/dialog.css
  web/firefoxcom.js
  web/genericcom.js
  web/images/altText_disclaimer.svg
  web/images/altText_spinner.svg
  web/images/altText_warning.svg
  web/images/messageBar_closingButton.svg
  web/images/messageBar_warning.svg
  web/new_alt_text_manager.js
  web/stubs-geckoview.js
  web/viewer-geckoview.html
  web/viewer.html
  web/viewer.js
Labels: editor

#18516 [Editor] Add a checkerboard behind the image preview in the new alt-text dialog in order to see its potential transparency
  src/display/editor/stamp.js
Labels: editor

#18526 [Editor] Allow Float32Array for quadpoints in annotations (bug 1907958)
  src/core/core_utils.js
  test/driver.js
Labels: printing, editor
